const K='moje-finanse-v14',O='moje-finanse-v13',M=['Sty','Lut','Mar','Kwi','Maj','Cze','Lip','Sie','Wrz','Paź','Lis','Gru'],$=x=>document.getElementById(x),N=n=>+n||0,F=n=>new Intl.NumberFormat('pl-PL',{style:'currency',currency:'PLN',maximumFractionDigits:0}).format(Math.round(N(n))),T=new Date(),TODAY=T.toISOString().slice(0,10),CY=T.getFullYear();
function blank(){return{salary:M.map(()=>({net:null,bonus:null,locked:true})),company:M.map(()=>({revenue:null,costs:null,vat:null,locked:true}))}}
function nl(l){let b=N(l.balance);return{name:l.name||'Kredyt',balance:b,originalBalance:N(l.originalBalance)||N(l.startBalance)||b,payment:N(l.payment),rate:N(l.rate),months:N(l.months),extraMonthly:N(l.extraMonthly),oneOff:N(l.oneOff),asOfDate:l.asOfDate||TODAY,overpayMode:l.overpayMode==='reduce_payment'?'reduce_payment':'shorten',history:Array.isArray(l.history)?l.history.map(h=>({month:h.month||TODAY.slice(0,7),paid:N(h.paid),extra:N(h.extra),balanceAfter:h.balanceAfter===''||h.balanceAfter==null?null:N(h.balanceAfter),note:h.note||''})):[]}}
function def(){return{selectedYear:CY,years:{},loans:[],settings:{threshold:120000,reduction:3600,kup:250,ppkEmp:2,ppkEr:1.5}}}
function norm(s){let d=def(),o={...d,...s,settings:{...d.settings,...s.settings},years:s.years||{},loans:(s.loans||[]).map(nl)};for(let y in o.years){let z=o.years[y]||{},b=blank();o.years[y]={salary:M.map((_,i)=>({...b.salary[i],...(z.salary?.[i]||{})})),company:M.map((_,i)=>({...b.company[i],...(z.company?.[i]||{})}))}}return o}
function migrate(o){let s=def();s.years['2026']=blank();s.years['2026'].salary=M.map((_,i)=>({net:o.months?.[i]?.net??null,bonus:o.months?.[i]?.bonus??null,locked:true}));s.years['2026'].company=M.map((_,i)=>({revenue:o.company?.[i]?.revenue??null,costs:o.company?.[i]?.costs??null,vat:o.company?.[i]?.vat??null,locked:true}));s.loans=(o.loans||[]).map(x=>nl({...x,asOfDate:x.asOfDate||TODAY}));s.settings={...s.settings,...o.settings};return s}
function load(){try{let a=JSON.parse(localStorage.getItem(K));if(a)return norm(a)}catch{}try{let a=JSON.parse(localStorage.getItem(O));if(a)return migrate(a)}catch{}return def()}let S=load();function Y(){let y=String(S.selectedYear);return S.years[y]||(S.years[y]=blank())}function save(){localStorage.setItem(K,JSON.stringify(S))}Y();save();
function tax(b){let s=S.settings,t=s.threshold;return b<=t?Math.max(0,b*.12-s.reduction):Math.max(0,t*.12+(b-t)*.32-s.reduction)}function fg(g,y){let s=g*.1371,h=(g-s)*.09,pe=g*S.settings.ppkEmp/100,er=g*S.settings.ppkEr/100,base=Math.max(0,g-s-S.settings.kup+er),pit=Math.max(0,tax(y+base)-tax(y));return{g,net:Math.max(0,g-s-h-pit-pe),base,pe,er}}function fn(n,y){if(!n)return fg(0,y);let a=0,b=n*2.7+4000;for(let i=0;i<50;i++){let m=(a+b)/2;fg(m,y).net<n?a=m:b=m}return fg((a+b)/2,y)}
function hist(type,key,year,month){let v=[];Object.keys(S.years).sort().forEach(q=>{let yy=+q,a=S.years[q][type]||[];a.forEach((r,i)=>{if(yy<year||(yy===year&&i<month)){if(type==='salary'){let x=N(r.net)+N(r.bonus);if(x>0)v.push(x)}else if(N(r.revenue)||N(r.costs)||N(r.vat))v.push(N(r[key]))}})});return v.slice(-12)}function avg(a){return a.length?a.reduce((x,y)=>x+y,0)/a.length:0}
function sal(){let y=0,rows=Y().salary.map((r,i)=>{let act=N(r.net)+N(r.bonus)>0,total=act?N(r.net)+N(r.bonus):avg(hist('salary','',S.selectedYear,i)),p=fn(total,y);y+=p.base;return{...p,total,n:act?N(r.net):total,b:act?N(r.bonus):0,actual:act,y}});let a=rows.filter(x=>x.actual);return{rows,avg:avg(a.map(x=>x.total)),count:a.length,last:Math.max(-1,...rows.map((r,i)=>r.actual?i:-1))}}function comp(){let rows=Y().company.map((r,i)=>{let act=N(r.revenue)||N(r.costs)||N(r.vat),av=k=>avg(hist('company',k,S.selectedYear,i));return{actual:!!act,revenue:act?N(r.revenue):av('revenue'),costs:act?N(r.costs):av('costs'),vat:act?N(r.vat):av('vat')}});return{rows}}
function show(v){document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active',x.id===v));document.querySelectorAll('.nav button[data-v]').forEach(x=>x.classList.toggle('active',x.dataset.v===v));scrollTo(0,0);render()}function changeYear(d){S.selectedYear+=d;Y();save();render()}
function addM(date,n){let d=new Date(date+'T12:00:00');d.setMonth(d.getMonth()+n);return d}function annuity(balance,r,n){if(n<=0)return balance;if(!r)return balance/n;return balance*r/(1-Math.pow(1+r,-n))}
function histSorted(l){return [...(l.history||[])].sort((a,b)=>a.month.localeCompare(b.month))}
function actualSeries(l){let rows=[{date:new Date(l.asOfDate+'T12:00:00'),balance:N(l.balance),kind:'actual'}],b=N(l.balance),r=N(l.rate)/1200;for(let h of histSorted(l)){let d=new Date(h.month+'-01T12:00:00');if(d<rows[0].date)continue;let interest=b*r,total=N(h.paid)+N(h.extra);b=h.balanceAfter!=null?Math.max(0,N(h.balanceAfter)):Math.max(0,b+interest-total);rows.push({date:d,balance:b,kind:'actual',paid:N(h.paid),extra:N(h.extra),note:h.note||''})}return rows}
function loanPoint(l){let a=actualSeries(l),q=a[a.length-1];return{balance:N(q.balance),date:q.date,rows:a}}
function baseTerm(l,balance){let r=N(l.rate)/1200,p=N(l.payment),m=0,b=balance;while(b>.01&&m<600&&p>b*r){b=Math.max(0,b-(p-b*r));m++}return m}
function sched(l,e=0,o=0){let p0=loanPoint(l),b=Math.max(0,p0.balance-o),r=N(l.rate)/1200,baseP=N(l.payment),m=0,interest=0,rows=[...p0.rows.map(x=>({...x}))],start=p0.date,mode=l.overpayMode||'shorten',remaining=baseTerm(l,p0.balance);while(b>.01&&m<600){let it=b*r,regular=mode==='reduce_payment'?annuity(b,r,Math.max(1,remaining)):baseP,pay=regular+N(e);if(pay<=it+.001)break;b=Math.max(0,b-(pay-it));interest+=it;m++;remaining=Math.max(0,remaining-1);rows.push({date:new Date(start.getFullYear(),start.getMonth()+m,1,12),balance:b,kind:'forecast',regular,extra:N(e)});if(mode==='reduce_payment'&&remaining<=0)break}return{rows,m,interest,startBalance:p0.balance}}
function loanYearSpend(){return S.loans.reduce((a,l)=>{let d=loanPoint(l).date,y=S.selectedYear,m=y<d.getFullYear()?0:y===d.getFullYear()?12-d.getMonth():12;return a+m*(N(l.payment)+N(l.extraMonthly))+(y===d.getFullYear()?N(l.oneOff):0)},0)}