/* Moje Finanse 1.6 — adaptacyjne wykresy kredytów */
(function(){
const oldLoans=window.loans;
const DAY=86400000;
const q=id=>document.getElementById(id);
function num(v){return +v||0}
function dparse(s){return new Date((s||TODAY)+'T12:00:00')}
function ymd(d){return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')}
function mlabel(d){return String(d.getMonth()+1).padStart(2,'0')+'.'+String(d.getFullYear()).slice(-2)}
function days(a,b){return Math.max(0,Math.round((b-a)/DAY))}
function due(y,m,day){const last=new Date(y,m+1,0).getDate();return new Date(y,m,Math.min(day,last),12)}
function firstDue(l){const b=dparse(l.asOfDate),day=Math.max(1,Math.min(31,num(l.dueDay)||b.getDate()));let d=due(b.getFullYear(),b.getMonth(),day);if(d<=b)d=due(b.getFullYear(),b.getMonth()+1,day);return d}
function payFor(balance,rate,months){if(months<=0)return balance;const r=rate/1200;if(!r)return balance/months;return balance*r/(1-Math.pow(1+r,-months))}
function remaining(l,b){if(num(l.months)>0)return Math.max(1,num(l.months));if(l.loanType==='zero')return Math.max(1,Math.ceil(b/Math.max(1,num(l.payment))));const r=num(l.rate)/1200,p=num(l.payment);let n=0;if(p<=b*r)return 600;while(b>.01&&n<600){b=Math.max(0,b-(p-b*r));n++}return Math.max(1,n)}
function apply(balance,l,last,payDate,regular,extra){const dd=days(last,payDate),interest=l.loanType==='zero'?0:balance*(num(l.rate)/100)/365*dd,reg=Math.max(0,num(regular)),toInt=Math.min(reg,interest),principal=Math.max(0,reg-toInt),unpaid=Math.max(0,interest-toInt),over=Math.max(0,num(extra));return{interest,principal,balance:Math.max(0,balance-principal-over+unpaid),days:dd,total:reg+over}}
function timeline(l,plan){let balance=num(l.balance),base=dparse(l.asOfDate),last=base,rows=[],rem=remaining(l,balance);const hist=[...(l.history||[])].sort((a,b)=>(a.paymentDate||a.month).localeCompare(b.paymentDate||b.month));for(const h of hist){const d=dparse(h.paymentDate||h.month+'-'+String(l.dueDay||1).padStart(2,'0'));if(d<base)continue;const regular=h.paid?num(h.regularPaid):0,extra=h.isOverpayment?num(h.extra):0,res=apply(balance,l,last,d,regular,extra);if(h.balanceAfter!=null)res.balance=Math.max(0,num(h.balanceAfter));balance=res.balance;last=d;rem=Math.max(0,rem-1);rows.push({date:d,month:h.month||ymd(d),kind:'actual',balance,regular,extra,interest:res.interest,principal:res.principal,payment:regular+extra})}
let d=firstDue(l);while(d<=last)d=due(d.getFullYear(),d.getMonth()+1,l.dueDay||1);let guard=0,one=false,regular=num(l.payment);while(balance>.01&&guard<600){if(l.overpayMode==='reduce_payment'&&rem>0)regular=payFor(balance,num(l.rate),rem);const accrued=l.loanType==='zero'?0:balance*(num(l.rate)/100)/365*days(last,d),planned=Math.min(balance+accrued,regular||num(l.payment));let extra=plan?num(l.extraMonthly):0;if(plan&&!one&&num(l.oneOff)>0){extra+=num(l.oneOff);one=true}const res=apply(balance,l,last,d,planned,extra);balance=res.balance;rows.push({date:new Date(d),month:ymd(d),kind:'forecast',balance,regular:planned,extra,interest:res.interest,principal:res.principal,payment:planned+extra});last=new Date(d);rem=Math.max(0,rem-1);d=due(d.getFullYear(),d.getMonth()+1,l.dueDay||1);guard++;if(l.overpayMode==='reduce_payment'&&rem<=0&&balance>.01)rem=1}
return rows}
function geometry(count){let step;if(count<=12)step=62;else if(count<=24)step=48;else if(count<=48)step=40;else if(count<=96)step=34;else step=30;const w=Math.max(720,90+Math.max(1,count-1)*step+50);return{step,w,left:52,right:26,top:18,balanceBottom:145,paymentTop:166,paymentBottom:218,labelY:252,height:266}}
function tooltip(r){return `${mlabel(r.date)} • rata ${Math.round(r.regular)} zł${r.extra?` • nadpłata ${Math.round(r.extra)} zł`:''} • saldo ${Math.round(r.balance)} zł`}
function loanSvg(l){const normal=timeline(l,false),planned=timeline(l,true),rows=normal.length?normal:planned;if(!rows.length)return'';const g=geometry(Math.max(normal.length,planned.length)),maxBal=Math.max(1,num(l.originalBalance),...normal.map(r=>r.balance),...planned.map(r=>r.balance)),maxPay=Math.max(1,...normal.map(r=>r.payment),...planned.map(r=>r.payment));const x=i=>g.left+i*g.step,yBal=v=>g.top+(1-v/maxBal)*(g.balanceBottom-g.top),payH=v=>Math.max(2,v/maxPay*(g.paymentBottom-g.paymentTop));const barW=Math.max(12,Math.min(24,g.step*.48));
const labels=rows.map((r,i)=>`<text x="${x(i)}" y="${g.labelY}" text-anchor="middle" fill="#73819a" font-size="8.5">${mlabel(r.date)}</text>`).join('');
const paymentBars=normal.map((r,i)=>{const hReg=payH(r.regular),hEx=r.extra?payH(r.extra):0,y=g.paymentBottom-hReg-hEx,fill=r.kind==='actual'?'#38b96a':'#3976dc',op=r.kind==='actual'?'.72':'.42';return`<g><title>${tooltip(r)}</title><rect x="${x(i)-barW/2}" y="${g.paymentBottom-hReg}" width="${barW}" height="${hReg}" rx="3" fill="${fill}" opacity="${op}"/>${hEx?`<rect x="${x(i)-barW/2}" y="${y}" width="${barW}" height="${hEx}" rx="3" fill="#f4a126" opacity=".82"/>`:''}</g>`}).join('');
const pts=a=>a.map((r,i)=>`${x(i)},${yBal(r.balance)}`).join(' ');const actualCount=normal.filter(r=>r.kind==='actual').length,actual=normal.slice(0,actualCount),future=normal.slice(Math.max(0,actualCount-1)),plan=planned.slice(Math.max(0,actualCount-1));
return`<svg viewBox="0 0 ${g.w} ${g.height}" style="width:${g.w}px" preserveAspectRatio="none"><line x1="${g.left-12}" y1="${g.balanceBottom}" x2="${g.w-g.right}" y2="${g.balanceBottom}" stroke="#dfe5ec"/><line x1="${g.left-12}" y1="${g.paymentTop-8}" x2="${g.w-g.right}" y2="${g.paymentTop-8}" stroke="#e9edf2" stroke-dasharray="4 5"/>${actual.length?`<polyline points="${pts(actual)}" fill="none" stroke="#38b96a" stroke-width="5" stroke-linecap="round" stroke-linejoin="round"/>`:''}${future.length?`<polyline points="${pts(future)}" fill="none" stroke="#3976dc" stroke-width="4" stroke-linecap="round" stroke-linejoin="round"/>`:''}${plan.length?`<polyline points="${pts(plan)}" fill="none" stroke="#df5963" stroke-width="4" stroke-dasharray="8 6" stroke-linecap="round" stroke-linejoin="round"/>`:''}${paymentBars}<text x="${g.left-10}" y="${g.paymentTop-13}" fill="#8b97a9" font-size="8">RATY / MIESIĄC</text>${labels}</svg>`}
function overviewSvg(){if(!S.loans.length)return'';const loanData=S.loans.map(l=>timeline(l,true)),starts=S.loans.map(l=>dparse(l.asOfDate)),start=new Date(Math.min(...starts.map(d=>d.getTime()))),ends=loanData.map(a=>a.at(-1)?.date||start),end=new Date(Math.max(...ends.map(d=>d.getTime()))),count=Math.max(1,(end.getFullYear()-start.getFullYear())*12+end.getMonth()-start.getMonth()+1),rows=[];for(let i=0;i<count;i++){const d=due(start.getFullYear(),start.getMonth()+i,1);let bal=0,pay=0;loanData.forEach((arr,idx)=>{let r=arr.filter(z=>z.date<=d).at(-1);if(!r){bal+=num(S.loans[idx].balance);return}bal+=num(r.balance);if(r.date.getFullYear()===d.getFullYear()&&r.date.getMonth()===d.getMonth())pay+=num(r.payment)});rows.push({date:d,balance:bal,payment:pay})}
const g=geometry(rows.length),maxBal=Math.max(1,...rows.map(r=>r.balance)),maxPay=Math.max(1,...rows.map(r=>r.payment)),x=i=>g.left+i*g.step,yBal=v=>g.top+(1-v/maxBal)*(g.balanceBottom-g.top),payH=v=>Math.max(2,v/maxPay*(g.paymentBottom-g.paymentTop)),barW=Math.max(12,Math.min(24,g.step*.48)),bars=rows.map((r,i)=>`<g><title>${mlabel(r.date)} • raty razem ${Math.round(r.payment)} zł • saldo ${Math.round(r.balance)} zł</title><rect x="${x(i)-barW/2}" y="${g.paymentBottom-payH(r.payment)}" width="${barW}" height="${payH(r.payment)}" rx="3" fill="#3976dc" opacity=".5"/></g>`).join(''),line=rows.map((r,i)=>`${x(i)},${yBal(r.balance)}`).join(' '),labels=rows.map((r,i)=>`<text x="${x(i)}" y="${g.labelY}" text-anchor="middle" fill="#73819a" font-size="8.5">${mlabel(r.date)}</text>`).join('');return`<svg viewBox="0 0 ${g.w} ${g.height}" style="width:${g.w}px" preserveAspectRatio="none"><line x1="${g.left-12}" y1="${g.balanceBottom}" x2="${g.w-g.right}" y2="${g.balanceBottom}" stroke="#dfe5ec"/><line x1="${g.left-12}" y1="${g.paymentTop-8}" x2="${g.w-g.right}" y2="${g.paymentTop-8}" stroke="#e9edf2" stroke-dasharray="4 5"/><polyline points="${line}" fill="none" stroke="#3976dc" stroke-width="4" stroke-linecap="round" stroke-linejoin="round"/>${bars}<text x="${g.left-10}" y="${g.paymentTop-13}" fill="#8b97a9" font-size="8">SUMA RAT / MIESIĄC</text>${labels}</svg>`}
function enhance(){const cards=[...document.querySelectorAll('#loanList .loan')];cards.forEach((card,i)=>{const box=card.querySelector('.loanUnifiedChart');if(!box||!S.loans[i])return;box.innerHTML=loanSvg(S.loans[i]);const head=card.querySelector('.loanChartHead small');if(head)head.textContent='linia = saldo • słupki = rata w KAŻDYM miesiącu • pomarańczowy = nadpłata';const legend=box.nextElementSibling;if(legend&&legend.classList.contains('legend'))legend.innerHTML='<span class="green">— saldo rzeczywiste</span><span><i class="lineSolid"></i> saldo prognoza</span><span><i class="lineDash"></i> plan nadpłat</span><span><i class="monthlyPayLegend"></i> rata miesiąca</span><span><i class="monthlyExtraLegend"></i> nadpłata</span>'});const ov=q('loanOverview');if(ov){const box=ov.querySelector('.overviewChart');if(box)box.innerHTML=overviewSvg();const small=ov.querySelector('.loanChartHead small');if(small)small.textContent='linia = łączne saldo • słupek = suma rat w każdym miesiącu'}}
window.loans=function(){oldLoans();enhance()};
})();