/* Moje Finanse 1.8 — stała baza bez nadpłat + rzeczywisty wpływ nadpłat */
(function(){
const prevLoans=window.loans;
const DAY=86400000;
const $id=id=>document.getElementById(id);
const n=v=>+v||0;
const money=v=>F(n(v));
function dparse(s){return new Date((s||TODAY)+'T12:00:00')}
function ym(d){return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')}
function ml(d){return String(d.getMonth()+1).padStart(2,'0')+'.'+String(d.getFullYear()).slice(-2)}
function days(a,b){return Math.max(0,Math.round((b-a)/DAY))}
function due(y,m,day){let last=new Date(y,m+1,0).getDate();return new Date(y,m,Math.min(day,last),12)}
function firstDue(l){let b=dparse(l.asOfDate),day=Math.max(1,Math.min(31,n(l.dueDay)||b.getDate())),d=due(b.getFullYear(),b.getMonth(),day);if(d<=b)d=due(b.getFullYear(),b.getMonth()+1,day);return d}
function annuity(balance,rate,months){if(months<=0)return balance;let r=rate/1200;if(!r)return balance/months;return balance*r/(1-Math.pow(1+r,-months))}
function term(l,b){if(n(l.months)>0)return Math.max(1,n(l.months));if(l.loanType==='zero')return Math.max(1,Math.ceil(b/Math.max(1,n(l.payment))));let r=n(l.rate)/1200,p=n(l.payment),m=0;if(p<=b*r)return 600;while(b>.01&&m<600){b=Math.max(0,b-(p-b*r));m++}return Math.max(1,m)}
function apply(balance,l,last,date,regular,extra){let dd=days(last,date),interest=l.loanType==='zero'?0:balance*(n(l.rate)/100)/365*dd,reg=Math.max(0,n(regular)),toInt=Math.min(reg,interest),principal=Math.max(0,reg-toInt),unpaid=Math.max(0,interest-toInt),over=Math.max(0,n(extra));return{interest,principal,extra:over,balance:Math.max(0,balance-principal-over+unpaid),payment:reg+over,days:dd}}
function fixedBaseline(l){let balance=n(l.balance),last=dparse(l.asOfDate),d=firstDue(l),rem=term(l,balance),rows=[],guard=0,regular=n(l.payment);while(balance>.01&&guard<600){let accrued=l.loanType==='zero'?0:balance*(n(l.rate)/100)/365*days(last,d),planned=Math.min(balance+accrued,regular||n(l.payment)),res=apply(balance,l,last,d,planned,0);balance=res.balance;rows.push({date:new Date(d),month:ym(d),balance,regular:planned,extra:0,payment:planned,interest:res.interest,principal:res.principal,kind:'baseline'});last=new Date(d);rem=Math.max(0,rem-1);d=due(d.getFullYear(),d.getMonth()+1,l.dueDay||1);guard++}return rows}
function liveTimeline(l,includeFuturePlan){let balance=n(l.balance),base=dparse(l.asOfDate),last=base,rows=[],rem=term(l,balance),hist=[...(l.history||[])].sort((a,b)=>(a.paymentDate||a.month).localeCompare(b.paymentDate||b.month));for(const h of hist){let d=dparse(h.paymentDate||h.month+'-'+String(l.dueDay||1).padStart(2,'0'));if(d<base)continue;let regular=h.paid?n(h.regularPaid):0,extra=h.isOverpayment?n(h.extra):0,res=apply(balance,l,last,d,regular,extra);if(h.balanceAfter!=null)res.balance=Math.max(0,n(h.balanceAfter));balance=res.balance;last=d;rem=Math.max(0,rem-1);rows.push({date:d,month:h.month||ym(d),balance,regular,extra,payment:regular+extra,interest:res.interest,principal:res.principal,kind:'actual',paid:!!h.paid})}
let d=firstDue(l);while(d<=last)d=due(d.getFullYear(),d.getMonth()+1,l.dueDay||1);let regular=n(l.payment),guard=0,one=false;while(balance>.01&&guard<600){if(l.overpayMode==='reduce_payment'&&rem>0)regular=annuity(balance,n(l.rate),rem);let accrued=l.loanType==='zero'?0:balance*(n(l.rate)/100)/365*days(last,d),planned=Math.min(balance+accrued,regular||n(l.payment)),extra=includeFuturePlan?n(l.extraMonthly):0;if(includeFuturePlan&&!one&&n(l.oneOff)>0){extra+=n(l.oneOff);one=true}let res=apply(balance,l,last,d,planned,extra);balance=res.balance;rows.push({date:new Date(d),month:ym(d),balance,regular:planned,extra,payment:planned+extra,interest:res.interest,principal:res.principal,kind:'forecast'});last=new Date(d);rem=Math.max(0,rem-1);d=due(d.getFullYear(),d.getMonth()+1,l.dueDay||1);guard++;if(l.overpayMode==='reduce_payment'&&rem<=0&&balance>.01)rem=1}return rows}
function geom(count){let step=count<=12?64:count<=24?48:count<=48?40:count<=96?34:30;return{step,w:Math.max(760,100+Math.max(1,count-1)*step+50),left:54,right:28,top:20,balBottom:145,payTop:167,payBottom:220,labelY:254,height:270}}
function composition(l){let live=liveTimeline(l,false),actual=live.filter(r=>r.kind==='actual'),regularPrincipal=actual.reduce((s,r)=>s+n(r.principal),0),extra=actual.reduce((s,r)=>s+n(r.extra),0),remaining=actual.length?n(actual.at(-1).balance):n(l.balance),base=Math.max(n(l.originalBalance),regularPrincipal+extra+remaining,1),paidPct=Math.max(0,Math.min(100,regularPrincipal/base*100)),extraPct=Math.max(0,Math.min(100,extra/base*100)),remainPct=Math.max(0,100-paidPct-extraPct);return`<div class="debtComposition"><div class="debtCompHead"><b>Kapitał kredytu</b><span>${money(base)}</span></div><div class="debtCompBar"><i class="dcPaid" style="width:${paidPct}%"></i><i class="dcExtra" style="width:${extraPct}%"></i><i class="dcRemain" style="width:${remainPct}%"></i></div><div class="debtCompLegend"><span><i class="dcDot paid"></i>spłacony ratami <b>${money(regularPrincipal)}</b></span><span><i class="dcDot extra"></i>nadpłacony <b>${money(extra)}</b></span><span><i class="dcDot remain"></i>pozostało <b>${money(remaining)}</b></span></div></div>`}
function chart(l){let baseline=fixedBaseline(l),live=liveTimeline(l,false),plan=liveTimeline(l,true),count=Math.max(baseline.length,live.length,plan.length),g=geom(count),maxBal=Math.max(1,n(l.originalBalance),n(l.balance),...baseline.map(r=>r.balance),...live.map(r=>r.balance),...plan.map(r=>r.balance)),maxPay=Math.max(1,...baseline.map(r=>r.payment),...live.map(r=>r.payment),...plan.map(r=>r.payment));let x=i=>g.left+i*g.step,y=v=>g.top+(1-v/maxBal)*(g.balBottom-g.top),ph=v=>Math.max(2,v/maxPay*(g.payBottom-g.payTop)),bw=Math.max(13,Math.min(25,g.step*.5));
let histMap={};(l.history||[]).forEach(h=>histMap[h.month]=h);
let bars=live.map((r,i)=>{let h=histMap[r.month],planned=r.kind==='actual'?Math.max(n(l.payment),n(r.regular)):n(r.regular),paid=h?.paid?n(h.regularPaid):0,extra=h?.isOverpayment?n(h.extra):0,baseH=ph(planned),paidH=ph(Math.min(paid,planned)),extraH=extra?ph(extra):0;let plannedY=g.payBottom-baseH,paidY=g.payBottom-paidH,extraY=g.payBottom-baseH-extraH;return`<g><title>${ml(r.date)} • rata ${Math.round(planned)} zł${paid?` • wpłacono ${Math.round(paid)} zł`:''}${extra?` • nadpłata ${Math.round(extra)} zł`:''}</title><rect x="${x(i)-bw/2}" y="${plannedY}" width="${bw}" height="${baseH}" rx="3" fill="#cfe2fb"/><rect x="${x(i)-bw/2}" y="${paidY}" width="${bw}" height="${paidH}" rx="3" fill="#38b96a"/>${extraH?`<rect x="${x(i)-bw/2}" y="${extraY}" width="${bw}" height="${extraH}" rx="3" fill="#f4a126"/>`:''}</g>`}).join('');
let pts=(arr)=>arr.map((r,i)=>`${x(i)},${y(r.balance)}`).join(' '),labels=live.map((r,i)=>`<text x="${x(i)}" y="${g.labelY}" text-anchor="middle" fill="#73819a" font-size="8.5">${ml(r.date)}</text>`).join('');
return`<svg viewBox="0 0 ${g.w} ${g.height}" style="width:${g.w}px" preserveAspectRatio="none"><line x1="${g.left-12}" y1="${g.balBottom}" x2="${g.w-g.right}" y2="${g.balBottom}" stroke="#dfe5ec"/><line x1="${g.left-12}" y1="${g.payTop-8}" x2="${g.w-g.right}" y2="${g.payTop-8}" stroke="#e9edf2" stroke-dasharray="4 5"/><text x="${g.left-10}" y="14" fill="#8b97a9" font-size="8">SALDO</text><text x="${g.left-10}" y="${g.payTop-13}" fill="#8b97a9" font-size="8">RATA / MIESIĄC</text><polyline points="${pts(baseline)}" fill="none" stroke="#9aa5b5" stroke-width="3" stroke-dasharray="3 5" stroke-linecap="round" stroke-linejoin="round"/>${live.length?`<polyline points="${pts(live)}" fill="none" stroke="#3976dc" stroke-width="4" stroke-linecap="round" stroke-linejoin="round"/>`:''}${plan.length?`<polyline points="${pts(plan)}" fill="none" stroke="#df5963" stroke-width="4" stroke-dasharray="8 6" stroke-linecap="round" stroke-linejoin="round"/>`:''}${bars}${labels}</svg>`}
function enhance(){let cards=[...document.querySelectorAll('#loanList .loan')];cards.forEach((card,i)=>{let l=S.loans[i],box=card.querySelector('.loanUnifiedChart');if(!l||!box)return;box.innerHTML=chart(l);let head=card.querySelector('.loanChartHead small');if(head)head.textContent='szara linia = stały scenariusz bez nadpłat • niebieska = rzeczywisty przebieg + zwykłe raty • czerwona = plan dalszych nadpłat';let legend=box.nextElementSibling;if(legend&&legend.classList.contains('legend'))legend.innerHTML='<span><i class="baselineLegend"></i> bez nadpłat</span><span><i class="liveLegend"></i> rzeczywisty / po wpłatach</span><span><i class="lineDash"></i> z planem nadpłat</span><span><i class="unpaidLegend"></i> rata do zapłaty</span><span><i class="paidLegend"></i> wpłacone</span><span><i class="monthlyExtraLegend"></i> nadpłata</span>';let progress=card.querySelector('.loanProgress');if(progress&&!card.querySelector('.debtComposition'))progress.insertAdjacentHTML('afterend',composition(l))})}
window.loans=function(){prevLoans();enhance()};
})();