/* Moje Finanse 1.9 — spójny kapitał, odsetki do końca, zwijanie kart i markery końca kredytów */
(function(){
const prevLoans=window.loans;
const DAY=86400000;
const $=id=>document.getElementById(id), n=v=>+v||0, money=v=>F(n(v));
function parseDate(s){return new Date((s||TODAY)+'T12:00:00')}
function ym(d){return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')}
function ml(d){return String(d.getMonth()+1).padStart(2,'0')+'.'+String(d.getFullYear()).slice(-2)}
function days(a,b){return Math.max(0,Math.round((b-a)/DAY))}
function due(y,m,day){let last=new Date(y,m+1,0).getDate();return new Date(y,m,Math.min(day,last),12)}
function firstDue(l){let b=parseDate(l.asOfDate),day=Math.max(1,Math.min(31,n(l.dueDay)||b.getDate())),d=due(b.getFullYear(),b.getMonth(),day);if(d<=b)d=due(b.getFullYear(),b.getMonth()+1,day);return d}
function annuity(balance,rate,months){if(months<=0)return balance;let r=rate/1200;if(!r)return balance/months;return balance*r/(1-Math.pow(1+r,-months))}
function term(l,b){if(n(l.months)>0)return Math.max(1,n(l.months));if(l.loanType==='zero')return Math.max(1,Math.ceil(b/Math.max(1,n(l.payment))));let r=n(l.rate)/1200,p=n(l.payment),m=0;if(p<=b*r)return 600;while(b>.01&&m<600){b=Math.max(0,b-(p-b*r));m++}return Math.max(1,m)}
function apply(balance,l,last,date,regular,extra){let dd=days(last,date),interest=l.loanType==='zero'?0:balance*(n(l.rate)/100)/365*dd,reg=Math.max(0,n(regular)),toInt=Math.min(reg,interest),principal=Math.max(0,reg-toInt),unpaid=Math.max(0,interest-toInt),over=Math.max(0,n(extra));return{interest,principal,extra:over,balance:Math.max(0,balance-principal-over+unpaid),payment:reg+over,days:dd}}
function live(l,withPlan){let balance=n(l.balance),base=parseDate(l.asOfDate),last=base,rows=[],rem=term(l,balance),hist=[...(l.history||[])].sort((a,b)=>(a.paymentDate||a.month).localeCompare(b.paymentDate||b.month));for(const h of hist){let d=parseDate(h.paymentDate||h.month+'-'+String(l.dueDay||1).padStart(2,'0'));if(d<base)continue;let regular=h.paid?n(h.regularPaid):0,extra=h.isOverpayment?n(h.extra):0,res=apply(balance,l,last,d,regular,extra);if(h.balanceAfter!=null)res.balance=Math.max(0,n(h.balanceAfter));balance=res.balance;last=d;rem=Math.max(0,rem-1);rows.push({date:d,month:h.month||ym(d),balance,regular,extra,interest:res.interest,principal:res.principal,payment:regular+extra,kind:'actual'})}
let d=firstDue(l);while(d<=last)d=due(d.getFullYear(),d.getMonth()+1,l.dueDay||1);let regular=n(l.payment),guard=0,one=false;while(balance>.01&&guard<600){if(l.overpayMode==='reduce_payment'&&rem>0)regular=annuity(balance,n(l.rate),rem);let accrued=l.loanType==='zero'?0:balance*(n(l.rate)/100)/365*days(last,d),planned=Math.min(balance+accrued,regular||n(l.payment)),extra=withPlan?n(l.extraMonthly):0;if(withPlan&&!one&&n(l.oneOff)>0){extra+=n(l.oneOff);one=true}let res=apply(balance,l,last,d,planned,extra);balance=res.balance;rows.push({date:new Date(d),month:ym(d),balance,regular:planned,extra,interest:res.interest,principal:res.principal,payment:planned+extra,kind:'forecast'});last=new Date(d);rem=Math.max(0,rem-1);d=due(d.getFullYear(),d.getMonth()+1,l.dueDay||1);guard++;if(l.overpayMode==='reduce_payment'&&rem<=0&&balance>.01)rem=1}return rows}
function baseline(l){let clone={...l,history:[],extraMonthly:0,oneOff:0,overpayMode:'shorten'};return live(clone,false)}
function stats(l){let rows=live(l,false),actual=rows.filter(r=>r.kind==='actual'),future=rows.filter(r=>r.kind==='forecast'),regularPaid=actual.reduce((s,r)=>s+n(r.regular),0),extra=actual.reduce((s,r)=>s+n(r.extra),0),interestPaid=actual.reduce((s,r)=>s+n(r.interest),0),remaining=actual.length?n(actual.at(-1).balance):n(l.balance),orig=Math.max(n(l.originalBalance),n(l.balance),1),capitalReduced=Math.max(0,orig-remaining),extraCapital=Math.min(extra,capitalReduced),regularPrincipal=Math.max(0,capitalReduced-extraCapital),interestLeft=l.loanType==='zero'?0:future.reduce((s,r)=>s+n(r.interest),0),interestPlanLeft=l.loanType==='zero'?0:live(l,true).filter(r=>r.kind==='forecast').reduce((s,r)=>s+n(r.interest),0);return{rows,actual,future,regularPaid,extra,interestPaid,remaining,orig,regularPrincipal,extraCapital,interestLeft,interestPlanLeft}}
function fixKpis(card,l){let s=stats(l),k=card.querySelector('.loanKpis');if(!k)return;k.innerHTML=`<div class="loanKpi"><small>AKTUALNE SALDO</small><b>${money(s.remaining)}</b><span>kapitał do spłaty</span></div><div class="loanKpi"><small>WPŁACONO RATY</small><b>${money(s.regularPaid)}</b><span>kapitał z rat ${money(s.regularPrincipal)}</span></div><div class="loanKpi"><small>NADPŁACONO</small><b class="green">${money(s.extra)}</b><span>kapitał nadpłat ${money(s.extraCapital)}</span></div><div class="loanKpi"><small>ODSETKI ZAPŁACONE</small><b>${money(s.interestPaid)}</b><span>${n(l.rate).toFixed(2)}% rocznie</span></div><div class="loanKpi interestFuture"><small>ODSETKI DO KOŃCA</small><b>${money(s.interestLeft)}</b><span>${l.loanType==='zero'?'raty 0% — brak odsetek':`z planem nadpłat: ${money(s.interestPlanLeft)}`}</span></div>`}
function fixComposition(card,l){let s=stats(l),box=card.querySelector('.debtComposition');if(!box)return;let base=s.orig,paidPct=Math.min(100,s.regularPrincipal/base*100),extraPct=Math.min(100,s.extraCapital/base*100),remainPct=Math.max(0,100-paidPct-extraPct);box.innerHTML=`<div class="debtCompHead"><b>Kapitał kredytu</b><span>${money(base)}</span></div><div class="debtCompBar"><i class="dcPaid" style="width:${paidPct}%"></i><i class="dcExtra" style="width:${extraPct}%"></i><i class="dcRemain" style="width:${remainPct}%"></i></div><div class="debtCompLegend"><span><i class="dcDot paid"></i>spłacony ratami <b>${money(s.regularPrincipal)}</b></span><span><i class="dcDot extra"></i>nadpłacony <b>${money(s.extraCapital)}</b></span><span><i class="dcDot remain"></i>pozostało <b>${money(s.remaining)}</b></span></div><div class="capitalEquation">${money(s.regularPrincipal)} + ${money(s.extraCapital)} + ${money(s.remaining)} = <b>${money(base)}</b></div>`}
function collapsible(card,l,i){let title=card.querySelector('.loanTitle');if(!title)return;let actions=title.querySelector('.loanTitleActions');if(!actions){let del=title.querySelector('.danger');actions=document.createElement('div');actions.className='loanTitleActions';let tog=document.createElement('button');tog.className='btn collapseBtn';tog.type='button';tog.onclick=()=>window.toggleLoanCard19(i);actions.appendChild(tog);if(del)actions.appendChild(del);title.appendChild(actions)}let btn=actions.querySelector('.collapseBtn');btn.textContent=l.uiCollapsed?'Rozwiń ▾':'Zwiń ▴';card.classList.toggle('loanCollapsed',!!l.uiCollapsed);let compact=card.querySelector('.loanCollapsedSummary');if(!compact){compact=document.createElement('div');compact.className='loanCollapsedSummary';title.insertAdjacentElement('afterend',compact)}let s=stats(l),end=live(l,true).at(-1)?.date;compact.innerHTML=`<span>saldo <b>${money(s.remaining)}</b></span><span>rata <b>${money(l.payment)}</b></span><span>odsetki do końca <b>${money(s.interestLeft)}</b></span><span>spłata <b>${end?end.toLocaleDateString('pl-PL',{month:'2-digit',year:'numeric'}):'—'}</b></span>`}
window.toggleLoanCard19=function(i){let l=S.loans[i];if(!l)return;l.uiCollapsed=!l.uiCollapsed;save();render()}
function overview19(){let host=$('loanList'),box=$('loanOverview');if(!host||!box||!S.loans.length)return;let items=S.loans.map(l=>({l,rows:live(l,true)})),start=new Date(Math.min(...S.loans.map(l=>parseDate(l.asOfDate).getTime()))),end=new Date(Math.max(...items.map(x=>(x.rows.at(-1)?.date||start).getTime()))),count=Math.max(1,(end.getFullYear()-start.getFullYear())*12+end.getMonth()-start.getMonth()+1),step=count<=18?46:count<=36?38:count<=72?32:28,w=Math.max(760,90+(count-1)*step+70),left=52,baseY=210,top=32,data=[];
for(let i=0;i<count;i++){let d=due(start.getFullYear(),start.getMonth()+i,1),bal=0,pay=0;items.forEach(({l,rows})=>{let r=rows.find(z=>z.date.getFullYear()===d.getFullYear()&&z.date.getMonth()===d.getMonth());let prev=rows.filter(z=>z.date<=d).at(-1);if(!prev){bal+=n(l.balance)}else bal+=n(prev.balance);if(r)pay+=n(r.payment)});data.push({d,bal,pay})}
let maxBal=Math.max(1,...data.map(r=>r.bal)),maxPay=Math.max(1,...data.map(r=>r.pay)),x=i=>left+i*step,yBal=v=>top+(1-v/maxBal)*115,payH=v=>Math.max(2,v/maxPay*46),bw=Math.max(12,Math.min(22,step*.45)),bars=data.map((r,i)=>`<rect x="${x(i)-bw/2}" y="${baseY-payH(r.pay)}" width="${bw}" height="${payH(r.pay)}" rx="3" fill="#cfe2fb"/>`).join(''),line=data.map((r,i)=>`${x(i)},${yBal(r.bal)}`).join(' '),labels=data.map((r,i)=>`<text x="${x(i)}" y="238" text-anchor="middle" fill="#73819a" font-size="8">${ml(r.d)}</text>`).join(''),markers=items.map((it,j)=>{let d=it.rows.at(-1)?.date||end,idx=Math.max(0,Math.min(count-1,(d.getFullYear()-start.getFullYear())*12+d.getMonth()-start.getMonth())),xx=x(idx),yy=17+(j%5)*13;return`<line x1="${xx}" y1="25" x2="${xx}" y2="${baseY}" stroke="#38b96a" stroke-width="1.4" stroke-dasharray="4 4"/><text x="${xx+4}" y="${yy}" fill="#238849" font-size="9">${esc(it.l.name)} • ${ml(d)}</text>`}).join('');
let chart=box.querySelector('.overviewChart');if(chart)chart.innerHTML=`<svg viewBox="0 0 ${w} 248" style="width:${w}px" preserveAspectRatio="none"><line x1="40" y1="147" x2="${w-20}" y2="147" stroke="#dfe5ec"/><line x1="40" y1="${baseY}" x2="${w-20}" y2="${baseY}" stroke="#dfe5ec"/>${bars}<polyline points="${line}" fill="none" stroke="#3976dc" stroke-width="4" stroke-linecap="round" stroke-linejoin="round"/>${markers}${labels}</svg>`;let head=box.querySelector('.loanChartHead small');if(head)head.textContent='linia = łączne saldo • słupki = suma rat • zielone pionowe linie = miesiąc zakończenia konkretnego kredytu';let leg=chart?.nextElementSibling;if(leg&&leg.classList.contains('legend'))leg.innerHTML='<span><i class="lineSolid"></i> łączne saldo</span><span><i class="unpaidLegend"></i> raty miesiąca</span><span class="green">--- zakończenie kredytu</span>'}
function enhance19(){let cards=[...document.querySelectorAll('#loanList .loan')];cards.forEach((card,i)=>{let l=S.loans[i];if(!l)return;fixKpis(card,l);fixComposition(card,l);collapsible(card,l,i)});overview19()}
window.loans=function(){prevLoans();enhance19()};
})();