/* Moje Finanse 2.0 — moduły życia finansowego */
(function(){
const G=id=>document.getElementById(id), num=v=>+v||0, PLN=v=>F(num(v));
const MONTHS_FULL=['Styczeń','Luty','Marzec','Kwiecień','Maj','Czerwiec','Lipiec','Sierpień','Wrzesień','Październik','Listopad','Grudzień'];
const ymNow=()=>TODAY.slice(0,7);
const monthKey=(y,m)=>`${y}-${String(m+1).padStart(2,'0')}`;
function ensure20(){
  S.finance ||= {};
  S.finance.expenses ||= [];
  S.finance.assets ||= [];
  S.finance.goals ||= [];
  S.finance.ppkOpening = num(S.finance.ppkOpening);
  S.finance.selectedMonth ||= ymNow();
  Object.values(S.years||{}).forEach(y=>{(y.company||[]).forEach(r=>{r.zus=num(r.zus);r.health=num(r.health);r.tax=num(r.tax);r.vatOut=num(r.vatOut);r.vatIn=num(r.vatIn);});});
  save();
}
function currentLoanBalance(l){try{return num(loanPoint(l).balance)}catch{return num(l.balance)}}
function loanHistoryFor(l,key){return (l.history||[]).find(h=>(h.month||'')===key)}
function regularPaid(h,l){if(!h)return 0;if(typeof h.paid==='boolean')return h.paid?num(h.regularPaid||l.payment):0;return num(h.regularPaid!=null?h.regularPaid:h.paid)}
function extraPaid(h){return h&&h.isOverpayment===false?0:num(h?.extra)}
function monthLoanSpend(key){return S.loans.reduce((sum,l)=>{let h=loanHistoryFor(l,key);if(h)return sum+regularPaid(h,l)+extraPaid(h);let d=key+'-01',base=(l.asOfDate||TODAY).slice(0,7);if(key<base)return sum;return sum+num(l.payment)+num(l.extraMonthly)},0)}
function recurringExpenses(key){return S.finance.expenses.filter(e=>e.active!==false&&(!e.from||key>=e.from)&&(!e.to||key<=e.to)).reduce((a,e)=>a+num(e.amount),0)}
function yearActualExpenses(y){let total=0;for(let m=0;m<12;m++)total+=recurringExpenses(monthKey(y,m));return total}
function salaryMonth(y,m){let old=S.selectedYear;S.selectedYear=y;Y();let r=sal().rows[m];S.selectedYear=old;Y();return r||{net:0,g:0,pe:0,er:0,total:0}}
function companyRaw(y,m){let yr=S.years[String(y)]||blank(),r=yr.company?.[m]||{};return r}
function companyMonth(y,m){let r=companyRaw(y,m),rev=num(r.revenue),cost=num(r.costs),zus=num(r.zus),health=num(r.health),tax=num(r.tax),vatNet=(num(r.vatOut)||num(r.vatIn))?num(r.vatOut)-num(r.vatIn):num(r.vat);return{rev,cost,zus,health,tax,vat:vatNet,profit:rev-cost-zus-health-tax-vatNet}}
function ppkTotalThrough(y,m=11){let total=num(S.finance.ppkOpening);Object.keys(S.years).sort().forEach(yy=>{let year=+yy;if(year>y)return;let old=S.selectedYear;S.selectedYear=year;Y();let rows=sal().rows;S.selectedYear=old;Y();rows.forEach((r,i)=>{if(year<y||i<=m)total+=num(r.pe)+num(r.er)})});return total}
function wealthTotal(){let assets=S.finance.assets.reduce((a,x)=>a+num(x.value),0),ppk=ppkTotalThrough(CY,new Date().getMonth()),debt=S.loans.reduce((a,l)=>a+currentLoanBalance(l),0);return{assets,ppk,debt,net:assets+ppk-debt}}
function dashboardMonth(key){let [y,mm]=key.split('-').map(Number),m=mm-1,s=salaryMonth(y,m),c=companyMonth(y,m),expenses=recurringExpenses(key),loans=monthLoanSpend(key),income=num(s.total)+Math.max(0,c.profit),free=income-expenses-loans;return{y,m,s,c,expenses,loans,income,free}}
function injectHome(){let home=G('home');if(!home||G('lifeHome'))return;let target=home.querySelector('.hero');target.insertAdjacentHTML('afterend',`<div id="lifeHome" class="lifeGrid"><button class="lifeTile" onclick="show('monthly')"><small>PULPIT MIESIĄCA</small><b id="lifeFree">0 zł</b><span id="lifeFreeSub">wolna gotówka</span></button><button class="lifeTile" onclick="show('budget')"><small>WYDATKI STAŁE</small><b id="lifeExpenses">0 zł</b><span>miesięcznie</span></button><button class="lifeTile" onclick="show('wealth')"><small>WARTOŚĆ NETTO</small><b id="lifeNetWorth">0 zł</b><span>aktywa + PPK − kredyty</span></button><button class="lifeTile" onclick="show('goals')"><small>CELE</small><b id="lifeGoals">0</b><span>aktywnych</span></button></div>`)}
function renderHome20(){injectHome();let key=ymNow(),d=dashboardMonth(key),w=wealthTotal();if(G('lifeFree')){G('lifeFree').textContent=PLN(d.free);G('lifeFree').classList.toggle('negative',d.free<0);G('lifeExpenses').textContent=PLN(d.expenses);G('lifeNetWorth').textContent=PLN(w.net);G('lifeGoals').textContent=S.finance.goals.length}}
function renderMonthly(){let host=G('monthlyBody');if(!host)return;let key=S.finance.selectedMonth||ymNow(),d=dashboardMonth(key),ppkEmp=num(d.s.pe),ppkEr=num(d.s.er);host.innerHTML=`<div class="card monthHero"><div class="monthPick"><button class="btn" onclick="shiftFinanceMonth(-1)">‹</button><input id="financeMonth" type="month" value="${key}" onchange="setFinanceMonth(this.value)"><button class="btn" onclick="shiftFinanceMonth(1)">›</button></div><small>WOLNA GOTÓWKA W MIESIĄCU</small><h2 class="${d.free<0?'red':'green'}">${PLN(d.free)}</h2><span>dochody ${PLN(d.income)} − wydatki ${PLN(d.expenses)} − kredyty ${PLN(d.loans)}</span></div><div class="monthKpis"><div><small>ETAT NETTO</small><b>${PLN(d.s.total)}</b><span>brutto ~ ${PLN(d.s.g)}</span></div><div><small>FIRMA — GOTÓWKA</small><b>${PLN(d.c.profit)}</b><span>przychód ${PLN(d.c.rev)}</span></div><div><small>RATY + NADPŁATY</small><b>${PLN(d.loans)}</b></div><div><small>WYDATKI STAŁE</small><b>${PLN(d.expenses)}</b></div><div><small>PPK PRACOWNIK</small><b>${PLN(ppkEmp)}</b></div><div><small>PPK PRACODAWCA</small><b class="green">+ ${PLN(ppkEr)}</b></div></div>${monthFlowChart(d)}${alerts20(key)}`}
function monthFlowChart(d){let vals=[['Etat',num(d.s.total)],['Firma',Math.max(0,d.c.profit)],['Wydatki',d.expenses],['Kredyty',d.loans],['Zostaje',Math.max(0,d.free)]],mx=Math.max(1,...vals.map(x=>x[1]));return `<div class="card"><div class="title">Przepływ miesiąca <span class="pill">dochody → obciążenia → wolna gotówka</span></div><div class="flowBars">${vals.map(([n,v])=>`<div><span>${n}</span><i><b style="width:${v/mx*100}%"></b></i><strong>${PLN(v)}</strong></div>`).join('')}</div></div>`}
function alerts20(key){let [y,m]=key.split('-').map(Number),now=new Date(TODAY+'T12:00:00'),items=[];S.loans.forEach(l=>{let day=Math.max(1,Math.min(31,num(l.dueDay)||1)),due=new Date(y,m-1,day,12),diff=Math.ceil((due-now)/86400000);if(key===ymNow()&&diff>=0&&diff<=7&&!loanHistoryFor(l,key))items.push(`Rata „${esc(l.name)}” za ${diff===0?'dzisiaj':diff+' dni'} — ${PLN(l.payment)}`)});let threshold=num(S.settings.threshold)||120000;try{let old=S.selectedYear;S.selectedYear=y;Y();let rows=sal().rows,cum=num(rows[m]?.y);S.selectedYear=old;Y();if(cum>threshold*.9&&cum<threshold)items.push(`Zbliżasz się do progu PIT: ${PLN(cum)} / ${PLN(threshold)}`);if(cum>=threshold)items.push(`Próg PIT został przekroczony: ${PLN(cum)}`)}catch{}return `<div class="card"><div class="title">Alerty</div>${items.length?items.map(x=>`<div class="alertRow">⚠️ <span>${x}</span></div>`).join(''):'<p class="muted">Brak pilnych alertów dla tego miesiąca.</p>'}</div>`}
function renderBudget(){let host=G('budgetBody');if(!host)return;let total=recurringExpenses(ymNow());host.innerHTML=`<div class="grid"><div class="tile"><small>STAŁE / MIES.</small><b>${PLN(total)}</b></div><div class="tile"><small>STAŁE / ROK</small><b>${PLN(total*12)}</b></div></div><div class="card"><div class="title">Wydatki stałe <button class="btn primary" onclick="expenseModal20()">＋ Dodaj</button></div>${S.finance.expenses.length?S.finance.expenses.map((e,i)=>`<div class="budgetRow"><div><b>${esc(e.name)}</b><small>${esc(e.category||'Inne')} • dzień ${e.day||'—'}${e.from?' • od '+e.from:''}${e.to?' • do '+e.to:''}</small></div><b>${PLN(e.amount)}/m</b><button class="btn danger" onclick="removeExpense20(${i})">Usuń</button></div>`).join(''):'<p class="muted">Dodaj czynsz, telefon, paliwo, subskrypcje, jedzenie i inne powtarzalne koszty.</p>'}</div>`}
function renderWealth(){let host=G('wealthBody');if(!host)return,w=wealthTotal();host.innerHTML=`<div class="wealthHero"><small>WARTOŚĆ NETTO</small><h2>${PLN(w.net)}</h2><span>aktywa ${PLN(w.assets)} + PPK ${PLN(w.ppk)} − kredyty ${PLN(w.debt)}</span></div><div class="grid"><div class="tile"><small>AKTYWA</small><b>${PLN(w.assets)}</b></div><div class="tile"><small>PPK</small><b>${PLN(w.ppk)}</b></div><div class="tile"><small>ZADŁUŻENIE</small><b>${PLN(w.debt)}</b></div></div><div class="card"><div class="title">Majątek <button class="btn primary" onclick="assetModal20()">＋ Dodaj aktywo</button></div>${S.finance.assets.length?S.finance.assets.map((a,i)=>`<div class="budgetRow"><div><b>${esc(a.name)}</b><small>${esc(a.type||'Inne')}</small></div><b>${PLN(a.value)}</b><button class="btn danger" onclick="removeAsset20(${i})">Usuń</button></div>`).join(''):'<p class="muted">Dodaj gotówkę, konto oszczędnościowe, inwestycje, auto lub inne składniki majątku.</p>'}</div><div class="card"><div class="title">PPK</div><div class="form"><label>Saldo początkowe PPK<input id="ppkOpening20" type="number" value="${num(S.finance.ppkOpening)}"></label></div><button class="btn primary" onclick="savePpk20()">Zapisz</button><p class="muted">Do salda początkowego aplikacja dodaje obliczone wpłaty pracownika i pracodawcy z wpisanych wypłat.</p></div>`}
function renderGoals(){let host=G('goalsBody');if(!host)return;host.innerHTML=`<div class="card"><div class="title">Cele finansowe <button class="btn primary" onclick="goalModal20()">＋ Dodaj cel</button></div>${S.finance.goals.length?S.finance.goals.map((g,i)=>{let p=Math.min(100,num(g.current)/Math.max(1,num(g.target))*100),remain=Math.max(0,num(g.target)-num(g.current)),months=num(g.monthly)>0?Math.ceil(remain/num(g.monthly)):null;return`<div class="goalCard"><div class="goalTop"><div><b>${esc(g.name)}</b><small>${g.due?'cel do '+g.due:''}</small></div><strong>${p.toFixed(0)}%</strong></div><div class="progress"><i style="width:${p}%"></i></div><div class="goalStats"><span>${PLN(g.current)} / ${PLN(g.target)}</span><span>brakuje ${PLN(remain)}</span><span>${months!=null?'~ '+months+' mies. przy '+PLN(g.monthly)+'/m':''}</span></div><button class="btn" onclick="updateGoal20(${i})">Aktualizuj</button> <button class="btn danger" onclick="removeGoal20(${i})">Usuń</button></div>`}).join(''):'<p class="muted">Np. poduszka finansowa, samochód, sprzęt do firmy albo konkretny poziom oszczędności.</p>'}</div>`}
function renderBusinessPlus(){let host=G('businessPlusBody');if(!host)return;let y=S.selectedYear,rows=(S.years[String(y)]||Y()).company;host.innerHTML=`<div class="sectionHead"><div class="yearNav"><button class="btn" onclick="changeYear(-1)">‹</button><b>${y}</b><button class="btn" onclick="changeYear(1)">›</button></div></div><div class="card"><div class="title">Firma+ — realna gotówka miesiąc po miesiącu</div><div class="businessGrid">${rows.map((r,i)=>{let c=companyMonth(y,i);return`<div class="bizMonth"><b>${MONTHS_FULL[i]}</b><label>Przychód netto<input type="number" id="bpr${i}" value="${r.revenue??''}"></label><label>Koszty netto<input type="number" id="bco${i}" value="${r.costs??''}"></label><label>VAT należny<input type="number" id="bvo${i}" value="${r.vatOut||''}"></label><label>VAT naliczony<input type="number" id="bvi${i}" value="${r.vatIn||''}"></label><label>ZUS społeczne<input type="number" id="bzu${i}" value="${r.zus||''}"></label><label>Składka zdrowotna<input type="number" id="bhe${i}" value="${r.health||''}"></label><label>Podatek dochodowy<input type="number" id="bta${i}" value="${r.tax||''}"></label><div class="bizResult"><small>REALNIE ZOSTAJE</small><b class="${c.profit<0?'red':'green'}">${PLN(c.profit)}</b></div><button class="btn primary" onclick="saveBusinessMonth20(${i})">Zapisz ${M[i]}</button></div>`}).join('')}</div></div>`}
window.expenseModal20=function(){open(`<h2>Dodaj wydatek stały</h2><div class="form"><label>Nazwa<input id="e20n"></label><label>Kategoria<select id="e20c"><option>Mieszkanie</option><option>Jedzenie</option><option>Transport</option><option>Telefon / Internet</option><option>Subskrypcje</option><option>Ubezpieczenia</option><option>Inne</option></select></label><label>Kwota / miesiąc<input id="e20a" type="number"></label><label>Dzień płatności<input id="e20d" type="number" min="1" max="31"></label><label>Od miesiąca<input id="e20f" type="month"></label><label>Do miesiąca (opcjonalnie)<input id="e20t" type="month"></label></div><div class="actions"><button class="btn" onclick="closeModal()">Anuluj</button><button class="btn primary" onclick="addExpense20()">Dodaj</button></div>`)};
window.addExpense20=function(){S.finance.expenses.push({name:G('e20n').value||'Wydatek',category:G('e20c').value,amount:num(G('e20a').value),day:num(G('e20d').value),from:G('e20f').value,to:G('e20t').value,active:true});save();closeModal();render()};
window.removeExpense20=i=>{S.finance.expenses.splice(i,1);save();render()};
window.assetModal20=function(){open(`<h2>Dodaj składnik majątku</h2><div class="form"><label>Nazwa<input id="a20n"></label><label>Typ<select id="a20t"><option>Gotówka</option><option>Konto</option><option>Oszczędności</option><option>Inwestycje</option><option>Auto</option><option>Nieruchomość</option><option>Inne</option></select></label><label>Aktualna wartość<input id="a20v" type="number"></label></div><div class="actions"><button class="btn" onclick="closeModal()">Anuluj</button><button class="btn primary" onclick="addAsset20()">Dodaj</button></div>`)};
window.addAsset20=function(){S.finance.assets.push({name:G('a20n').value||'Aktywo',type:G('a20t').value,value:num(G('a20v').value)});save();closeModal();render()};window.removeAsset20=i=>{S.finance.assets.splice(i,1);save();render()};
window.goalModal20=function(){open(`<h2>Dodaj cel</h2><div class="form"><label>Nazwa<input id="g20n"></label><label>Kwota celu<input id="g20t" type="number"></label><label>Mam już<input id="g20c" type="number"></label><label>Chcę odkładać / mies.<input id="g20m" type="number"></label><label>Termin (opcjonalnie)<input id="g20d" type="month"></label></div><div class="actions"><button class="btn" onclick="closeModal()">Anuluj</button><button class="btn primary" onclick="addGoal20()">Dodaj</button></div>`)};
window.addGoal20=function(){S.finance.goals.push({name:G('g20n').value||'Cel',target:num(G('g20t').value),current:num(G('g20c').value),monthly:num(G('g20m').value),due:G('g20d').value});save();closeModal();render()};window.removeGoal20=i=>{S.finance.goals.splice(i,1);save();render()};window.updateGoal20=function(i){let g=S.finance.goals[i];open(`<h2>${esc(g.name)}</h2><label>Aktualnie odłożone<input id="g20u" type="number" value="${num(g.current)}"></label><div class="actions"><button class="btn" onclick="closeModal()">Anuluj</button><button class="btn primary" onclick="saveGoal20(${i})">Zapisz</button></div>`)};window.saveGoal20=i=>{S.finance.goals[i].current=num(G('g20u').value);save();closeModal();render()};
window.savePpk20=function(){S.finance.ppkOpening=num(G('ppkOpening20').value);save();render()};
window.setFinanceMonth=function(v){if(v){S.finance.selectedMonth=v;save();render()}};window.shiftFinanceMonth=function(delta){let [y,m]=S.finance.selectedMonth.split('-').map(Number),d=new Date(y,m-1+delta,1,12);S.finance.selectedMonth=monthKey(d.getFullYear(),d.getMonth());save();render()};
window.saveBusinessMonth20=function(i){let r=Y().company[i];r.revenue=num(G('bpr'+i).value);r.costs=num(G('bco'+i).value);r.vatOut=num(G('bvo'+i).value);r.vatIn=num(G('bvi'+i).value);r.vat=r.vatOut-r.vatIn;r.zus=num(G('bzu'+i).value);r.health=num(G('bhe'+i).value);r.tax=num(G('bta'+i).value);save();render()};
function render20(){ensure20();renderHome20();renderMonthly();renderBudget();renderWealth();renderGoals();renderBusinessPlus()}
const oldRender=window.render;window.render=function(){oldRender();render20()};
ensure20();setTimeout(()=>{render20()},0);
})();