/* Moje Finanse 2.2 — głębsza analityka istniejących modułów */
(function(){
const G=id=>document.getElementById(id),num=v=>+v||0,PLN=v=>F(num(v));
const FULL=['Styczeń','Luty','Marzec','Kwiecień','Maj','Czerwiec','Lipiec','Sierpień','Wrzesień','Październik','Listopad','Grudzień'];
function ensure(){S.finance||={};S.finance.calendarEvents||=[];S.finance.scenario||={salaryPct:0,companyPct:0,expensePct:0,extraDebt:0};S.finance.emergencySavings=num(S.finance.emergencySavings);S.finance.emergencyTargetMonths=num(S.finance.emergencyTargetMonths)||6;S.finance.analysisMonth||=S.finance.selectedMonth||TODAY.slice(0,7);S.finance.categoryLimits||={};S.finance.budgetActual||={};S.finance.ppkReturnPct=num(S.finance.ppkReturnPct)||5;save()}
function key(y,m){return `${y}-${String(m+1).padStart(2,'0')}`}
function parseKey(k){let [y,m]=k.split('-').map(Number);return{y,m:m-1}}
function addMonths(k,d){let {y,m}=parseKey(k),x=new Date(y,m+d,1,12);return key(x.getFullYear(),x.getMonth())}
function salaryData(y,m){let old=S.selectedYear;S.selectedYear=y;Y();let r=sal().rows[m]||{};S.selectedYear=old;Y();return{net:num(r.total),gross:num(r.g),ppkEmp:num(r.pe),ppkEr:num(r.er),actual:!!r.actual}}
function companyData(y,m){let r=(S.years[String(y)]||blank()).company?.[m]||{},rev=num(r.revenue),cost=num(r.costs),zus=num(r.zus),health=num(r.health),tax=num(r.tax),vat=(num(r.vatOut)||num(r.vatIn))?num(r.vatOut)-num(r.vatIn):num(r.vat);return{revenue:rev,costs:cost,zus,health,tax,vat,profit:rev-cost-zus-health-tax-vat,actual:!!(rev||cost||zus||health||tax||vat)}}
function expenseRows(k){return (S.finance.expenses||[]).filter(e=>e.active!==false&&(!e.from||k>=e.from)&&(!e.to||k<=e.to))}
function expenseFor(k){return expenseRows(k).reduce((a,e)=>a+num(e.amount),0)}
function histForLoan(l,k){return (l.history||[]).find(h=>(h.month||'')===k)}
function loanSpend(k){return S.loans.reduce((a,l)=>{let h=histForLoan(l,k);if(h){let regular=typeof h.paid==='boolean'?(h.paid?num(h.regularPaid||l.payment):0):num(h.regularPaid!=null?h.regularPaid:h.paid),extra=h.isOverpayment===false?0:num(h.extra);return a+regular+extra}if(k<(l.asOfDate||TODAY).slice(0,7))return a;return a+num(l.payment)+num(l.extraMonthly)},0)}
function monthFlow(k){let {y,m}=parseKey(k),s=salaryData(y,m),c=companyData(y,m),e=expenseFor(k),lo=loanSpend(k),income=s.net+Math.max(0,c.profit);return{key:k,y,m,s,c,expenses:e,loans:lo,income,free:income-e-lo}}
function currentBalance(l){try{return num(loanPoint(l).balance)}catch{return num(l.balance)}}
function payoff(l,extra=0){let b=currentBalance(l),rate=(l.loanType==='zero'?0:num(l.rate))/1200,pay=num(l.payment)+num(extra),m=0,interest=0;if(pay<=0)return{m:600,interest:0};while(b>.01&&m<600){let it=b*rate;if(pay<=it+.001)return{m:600,interest};interest+=it;b=Math.max(0,b-(pay-it));m++}return{m,interest}}
function payoffDate(m){let d=new Date(TODAY+'T12:00:00');d.setMonth(d.getMonth()+m);return d.toLocaleDateString('pl-PL',{month:'2-digit',year:'numeric'})}
function renderCalendar(){let host=G('calendarBody');if(!host)return;let k=S.finance.analysisMonth||TODAY.slice(0,7),{y,m}=parseKey(k),days=new Date(y,m+1,0).getDate(),offset=(new Date(y,m,1).getDay()+6)%7,events={};let add=(d,label,kind,amount)=>{d=Math.max(1,Math.min(days,num(d)||1));(events[d]||=[]).push({label,kind,amount})};expenseRows(k).forEach(e=>add(e.day||1,e.name,'expense',e.amount));S.loans.forEach(l=>{if(k>=(l.asOfDate||TODAY).slice(0,7))add(l.dueDay||1,l.name,'loan',l.payment)});(S.finance.calendarEvents||[]).filter(e=>e.month===k).forEach(e=>add(e.day,e.name,'custom',e.amount));let cells='';for(let i=0;i<offset;i++)cells+='<div class="calDay empty"></div>';for(let d=1;d<=days;d++)cells+=`<div class="calDay"><b>${d}</b>${(events[d]||[]).map(e=>`<span class="calEvent ${e.kind}">${esc(e.label)}${num(e.amount)?' • '+PLN(e.amount):''}</span>`).join('')}</div>`;host.innerHTML=`<div class="card"><div class="calendarHead"><button class="btn" onclick="shiftAnalysisMonth(-1)">‹</button><b>${FULL[m]} ${y}</b><button class="btn" onclick="shiftAnalysisMonth(1)">›</button><button class="btn primary" onclick="calendarEventModal21()">＋ Wydarzenie</button></div><div class="calWeek"><span>Pn</span><span>Wt</span><span>Śr</span><span>Cz</span><span>Pt</span><span>So</span><span>Nd</span></div><div class="calendarGrid">${cells}</div></div>`}
function renderEmergency(){let host=G('emergencyBody');if(!host)return,d=monthFlow(S.finance.analysisMonth),monthly=Math.max(0,d.expenses+d.loans),target=monthly*num(S.finance.emergencyTargetMonths),saved=num(S.finance.emergencySavings),covered=monthly?saved/monthly:0,p=Math.min(100,target?saved/target*100:0);host.innerHTML=`<div class="wealthHero"><small>PODUSZKA FINANSOWA</small><h2>${covered.toFixed(1)} mies.</h2><span>${PLN(saved)} / ${PLN(target)}</span></div><div class="card"><div class="progress"><i style="width:${p}%"></i></div><div class="goalStats"><span>obciążenia ${PLN(monthly)}/m</span><span>cel ${num(S.finance.emergencyTargetMonths)} mies.</span><span>brakuje ${PLN(Math.max(0,target-saved))}</span></div><div class="form"><label>Oszczędności płynne<input id="emergencySavings21" type="number" value="${saved}"></label><label>Cel w miesiącach<input id="emergencyMonths21" type="number" value="${num(S.finance.emergencyTargetMonths)}"></label></div><button class="btn primary" onclick="saveEmergency21()">Zapisz</button></div>`}
function renderScenario(){let host=G('scenarioBody');if(!host)return,sc=S.finance.scenario||{},start=S.finance.analysisMonth,rows=[];for(let i=0;i<12;i++){let k=addMonths(start,i),d=monthFlow(k),alt=d.s.net*(1+num(sc.salaryPct)/100)+Math.max(0,d.c.profit)*(1+num(sc.companyPct)/100)-d.expenses*(1+num(sc.expensePct)/100)-d.loans-num(sc.extraDebt);rows.push({k,base:d.free,alt})}let base=rows.reduce((a,r)=>a+r.base,0),alt=rows.reduce((a,r)=>a+r.alt,0),mx=Math.max(1,...rows.flatMap(r=>[Math.abs(r.base),Math.abs(r.alt)]));host.innerHTML=`<div class="grid"><div class="tile"><small>BAZA — 12 MIES.</small><b>${PLN(base)}</b></div><div class="tile"><small>SCENARIUSZ</small><b>${PLN(alt)}</b></div><div class="tile"><small>RÓŻNICA</small><b class="${alt>=base?'green':'red'}">${PLN(alt-base)}</b></div></div><div class="card"><div class="form scenarioForm"><label>Zmiana etatu %<input id="scSalary21" type="number" value="${num(sc.salaryPct)}"></label><label>Zmiana firmy %<input id="scCompany21" type="number" value="${num(sc.companyPct)}"></label><label>Zmiana wydatków %<input id="scExpense21" type="number" value="${num(sc.expensePct)}"></label><label>Dodatkowa nadpłata / mies.<input id="scDebt21" type="number" value="${num(sc.extraDebt)}"></label></div><button class="btn primary" onclick="saveScenario21()">Przelicz</button></div><div class="card"><div class="scenarioBars">${rows.map(r=>`<div class="scenarioCol"><div class="scenarioStack"><i class="scenarioAlt" style="height:${Math.abs(r.alt)/mx*110}px"></i><i class="scenarioBase" style="height:${Math.abs(r.base)/mx*110}px"></i></div><small>${r.k.slice(5)}/${r.k.slice(2,4)}</small></div>`).join('')}</div></div>`}
function renderDebt(){let host=G('debtBody');if(!host)return,d=monthFlow(S.finance.analysisMonth),debt=S.loans.reduce((a,l)=>a+currentBalance(l),0),monthly=S.loans.reduce((a,l)=>a+num(l.payment)+num(l.extraMonthly),0),ratio=d.income?monthly/d.income*100:0,weighted=debt?S.loans.reduce((a,l)=>a+currentBalance(l)*num(l.rate),0)/debt:0,snow=[...S.loans].sort((a,b)=>currentBalance(a)-currentBalance(b)),aval=[...S.loans].sort((a,b)=>num(b.rate)-num(a.rate));host.innerHTML=`<div class="monthKpis"><div><small>ZADŁUŻENIE</small><b>${PLN(debt)}</b></div><div><small>RATY / DOCHÓD</small><b>${ratio.toFixed(1)}%</b></div><div><small>ŚR. OPROCENTOWANIE</small><b>${weighted.toFixed(2)}%</b></div></div><div class="card"><div class="two debtStrategies"><div><b>Snowball</b>${snow.map((l,i)=>`<div class="debtRank"><span>${i+1}. ${esc(l.name)}</span><b>${PLN(currentBalance(l))}</b></div>`).join('')}</div><div><b>Avalanche</b>${aval.map((l,i)=>`<div class="debtRank"><span>${i+1}. ${esc(l.name)}</span><b>${num(l.rate).toFixed(2)}%</b></div>`).join('')}</div></div></div>`}
function renderActions(){let host=G('actionBody');if(!host)return,k=S.finance.analysisMonth,d=monthFlow(k),items=[];S.loans.forEach(l=>{if(!histForLoan(l,k))items.push({day:num(l.dueDay)||1,text:`Rata ${esc(l.name)} — ${PLN(l.payment)}`})});expenseRows(k).forEach(e=>items.push({day:num(e.day)||1,text:`${esc(e.name)} — ${PLN(e.amount)}`}));items.sort((a,b)=>a.day-b.day);host.innerHTML=`<div class="card actionHero"><small>WOLNA GOTÓWKA PO PLANIE</small><h2>${PLN(d.free)}</h2></div><div class="card">${items.map(i=>`<div class="actionRow"><b>${String(i.day).padStart(2,'0')}</b><span>${i.text}</span></div>`).join('')||'<p class="muted">Brak zaplanowanych pozycji.</p>'}</div>`}
function salaryBreakdown(gross,net,ppkEmp,ppkEr){let pension=gross*.0976,disability=gross*.015,sickness=gross*.0245,social=pension+disability+sickness,health=Math.max(0,gross-social)*.09,pit=Math.max(0,gross-social-health-ppkEmp-net),employerPension=gross*.0976,employerDis=gross*.065,accident=gross*.0167,fp=gross*.0245,fgsp=gross*.001,employer=employerPension+employerDis+accident+fp+fgsp+ppkEr;return{pension,disability,sickness,social,health,pit,employerPension,employerDis,accident,fp,fgsp,employer,totalCost:gross+employer}}
function renderSalaryDeep(){let sec=G('salary');if(!sec)return;let box=G('salaryDeep22');if(!box){box=document.createElement('div');box.id='salaryDeep22';sec.appendChild(box)}let old=S.selectedYear;let y=S.selectedYear;Y();let rows=sal().rows;S.selectedYear=old;Y();let actual=rows.filter(r=>r.actual),g=actual.reduce((a,r)=>a+num(r.g),0),net=actual.reduce((a,r)=>a+num(r.total),0),emp=actual.reduce((a,r)=>a+num(r.pe),0),er=actual.reduce((a,r)=>a+num(r.er),0),last=actual.at(-1)||rows.find(r=>num(r.g)>0)||{},b=salaryBreakdown(num(last.g),num(last.total),num(last.pe),num(last.er)),opening=num(S.finance.ppkOpening),rate=num(S.finance.ppkReturnPct)/100/12,ppk=opening;rows.forEach(r=>{ppk=ppk*(1+rate)+num(r.pe)+num(r.er)});box.innerHTML=`<div class="card"><div class="title">Rozbicie wypłaty — ostatni miesiąc <span class="pill">szacunek</span></div><div class="salarySplit22"><div><small>BRUTTO</small><b>${PLN(last.g)}</b></div><div><small>NETTO</small><b>${PLN(last.total)}</b></div><div><small>EMERYTALNA 9,76%</small><b>${PLN(b.pension)}</b></div><div><small>RENTOWA 1,5%</small><b>${PLN(b.disability)}</b></div><div><small>CHOROBOWA 2,45%</small><b>${PLN(b.sickness)}</b></div><div><small>ZDROWOTNA 9%</small><b>${PLN(b.health)}</b></div><div><small>PIT</small><b>${PLN(b.pit)}</b></div><div><small>PPK PRACOWNIK</small><b>${PLN(last.pe)}</b></div><div><small>PPK PRACODAWCA</small><b class="green">${PLN(last.er)}</b></div><div><small>KOSZT PRACODAWCY</small><b>${PLN(b.totalCost)}</b></div></div><p class="muted">Składki i PIT są estymacją na podstawie standardowych stawek; faktyczna lista płac może różnić się przez ulgi, limity i parametry pracodawcy.</p></div><div class="card"><div class="title">PPK — rozbudowany podgląd</div><div class="monthKpis"><div><small>WPŁATY PRACOWNIKA ${y}</small><b>${PLN(emp)}</b></div><div><small>WPŁATY PRACODAWCY ${y}</small><b>${PLN(er)}</b></div><div><small>RAZEM WPŁATY</small><b>${PLN(emp+er)}</b></div><div><small>PROGNOZOWANA WARTOŚĆ</small><b class="green">${PLN(ppk)}</b></div></div><div class="form"><label>Saldo początkowe PPK<input id="ppkOpening22" type="number" value="${opening}"></label><label>Założona stopa zwrotu % rocznie<input id="ppkReturn22" type="number" step="0.1" value="${num(S.finance.ppkReturnPct)}"></label></div><button class="btn primary" onclick="savePpk22()">Zapisz parametry PPK</button><div class="ppkMonths22">${rows.map((r,i)=>`<div><span>${M[i]}</span><b>${PLN(num(r.pe)+num(r.er))}</b><small>Ty ${PLN(r.pe)} • pracodawca ${PLN(r.er)}</small></div>`).join('')}</div></div><div class="card"><div class="title">Etat — rok ${y}</div><div class="grid"><div class="tile"><small>BRUTTO</small><b>${PLN(g)}</b></div><div class="tile"><small>NETTO</small><b>${PLN(net)}</b></div><div class="tile"><small>PPK ŁĄCZNIE</small><b>${PLN(emp+er)}</b></div><div class="tile"><small>ŚREDNIE NETTO</small><b>${PLN(actual.length?net/actual.length:0)}</b></div></div></div>`}
function renderBudgetDeep(){let host=G('budgetBody');if(!host)return;let box=G('budgetAnalytics22');if(!box){box=document.createElement('div');box.id='budgetAnalytics22';host.insertAdjacentElement('afterend',box)}let k=S.finance.analysisMonth||TODAY.slice(0,7),cats=[...new Set(['Mieszkanie','Jedzenie','Transport','Subskrypcje','Ubezpieczenia','Zdrowie','Inne',...expenseRows(k).map(e=>e.category||'Inne')])],actualMap=S.finance.budgetActual[k]||{};box.innerHTML=`<div class="card"><div class="title">Budżet kategorii — plan vs wykonanie <span class="pill">${k}</span></div>${cats.map(c=>{let plan=num(S.finance.categoryLimits[c]),committed=expenseRows(k).filter(e=>(e.category||'Inne')===c).reduce((a,e)=>a+num(e.amount),0),actual=actualMap[c]!==undefined?num(actualMap[c]):committed,p=plan?Math.min(130,actual/plan*100):0;return`<div class="budgetCat22"><div><b>${esc(c)}</b><small>plan ${PLN(plan)} • stałe ${PLN(committed)}</small></div><div class="budgetTrack22"><i style="width:${Math.min(100,p)}%" class="${p>100?'over':''}"></i></div><strong class="${p>100?'red':''}">${plan?p.toFixed(0)+'%':'—'}</strong><input type="number" id="limit22_${safeId(c)}" value="${plan||''}" placeholder="limit"><input type="number" id="actual22_${safeId(c)}" value="${actual||''}" placeholder="wykonanie"></div>`}).join('')}<button class="btn primary" onclick='saveBudget22(${JSON.stringify(cats)})'>Zapisz limity i wykonanie</button></div>`}
function safeId(s){return s.replace(/[^a-zA-Z0-9]/g,'_')}
function renderBusinessDeep(){let host=G('businessPlusBody');if(!host)return;let box=G('businessKpi22');if(!box){box=document.createElement('div');box.id='businessKpi22';host.insertAdjacentElement('beforebegin',box)}let y=S.selectedYear,rows=Array.from({length:12},(_,i)=>companyData(y,i)),actual=rows.filter(r=>r.actual),rev=actual.reduce((a,r)=>a+r.revenue,0),cost=actual.reduce((a,r)=>a+r.costs+r.zus+r.health+r.tax+r.vat,0),profit=actual.reduce((a,r)=>a+r.profit,0),margin=rev?profit/rev*100:0,avgRev=actual.length?rev/actual.length:0,avgProfit=actual.length?profit/actual.length:0,forecastRev=avgRev*12,forecastProfit=avgProfit*12,mx=Math.max(1,...rows.map(r=>Math.abs(r.profit)));box.innerHTML=`<div class="card"><div class="title">Firma+ — KPI i prognoza ${y}</div><div class="monthKpis"><div><small>PRZYCHÓD YTD</small><b>${PLN(rev)}</b></div><div><small>REALNIE ZOSTAJE YTD</small><b class="${profit>=0?'green':'red'}">${PLN(profit)}</b></div><div><small>MARŻA GOTÓWKOWA</small><b>${margin.toFixed(1)}%</b></div><div><small>PROGNOZA PRZYCHODU</small><b>${PLN(forecastRev)}</b></div><div><small>PROGNOZA WYNIKU</small><b>${PLN(forecastProfit)}</b></div><div><small>ŚR. KOSZT / MIES.</small><b>${PLN(actual.length?cost/actual.length:0)}</b></div></div><div class="bizTrend22">${rows.map((r,i)=>`<div><i class="${r.profit<0?'neg':''}" style="height:${Math.abs(r.profit)/mx*80}px"></i><small>${M[i]}</small></div>`).join('')}</div></div>`}
function renderLoanScenarios(){document.querySelectorAll('#loanList .loan').forEach((card,i)=>{let l=S.loans[i];if(!l)return;let old=card.querySelector('.loanScenario22');if(old)old.remove();let extras=[0,num(l.extraMonthly),250,500,1000].filter((v,idx,a)=>a.indexOf(v)===idx).sort((a,b)=>a-b),base=payoff(l,0),html=`<div class="loanScenario22"><div class="loanChartHead"><div><b>Porównanie nadpłat</b><small>wpływ na czas spłaty i przyszłe odsetki</small></div></div><div class="scenarioLoanGrid22">${extras.map(ex=>{let p=payoff(l,ex),saved=Math.max(0,base.interest-p.interest),months=Math.max(0,base.m-p.m);return`<div class="${ex===num(l.extraMonthly)?'active':''}"><small>NADPŁATA / MIES.</small><b>${PLN(ex)}</b><span>spłata ${payoffDate(p.m)}</span><span>${months?months+' mies. szybciej':'bazowy okres'}</span><span>${l.loanType==='zero'?'odsetki 0 zł':'odsetki '+PLN(p.interest)}</span><strong class="green">${saved?'oszczędzasz '+PLN(saved):''}</strong></div>`}).join('')}</div></div>`;let target=card.querySelector('.loanResultGrid')||card.querySelector('.loanEdit');if(target)target.insertAdjacentHTML('afterend',html);else card.insertAdjacentHTML('beforeend',html)})}
function injectHome(){let life=G('lifeHome');if(!life||G('lifeCalendar'))return;life.insertAdjacentHTML('beforeend',`<button id="lifeCalendar" class="lifeTile" onclick="show('calendar')"><small>KALENDARZ</small><b>Terminy</b><span>raty i opłaty</span></button><button class="lifeTile" onclick="show('emergency')"><small>PODUSZKA</small><b>${num(S.finance.emergencyTargetMonths)} mies.</b><span>bezpieczeństwo</span></button><button class="lifeTile" onclick="show('scenario')"><small>SCENARIUSZE</small><b>Co jeśli?</b><span>12 miesięcy</span></button><button class="lifeTile" onclick="show('debt')"><small>ZADŁUŻENIE</small><b>${PLN(S.loans.reduce((a,l)=>a+currentBalance(l),0))}</b><span>analiza</span></button>`)}
function enhance(){ensure();document.title='Moje Finanse 2.2';let hs=document.querySelector('.top small');if(hs)hs.innerHTML=`<span id="headerYear">${S.selectedYear}</span> • wersja 2.2`;injectHome();renderCalendar();renderEmergency();renderScenario();renderDebt();renderActions();renderSalaryDeep();renderBudgetDeep();renderBusinessDeep();renderLoanScenarios()}
window.shiftAnalysisMonth=function(d){S.finance.analysisMonth=addMonths(S.finance.analysisMonth||TODAY.slice(0,7),d);save();enhance()};
window.calendarEventModal21=function(){open(`<h2>Wydarzenie finansowe</h2><div class="form"><label>Miesiąc<input id="ceMonth21" type="month" value="${S.finance.analysisMonth}"></label><label>Dzień<input id="ceDay21" type="number" min="1" max="31"></label><label>Nazwa<input id="ceName21"></label><label>Kwota<input id="ceAmount21" type="number"></label></div><button class="btn primary" onclick="saveCalendarEvent21()">Dodaj</button>`)};
window.saveCalendarEvent21=function(){S.finance.calendarEvents.push({month:G('ceMonth21').value,day:num(G('ceDay21').value),name:G('ceName21').value||'Wydarzenie',amount:num(G('ceAmount21').value)});save();closeModal();enhance()};
window.saveEmergency21=function(){S.finance.emergencySavings=num(G('emergencySavings21').value);S.finance.emergencyTargetMonths=Math.max(1,num(G('emergencyMonths21').value));save();enhance()};
window.saveScenario21=function(){S.finance.scenario={salaryPct:num(G('scSalary21').value),companyPct:num(G('scCompany21').value),expensePct:num(G('scExpense21').value),extraDebt:num(G('scDebt21').value)};save();enhance()};
window.savePpk22=function(){S.finance.ppkOpening=num(G('ppkOpening22').value);S.finance.ppkReturnPct=num(G('ppkReturn22').value);save();enhance()};
window.saveBudget22=function(cats){let k=S.finance.analysisMonth||TODAY.slice(0,7);S.finance.budgetActual[k]||={};cats.forEach(c=>{S.finance.categoryLimits[c]=num(G('limit22_'+safeId(c)).value);S.finance.budgetActual[k][c]=num(G('actual22_'+safeId(c)).value)});save();enhance()};
ensure();const oldRender=window.render;if(typeof oldRender==='function')window.render=function(){oldRender();setTimeout(enhance,0)};setTimeout(enhance,0);
})();