/* Moje Finanse 2.1 — kalendarz, scenariusze, poduszka, analiza zadłużenia */
(function(){
const G=id=>document.getElementById(id), num=v=>+v||0, PLN=v=>F(num(v));
const FULL=['Styczeń','Luty','Marzec','Kwiecień','Maj','Czerwiec','Lipiec','Sierpień','Wrzesień','Październik','Listopad','Grudzień'];
function ensure21(){S.finance||={};S.finance.calendarEvents||=[];S.finance.scenario||={salaryPct:0,companyPct:0,expensePct:0,extraDebt:0};S.finance.emergencySavings=num(S.finance.emergencySavings);S.finance.emergencyTargetMonths=num(S.finance.emergencyTargetMonths)||6;S.finance.analysisMonth||=S.finance.selectedMonth||TODAY.slice(0,7);save()}
function monthKey(y,m){return `${y}-${String(m+1).padStart(2,'0')}`}
function parseKey(k){let [y,m]=k.split('-').map(Number);return{y,m:m-1}}
function addMonths(k,delta){let {y,m}=parseKey(k),d=new Date(y,m+delta,1,12);return monthKey(d.getFullYear(),d.getMonth())}
function salaryData(y,m){let old=S.selectedYear;S.selectedYear=y;Y();let r=sal().rows[m]||{};S.selectedYear=old;Y();return{net:num(r.total),gross:num(r.g),ppkEmp:num(r.pe),ppkEr:num(r.er)}}
function companyData(y,m){let r=(S.years[String(y)]||blank()).company?.[m]||{},rev=num(r.revenue),cost=num(r.costs),zus=num(r.zus),health=num(r.health),tax=num(r.tax),vat=(num(r.vatOut)||num(r.vatIn))?num(r.vatOut)-num(r.vatIn):num(r.vat);return{revenue:rev,costs:cost,profit:rev-cost-zus-health-tax-vat}}
function expenseFor(k){return (S.finance.expenses||[]).filter(e=>e.active!==false&&(!e.from||k>=e.from)&&(!e.to||k<=e.to)).reduce((a,e)=>a+num(e.amount),0)}
function histForLoan(l,k){return (l.history||[]).find(h=>(h.month||'')===k)}
function loanSpend(k){return S.loans.reduce((a,l)=>{let h=histForLoan(l,k);if(h){let regular=typeof h.paid==='boolean'?(h.paid?num(h.regularPaid||l.payment):0):num(h.regularPaid!=null?h.regularPaid:h.paid),extra=h.isOverpayment===false?0:num(h.extra);return a+regular+extra}if(k<(l.asOfDate||TODAY).slice(0,7))return a;return a+num(l.payment)+num(l.extraMonthly)},0)}
function monthFlow(k){let {y,m}=parseKey(k),s=salaryData(y,m),c=companyData(y,m),e=expenseFor(k),lo=loanSpend(k),income=s.net+Math.max(0,c.profit);return{key:k,y,m,s,c,expenses:e,loans:lo,income,free:income-e-lo}}
function currentBalance(l){try{return num(loanPoint(l).balance)}catch{return num(l.balance)}}
function debtTotals(){let debt=S.loans.reduce((a,l)=>a+currentBalance(l),0),monthly=S.loans.reduce((a,l)=>a+num(l.payment)+num(l.extraMonthly),0),weighted=debt?S.loans.reduce((a,l)=>a+currentBalance(l)*num(l.rate),0)/debt:0;return{debt,monthly,weighted}}
function payoffMonths(l,extra=0){let b=currentBalance(l),rate=num(l.rate)/1200,pay=num(l.payment)+num(extra),m=0,interest=0;if(l.loanType==='zero'||!rate){return{m:Math.ceil(b/Math.max(1,pay)),interest:0}}while(b>.01&&m<600&&pay>b*rate){let it=b*rate;interest+=it;b=Math.max(0,b-(pay-it));m++}return{m,interest}}
function payoffDate(months){let d=new Date(TODAY+'T12:00:00');d.setMonth(d.getMonth()+months);return d.toLocaleDateString('pl-PL',{month:'2-digit',year:'numeric'})}
function renderCalendar(){let host=G('calendarBody');if(!host)return;let k=S.finance.analysisMonth||TODAY.slice(0,7),{y,m}=parseKey(k),first=new Date(y,m,1,12),days=new Date(y,m+1,0,12).getDate(),offset=(first.getDay()+6)%7,events={};function add(day,label,kind,amount){day=Math.max(1,Math.min(days,num(day)||1));(events[day]||=[]).push({label,kind,amount})}(S.finance.expenses||[]).filter(e=>e.active!==false&&(!e.from||k>=e.from)&&(!e.to||k<=e.to)).forEach(e=>add(e.day||1,e.name,'expense',e.amount));S.loans.forEach(l=>{if(k>=(l.asOfDate||TODAY).slice(0,7))add(l.dueDay||1,l.name,'loan',l.payment)});(S.finance.calendarEvents||[]).filter(e=>e.month===k).forEach(e=>add(e.day,e.name,'custom',e.amount));let cells='';for(let i=0;i<offset;i++)cells+='<div class="calDay empty"></div>';for(let d=1;d<=days;d++){cells+=`<div class="calDay"><b>${d}</b>${(events[d]||[]).map(e=>`<span class="calEvent ${e.kind}">${esc(e.label)}${num(e.amount)?' • '+PLN(e.amount):''}</span>`).join('')}</div>`}host.innerHTML=`<div class="card"><div class="calendarHead"><button class="btn" onclick="shiftAnalysisMonth(-1)">‹</button><b>${FULL[m]} ${y}</b><button class="btn" onclick="shiftAnalysisMonth(1)">›</button><button class="btn primary" onclick="calendarEventModal21()">＋ Wydarzenie</button></div><div class="calWeek"><span>Pn</span><span>Wt</span><span>Śr</span><span>Cz</span><span>Pt</span><span>So</span><span>Nd</span></div><div class="calendarGrid">${cells}</div><div class="legend"><span><i class="calDot expense"></i>wydatek</span><span><i class="calDot loan"></i>rata</span><span><i class="calDot custom"></i>własne</span></div></div>`}
function renderEmergency(){let host=G('emergencyBody');if(!host)return;let k=S.finance.analysisMonth||TODAY.slice(0,7),d=monthFlow(k),monthly=Math.max(0,d.expenses+d.loans),target=monthly*num(S.finance.emergencyTargetMonths),saved=num(S.finance.emergencySavings),monthsCovered=monthly?saved/monthly:0,p=Math.min(100,target?saved/target*100:0);host.innerHTML=`<div class="wealthHero"><small>PODUSZKA FINANSOWA</small><h2>${monthsCovered.toFixed(1)} mies.</h2><span>${PLN(saved)} oszczędności / ${PLN(target)} celu</span></div><div class="card"><div class="title">Bezpieczeństwo finansowe</div><div class="progress"><i style="width:${p}%"></i></div><div class="goalStats"><span>miesięczne obciążenia ${PLN(monthly)}</span><span>cel ${num(S.finance.emergencyTargetMonths)} mies.</span><span>brakuje ${PLN(Math.max(0,target-saved))}</span></div><div class="form"><label>Oszczędności płynne<input id="emergencySavings21" type="number" value="${saved}"></label><label>Cel w miesiącach<input id="emergencyMonths21" type="number" min="1" max="36" value="${num(S.finance.emergencyTargetMonths)}"></label></div><button class="btn primary" onclick="saveEmergency21()">Zapisz</button></div>`}
function scenarioRows(){let sc=S.finance.scenario||{},start=S.finance.analysisMonth||TODAY.slice(0,7),rows=[];for(let i=0;i<12;i++){let k=addMonths(start,i),d=monthFlow(k),income=d.s.net*(1+num(sc.salaryPct)/100)+Math.max(0,d.c.profit)*(1+num(sc.companyPct)/100),expenses=d.expenses*(1+num(sc.expensePct)/100),loans=d.loans+num(sc.extraDebt),free=income-expenses-loans;rows.push({k,base:d.free,scenario:free})}return rows}
function renderScenario(){let host=G('scenarioBody');if(!host)return;let sc=S.finance.scenario||{},rows=scenarioRows(),base=rows.reduce((a,r)=>a+r.base,0),alt=rows.reduce((a,r)=>a+r.scenario,0),mx=Math.max(1,...rows.flatMap(r=>[Math.abs(r.base),Math.abs(r.scenario)]));host.innerHTML=`<div class="grid"><div class="tile"><small>BAZA — 12 MIES.</small><b>${PLN(base)}</b></div><div class="tile"><small>SCENARIUSZ — 12 MIES.</small><b class="${alt>=base?'green':'red'}">${PLN(alt)}</b></div><div class="tile"><small>RÓŻNICA</small><b class="${alt-base>=0?'green':'red'}">${alt-base>=0?'+ ':''}${PLN(alt-base)}</b></div></div><div class="card"><div class="title">Założenia scenariusza</div><div class="form scenarioForm"><label>Zmiana etatu %<input id="scSalary21" type="number" step="1" value="${num(sc.salaryPct)}"></label><label>Zmiana firmy %<input id="scCompany21" type="number" step="1" value="${num(sc.companyPct)}"></label><label>Zmiana wydatków %<input id="scExpense21" type="number" step="1" value="${num(sc.expensePct)}"></label><label>Dodatkowa nadpłata / mies.<input id="scDebt21" type="number" value="${num(sc.extraDebt)}"></label></div><button class="btn primary" onclick="saveScenario21()">Przelicz scenariusz</button></div><div class="card"><div class="title">Wolna gotówka — baza vs scenariusz</div><div class="scenarioBars">${rows.map(r=>`<div class="scenarioCol"><div class="scenarioStack"><i class="scenarioAlt" style="height:${Math.abs(r.scenario)/mx*110}px"></i><i class="scenarioBase" style="height:${Math.abs(r.base)/mx*110}px"></i></div><small>${r.k.slice(5)}/${r.k.slice(2,4)}</small></div>`).join('')}</div><div class="legend"><span><i class="scenarioLegend base"></i>baza</span><span><i class="scenarioLegend alt"></i>scenariusz</span></div></div>`}
function renderDebtAnalysis(){let host=G('debtBody');if(!host)return;let k=S.finance.analysisMonth||TODAY.slice(0,7),d=monthFlow(k),dt=debtTotals(),ratio=d.income?dt.monthly/d.income*100:0,sortedSnow=[...S.loans].sort((a,b)=>currentBalance(a)-currentBalance(b)),sortedAval=[...S.loans].sort((a,b)=>num(b.rate)-num(a.rate)),next=sortedSnow[0],nextPay=next?payoffMonths(next,num(next.extraMonthly)):null;host.innerHTML=`<div class="monthKpis"><div><small>ŁĄCZNE ZADŁUŻENIE</small><b>${PLN(dt.debt)}</b></div><div><small>RATY / DOCHÓD</small><b class="${ratio>40?'red':ratio>25?'':'green'}">${ratio.toFixed(1)}%</b></div><div><small>ŚR. OPROCENTOWANIE</small><b>${dt.weighted.toFixed(2)}%</b></div><div><small>NAJBLIŻSZY DO ZERA</small><b>${next?esc(next.name):'—'}</b><span>${nextPay?payoffDate(nextPay.m):''}</span></div></div><div class="card"><div class="title">Kolejność spłaty</div><div class="two debtStrategies"><div><b>Snowball — najmniejsze saldo</b>${sortedSnow.map((l,i)=>`<div class="debtRank"><span>${i+1}. ${esc(l.name)}</span><b>${PLN(currentBalance(l))}</b></div>`).join('')}</div><div><b>Avalanche — najwyższy procent</b>${sortedAval.map((l,i)=>`<div class="debtRank"><span>${i+1}. ${esc(l.name)}</span><b>${num(l.rate).toFixed(2)}%</b></div>`).join('')}</div></div></div>${debtAdvice(d,ratio)}`}
function debtAdvice(d,ratio){let lines=[];if(!S.loans.length)lines.push('Brak aktywnych kredytów.');else{if(ratio>40)lines.push('Raty przekraczają 40% miesięcznego dochodu — priorytetem jest płynność i poduszka.');else if(ratio>25)lines.push('Obciążenie kredytami jest zauważalne; nadpłaty warto kierować na najdroższy kredyt.');else lines.push('Udział rat w dochodzie jest relatywnie niski; możesz elastyczniej łączyć nadpłaty z budowaniem oszczędności.');if(d.free>0)lines.push(`Po bieżących obciążeniach zostaje około ${PLN(d.free)} w tym miesiącu.`)}return `<div class="card"><div class="title">Wnioski</div>${lines.map(x=>`<div class="alertRow">• <span>${x}</span></div>`).join('')}</div>`}
function renderActionCenter(){let host=G('actionBody');if(!host)return;let k=S.finance.analysisMonth||TODAY.slice(0,7),d=monthFlow(k),items=[],nowDay=new Date().getDate();S.loans.forEach(l=>{let h=histForLoan(l,k);if(!h)items.push({kind:'Rata',text:`${esc(l.name)} — ${PLN(l.payment)}`,day:num(l.dueDay)||1})});(S.finance.expenses||[]).filter(e=>e.active!==false&&(!e.from||k>=e.from)&&(!e.to||k<=e.to)).forEach(e=>items.push({kind:'Wydatek',text:`${esc(e.name)} — ${PLN(e.amount)}`,day:num(e.day)||1}));items.sort((a,b)=>a.day-b.day);host.innerHTML=`<div class="card actionHero"><small>CO MAM ZROBIĆ W TYM MIESIĄCU?</small><h2>${PLN(d.free)}</h2><span>prognozowana wolna gotówka po stałych kosztach i ratach</span></div><div class="card"><div class="title">Plan miesiąca</div>${items.length?items.map(i=>`<div class="actionRow ${i.day<nowDay&&k===TODAY.slice(0,7)?'late':''}"><b>${String(i.day).padStart(2,'0')}</b><span><small>${i.kind}</small>${i.text}</span></div>`).join(''):'<p class="muted">Brak zaplanowanych pozycji.</p>'}</div>`}
function injectHome21(){let life=G('lifeHome');if(!life||G('lifeCalendar'))return;life.insertAdjacentHTML('beforeend',`<button id="lifeCalendar" class="lifeTile" onclick="show('calendar')"><small>KALENDARZ</small><b>Terminy</b><span>raty i opłaty</span></button><button class="lifeTile" onclick="show('emergency')"><small>PODUSZKA</small><b>${num(S.finance.emergencyTargetMonths)} mies.</b><span>bezpieczeństwo</span></button><button class="lifeTile" onclick="show('scenario')"><small>SCENARIUSZE</small><b>Co jeśli?</b><span>12 miesięcy</span></button><button class="lifeTile" onclick="show('debt')"><small>ZADŁUŻENIE</small><b>${PLN(debtTotals().debt)}</b><span>analiza</span></button>`)}
function render21(){ensure21();injectHome21();renderCalendar();renderEmergency();renderScenario();renderDebtAnalysis();renderActionCenter()}
window.shiftAnalysisMonth=function(d){S.finance.analysisMonth=addMonths(S.finance.analysisMonth||TODAY.slice(0,7),d);save();render21()};
window.calendarEventModal21=function(){let k=S.finance.analysisMonth||TODAY.slice(0,7);open(`<h2>Dodaj wydarzenie</h2><div class="form"><label>Miesiąc<input id="ceMonth21" type="month" value="${k}"></label><label>Dzień<input id="ceDay21" type="number" min="1" max="31" value="1"></label><label>Nazwa<input id="ceName21" placeholder="np. ubezpieczenie auta"></label><label>Kwota<input id="ceAmount21" type="number"></label></div><div class="actions"><button class="btn" onclick="closeModal()">Anuluj</button><button class="btn primary" onclick="saveCalendarEvent21()">Dodaj</button></div>`)};
window.saveCalendarEvent21=function(){S.finance.calendarEvents.push({month:G('ceMonth21').value||S.finance.analysisMonth,day:num(G('ceDay21').value)||1,name:G('ceName21').value||'Wydarzenie',amount:num(G('ceAmount21').value)});save();closeModal();render21()};
window.saveEmergency21=function(){S.finance.emergencySavings=num(G('emergencySavings21').value);S.finance.emergencyTargetMonths=Math.max(1,num(G('emergencyMonths21').value)||6);save();render21()};
window.saveScenario21=function(){S.finance.scenario={salaryPct:num(G('scSalary21').value),companyPct:num(G('scCompany21').value),expensePct:num(G('scExpense21').value),extraDebt:num(G('scDebt21').value)};save();render21()};
const oldRender=window.render;window.render=function(){if(oldRender)oldRender();render21()};
const oldShow=window.show;window.show=function(v){if(oldShow)oldShow(v);render21()};
ensure21();setTimeout(render21,0);
})();