/* Moje Finanse 2.9 — symulator podwyżki bez nadpisywania wersji */
(function(){
const G=id=>document.getElementById(id),num=v=>+v||0,PLN=v=>F(num(v));
const FULL=['Styczeń','Luty','Marzec','Kwiecień','Maj','Czerwiec','Lipiec','Sierpień','Wrzesień','Październik','Listopad','Grudzień'];
function ensure(){S.finance||={};if(S.finance.raiseGross==null)S.finance.raiseGross=500;if(S.finance.raiseStartMonth==null)S.finance.raiseStartMonth=Math.max(0,new Date().getMonth());}
function rows(){return typeof sal==='function'?sal().rows.map((r,i)=>({...r,i})):[]}
function simulate(rs,start,raise){let cum=0,base=[],alt=[];for(let i=0;i<12;i++){let ep=num(rs[i]?.ppkEmpPct||2),er=num(rs[i]?.ppkErPct||1.5),g=num(rs[i]?.g),b=fg(g,cum,ep,er);base.push({...b,i});cum+=b.base}cum=0;for(let i=0;i<12;i++){let ep=num(rs[i]?.ppkEmpPct||2),er=num(rs[i]?.ppkErPct||1.5),g=Math.max(0,num(rs[i]?.g)+(i>=start?raise:0)),a=fg(g,cum,ep,er);alt.push({...a,i});cum+=a.base}return{base,alt}}
function render24(){let sec=G('salary');if(!sec)return;let anchor=G('salaryDeep23')||sec,box=G('salaryRaise24');if(!box){box=document.createElement('div');box.id='salaryRaise24';anchor.appendChild(box)}let rs=rows();if(!rs.length)return;let start=Math.max(0,Math.min(11,num(S.finance.raiseStartMonth))),raise=num(S.finance.raiseGross),sim=simulate(rs,start,raise),base=sim.base[start],alt=sim.alt[start],delta=alt.net-base.net,annual=sim.alt.reduce((a,r)=>a+r.net,0)-sim.base.reduce((a,r)=>a+r.net,0),grossBase=num(rs[start]?.g),mx=Math.max(1,...sim.base.map((r,i)=>Math.max(r.net,sim.alt[i].net)));box.innerHTML=`<div class="card"><div class="title">Symulator podwyżki <span class="pill">symulacja, bez zmiany danych</span></div><div class="raiseControls24"><label>Podwyżka brutto<input id="raiseGross24" type="number" step="50" value="${raise}"></label><label>Od miesiąca<select id="raiseMonth24">${FULL.map((m,i)=>`<option value="${i}" ${i===start?'selected':''}>${m}</option>`).join('')}</select></label><button class="btn primary" onclick="saveRaise24()">Przelicz</button></div><div class="salarySplit23 raiseStats24"><div><small>NOWE BRUTTO</small><b>${PLN(grossBase+raise)}</b></div><div><small>WIĘCEJ NETTO / MIES.</small><b class="green">+ ${PLN(delta)}</b></div><div><small>WIĘCEJ NETTO DO KOŃCA ROKU</small><b class="green">+ ${PLN(annual)}</b></div><div><small>PPK TY / MIES.</small><b>+ ${PLN(alt.pe-base.pe)}</b></div><div><small>PPK FIRMA / MIES.</small><b>+ ${PLN(alt.er-base.er)}</b></div></div><div class="raiseChart24">${sim.base.map((r,i)=>`<div><div class="raiseBars24"><i class="alt" style="height:${Math.max(2,sim.alt[i].net/mx*105)}px"></i><i class="base" style="height:${Math.max(2,r.net/mx*105)}px"></i></div><small>${M[i]}</small></div>`).join('')}</div><div class="payLegend23"><span><i class="raiseBaseLegend24"></i>obecne netto</span><span><i class="raiseAltLegend24"></i>po podwyżce</span></div></div>`}
window.saveRaise24=function(){S.finance.raiseGross=num(G('raiseGross24').value);S.finance.raiseStartMonth=num(G('raiseMonth24').value);save();render24()};
ensure();const prev=window.render;if(typeof prev==='function')window.render=function(){prev();render24()};setTimeout(render24,120);
})();