/* Moje Finanse 2.5 — pełne moduły dodatkowe */
(function(){
const G=id=>document.getElementById(id), N=v=>+v||0;
const PLN=v=>new Intl.NumberFormat('pl-PL',{style:'currency',currency:'PLN',minimumFractionDigits:0,maximumFractionDigits:2}).format(N(v));
const FULL=['Styczeń','Luty','Marzec','Kwiecień','Maj','Czerwiec','Lipiec','Sierpień','Wrzesień','Październik','Listopad','Grudzień'];
const nowKey=()=>TODAY.slice(0,7);
const key=(y,m)=>`${y}-${String(m+1).padStart(2,'0')}`;
function ensure(){S.finance||={};S.finance.expenses||=[];S.finance.assets||=[];S.finance.goals||=[];S.finance.calendarEvents||=[];S.finance.scenario||={salaryPct:0,companyPct:0,expensePct:0,extraDebt:0};S.finance.selectedMonth||=nowKey();S.finance.analysisMonth||=S.finance.selectedMonth;S.finance.emergencySavings=N(S.finance.emergencySavings);S.finance.emergencyTargetMonths=N(S.finance.emergencyTargetMonths)||6;}
function parse(k){let [y,m]=k.split('-').map(Number);return{y,m:m-1}}
function addMonth(k,d){let {y,m}=parse(k),x=new Date(y,m+d,1,12);return key(x.getFullYear(),x.getMonth())}
function salary(y,m){let yr=S.years?.[String(y)]||{},r=yr.salary?.[m]||{};let net=N(r.net)+N(r.bonus);if(!net&&typeof sal==='function'){try{let old=S.selectedYear;S.selectedYear=y;Y();let z=sal().rows[m]||{};S.selectedYear=old;Y();return{net:N(z.total),gross:N(z.g),ppkEmp:N(z.pe),ppkEr:N(z.er),actual:!!z.actual}}catch{}}return{net,gross:N(r.gross),ppkEmp:N(r.ppkEmp),ppkEr:N(r.ppkEr),actual:!!r.actual}}
function company(y,m){let r=(S.years?.[String(y)]||{}).company?.[m]||{},rev=N(r.revenue),cost=N(r.costs),zus=N(r.zus),health=N(r.health),tax=N(r.tax),vat=(N(r.vatOut)||N(r.vatIn))?N(r.vatOut)-N(r.vatIn):N(r.vat);return{rev,cost,zus,health,tax,vat,profit:rev-cost-zus-health-tax-vat}}
function expRows(k){return (S.finance.expenses||[]).filter(e=>e.active!==false&&(!e.from||k>=e.from)&&(!e.to||k<=e.to))}
function expTotal(k){return expRows(k).reduce((a,e)=>a+N(e.amount),0)}
function hist(l,k){return (l.history||[]).find(h=>(h.month||'')===k)}
function loanSpend(k){return (S.loans||[]).reduce((a,l)=>{let h=hist(l,k);if(h){let reg=h.paid?N(h.regularPaid||l.payment):0,ex=h.isOverpayment?N(h.extra):0;return a+reg+ex}if(k<(l.asOfDate||TODAY).slice(0,7))return a;return a+N(l.payment)+N(l.extraMonthly)},0)}
function balance(l){try{return N(loanPoint(l).balance)}catch{return N(l.balance)}}
function flow(k){let {y,m}=parse(k),s=salary(y,m),c=company(y,m),e=expTotal(k),lo=loanSpend(k),income=s.net+Math.max(0,c.profit);return{k,y,m,s,c,e,lo,income,free:income-e-lo}}
function monthNav(k,fn){let {y,m}=parse(k);return `<div class="card miniNav"><button class="btn" onclick="${fn}(-1)">‹</button><b>${FULL[m]} ${y}</b><button class="btn" onclick="${fn}(1)">›</button></div>`}
function kpis(items){return `<div class="v25Kpis">${items.map(x=>`<div><small>${x[0]}</small><b class="${x[2]||''}">${x[1]}</b>${x[3]?`<span>${x[3]}</span>`:''}</div>`).join('')}</div>`}
function renderMonthly(){let h=G('monthlyBody');if(!h)return;let k=S.finance.selectedMonth||nowKey(),d=flow(k),ob=expRows(k);h.innerHTML=`${monthNav(k,'v25ShiftMonth')}${kpis([['DOCHODY',PLN(d.income),'green'],['WYDATKI STAŁE',PLN(d.e)],['KREDYTY',PLN(d.lo)],['WOLNA GOTÓWKA',PLN(d.free),d.free<0?'red':'green']])}<div class="card"><div class="title">Przepływ pieniędzy</div><div class="v25Flow"><div><span>Etat</span><b>${PLN(d.s.net)}</b></div><div><span>Firma</span><b>${PLN(d.c.profit)}</b></div><div class="minus"><span>Wydatki</span><b>− ${PLN(d.e)}</b></div><div class="minus"><span>Raty</span><b>− ${PLN(d.lo)}</b></div><div class="result"><span>Zostaje</span><b>${PLN(d.free)}</b></div></div></div><div class="card"><div class="title">Obciążenia miesiąca</div>${ob.length?ob.map(e=>`<div class="v25Row"><span>${esc(e.name)}<small>${esc(e.category||'Stały wydatek')} • dzień ${e.day||'—'}</small></span><b>${PLN(e.amount)}</b></div>`).join(''):'<p class="muted">Brak wpisanych wydatków stałych.</p>'}${(S.loans||[]).map(l=>`<div class="v25Row"><span>${esc(l.name)}<small>rata kredytu • dzień ${l.dueDay||'—'}</small></span><b>${PLN(N(l.payment)+N(l.extraMonthly))}</b></div>`).join('')}</div>`}
function renderBudget(){let h=G('budgetBody');if(!h)return,k=S.finance.analysisMonth||nowKey(),rows=expRows(k),total=expTotal(k),cats={};rows.forEach(e=>cats[e.category||'Inne']=(cats[e.category||'Inne']||0)+N(e.amount));h.innerHTML=`${monthNav(k,'v25ShiftAnalysis')}${kpis([['STAŁE / MIES.',PLN(total)],['STAŁE / ROK',PLN(total*12)],['POZYCJI',String(rows.length)]])}<div class="card"><div class="title">Kategorie <button class="btn primary" onclick="expenseModal20&&expenseModal20()">＋ Dodaj wydatek</button></div>${Object.entries(cats).sort((a,b)=>b[1]-a[1]).map(([c,v])=>`<div class="v25BudgetBar"><span>${esc(c)}</span><i><b style="width:${total?v/total*100:0}%"></b></i><strong>${PLN(v)}</strong></div>`).join('')||'<p class="muted">Dodaj pierwsze stałe koszty.</p>'}</div><div class="card"><div class="title">Lista wydatków</div>${rows.map((e,i)=>`<div class="v25Row"><span><b>${esc(e.name)}</b><small>${esc(e.category||'Inne')} • dzień ${e.day||'—'}</small></span><b>${PLN(e.amount)}</b></div>`).join('')||'<p class="muted">Brak pozycji.</p>'}</div>`}
function renderWealth(){let h=G('wealthBody');if(!h)return;let assets=(S.finance.assets||[]).reduce((a,x)=>a+N(x.value),0),debt=(S.loans||[]).reduce((a,l)=>a+balance(l),0),ppk=N(S.finance.ppkOpening),net=assets+ppk-debt;h.innerHTML=`${kpis([['WARTOŚĆ NETTO',PLN(net),net<0?'red':'green'],['AKTYWA',PLN(assets)],['PPK / OSZCZĘDNOŚCI',PLN(ppk)],['KREDYTY',PLN(debt)]])}<div class="card"><div class="title">Aktywa <button class="btn primary" onclick="assetModal20&&assetModal20()">＋ Dodaj aktywo</button></div>${(S.finance.assets||[]).map(a=>`<div class="v25Row"><span>${esc(a.name)}<small>${esc(a.type||'Aktywo')}</small></span><b>${PLN(a.value)}</b></div>`).join('')||'<p class="muted">Dodaj gotówkę, oszczędności, inwestycje albo inne aktywa.</p>'}</div><div class="card"><div class="title">Zobowiązania</div>${(S.loans||[]).map(l=>`<div class="v25Row"><span>${esc(l.name)}<small>${N(l.rate).toFixed(2)}% • rata ${PLN(l.payment)}</small></span><b>${PLN(balance(l))}</b></div>`).join('')||'<p class="muted">Brak kredytów.</p>'}</div>`}
function renderGoals(){let h=G('goalsBody');if(!h)return;let gs=S.finance.goals||[];h.innerHTML=`${kpis([['AKTYWNE CELE',String(gs.length)],['ŁĄCZNY CEL',PLN(gs.reduce((a,g)=>a+N(g.target),0))],['JUŻ ODKŁADANE',PLN(gs.reduce((a,g)=>a+N(g.current),0))]])}<div class="card"><div class="title">Cele <button class="btn primary" onclick="goalModal20&&goalModal20()">＋ Dodaj cel</button></div>${gs.map((g,i)=>{let p=Math.min(100,N(g.current)/Math.max(1,N(g.target))*100),left=Math.max(0,N(g.target)-N(g.current)),months=N(g.monthly)>0?Math.ceil(left/N(g.monthly)):null;return`<div class="v25Goal"><div><b>${esc(g.name)}</b><strong>${p.toFixed(0)}%</strong></div><div class="progress"><i style="width:${p}%"></i></div><small>${PLN(g.current)} z ${PLN(g.target)} • brakuje ${PLN(left)}${months!=null?` • ok. ${months} mies.`:''}</small></div>`}).join('')||'<p class="muted">Dodaj cel finansowy, aby śledzić postęp.</p>'}</div>`}
function renderCalendar(){let h=G('calendarBody');if(!h)return,k=S.finance.analysisMonth||nowKey(),{y,m}=parse(k),days=new Date(y,m+1,0).getDate(),off=(new Date(y,m,1).getDay()+6)%7,E={};let add=(d,t,a,c)=>{d=Math.max(1,Math.min(days,N(d)||1));(E[d]||=[]).push({t,a,c})};expRows(k).forEach(e=>add(e.day,e.name,e.amount,'expense'));(S.loans||[]).forEach(l=>{if(k>=(l.asOfDate||TODAY).slice(0,7))add(l.dueDay,l.name,l.payment,'loan')});(S.finance.calendarEvents||[]).filter(e=>e.month===k).forEach(e=>add(e.day,e.name,e.amount,'custom'));let cells='';for(let i=0;i<off;i++)cells+='<div class="v25Day empty"></div>';for(let d=1;d<=days;d++)cells+=`<div class="v25Day"><b>${d}</b>${(E[d]||[]).map(e=>`<span class="${e.c}">${esc(e.t)}${N(e.a)?` • ${PLN(e.a)}`:''}</span>`).join('')}</div>`;h.innerHTML=`${monthNav(k,'v25ShiftAnalysis')}<div class="card"><div class="title">Terminy <button class="btn primary" onclick="calendarEventModal21&&calendarEventModal21()">＋ Wydarzenie</button></div><div class="v25Week"><span>Pn</span><span>Wt</span><span>Śr</span><span>Cz</span><span>Pt</span><span>So</span><span>Nd</span></div><div class="v25Calendar">${cells}</div></div>`}
function renderEmergency(){let h=G('emergencyBody');if(!h)return,k=S.finance.analysisMonth||nowKey(),d=flow(k),monthly=d.e+d.lo,s=N(S.finance.emergencySavings),target=monthly*N(S.finance.emergencyTargetMonths),months=monthly?s/monthly:0,p=target?Math.min(100,s/target*100):0;h.innerHTML=`${kpis([['PODUSZKA',PLN(s),'green'],['POKRYCIE',months.toFixed(1)+' mies.'],['CEL',PLN(target)],['BRAKUJE',PLN(Math.max(0,target-s))]])}<div class="card"><div class="title">Poziom bezpieczeństwa</div><div class="progress v25BigProgress"><i style="width:${p}%"></i></div><p class="muted">Liczymy wydatki stałe + raty kredytów dla wybranego miesiąca.</p><div class="form"><label>Płynne oszczędności<input id="v25EmergencySavings" type="number" step="0.01" value="${s}"></label><label>Cel w miesiącach<input id="v25EmergencyMonths" type="number" step="1" value="${N(S.finance.emergencyTargetMonths)}"></label></div><button class="btn primary" onclick="v25SaveEmergency()">Zapisz</button></div>`}
function renderScenario(){let h=G('scenarioBody');if(!h)return,sc=S.finance.scenario||{},start=S.finance.analysisMonth||nowKey(),rows=[];for(let i=0;i<12;i++){let k=addMonth(start,i),d=flow(k),alt=d.s.net*(1+N(sc.salaryPct)/100)+Math.max(0,d.c.profit)*(1+N(sc.companyPct)/100)-d.e*(1+N(sc.expensePct)/100)-d.lo-N(sc.extraDebt);rows.push({k,base:d.free,alt})}let b=rows.reduce((a,r)=>a+r.base,0),a=rows.reduce((s,r)=>s+r.alt,0);h.innerHTML=`${kpis([['BAZA 12 MIES.',PLN(b)],['SCENARIUSZ',PLN(a),a>=b?'green':'red'],['RÓŻNICA',PLN(a-b),a>=b?'green':'red']])}<div class="card"><div class="form"><label>Zmiana etatu %<input id="v25ScSalary" type="number" step="0.1" value="${N(sc.salaryPct)}"></label><label>Zmiana firmy %<input id="v25ScCompany" type="number" step="0.1" value="${N(sc.companyPct)}"></label><label>Zmiana kosztów %<input id="v25ScExpense" type="number" step="0.1" value="${N(sc.expensePct)}"></label><label>Dodatkowa nadpłata / mies.<input id="v25ScDebt" type="number" step="0.01" value="${N(sc.extraDebt)}"></label></div><button class="btn primary" onclick="v25SaveScenario()">Przelicz</button></div><div class="card"><div class="title">12 miesięcy</div>${rows.map(r=>`<div class="v25Row"><span>${r.k}</span><span>bazowo <b>${PLN(r.base)}</b> → scenariusz <b class="${r.alt>=r.base?'green':'red'}">${PLN(r.alt)}</b></span></div>`).join('')}</div>`}
function payoff(l,extra=0){let b=balance(l),rate=l.loanType==='zero'?0:N(l.rate)/1200,p=N(l.payment)+N(extra),m=0,int=0;if(p<=0)return{m:600,int:0};while(b>.01&&m<600){let it=b*rate;if(p<=it+.001)return{m:600,int};int+=it;b=Math.max(0,b-(p-it));m++}return{m,int}}
function renderDebt(){let h=G('debtBody');if(!h)return,d=flow(S.finance.analysisMonth||nowKey()),debt=(S.loans||[]).reduce((a,l)=>a+balance(l),0),monthly=(S.loans||[]).reduce((a,l)=>a+N(l.payment)+N(l.extraMonthly),0),ratio=d.income?monthly/d.income*100:0,weighted=debt?(S.loans||[]).reduce((a,l)=>a+balance(l)*N(l.rate),0)/debt:0,snow=[...(S.loans||[])].sort((a,b)=>balance(a)-balance(b)),aval=[...(S.loans||[])].sort((a,b)=>N(b.rate)-N(a.rate));h.innerHTML=`${kpis([['ŁĄCZNE SALDO',PLN(debt)],['RATY / DOCHÓD',ratio.toFixed(1)+'%'],['ŚR. OPROCENTOWANIE',weighted.toFixed(2)+'%']])}<div class="card"><div class="title">Każdy kredyt</div>${(S.loans||[]).map(l=>{let p=payoff(l,N(l.extraMonthly));return`<div class="v25Debt"><div><b>${esc(l.name)}</b><small>saldo ${PLN(balance(l))} • rata ${PLN(l.payment)} • ${N(l.rate).toFixed(2)}%</small></div><div><b>${p.m>=600?'600+':p.m} mies.</b><small>odsetki do końca ~ ${PLN(p.int)}</small></div></div>`}).join('')||'<p class="muted">Brak kredytów.</p>'}</div><div class="two"><div class="card"><div class="title">Snowball</div>${snow.map((l,i)=>`<div class="v25Row"><span>${i+1}. ${esc(l.name)}</span><b>${PLN(balance(l))}</b></div>`).join('')}</div><div class="card"><div class="title">Avalanche</div>${aval.map((l,i)=>`<div class="v25Row"><span>${i+1}. ${esc(l.name)}</span><b>${N(l.rate).toFixed(2)}%</b></div>`).join('')}</div></div>`}
function renderActions(){let h=G('actionBody');if(!h)return,k=S.finance.analysisMonth||nowKey(),d=flow(k),items=[];expRows(k).forEach(e=>items.push({day:N(e.day)||1,name:e.name,amount:N(e.amount),type:'Wydatek stały'}));(S.loans||[]).forEach(l=>{let hh=hist(l,k);if(!hh?.paid)items.push({day:N(l.dueDay)||1,name:l.name,amount:N(l.payment)+N(l.extraMonthly),type:'Rata kredytu'})});items.sort((a,b)=>a.day-b.day);h.innerHTML=`${monthNav(k,'v25ShiftAnalysis')}${kpis([['DO ZAPŁATY',PLN(items.reduce((a,x)=>a+x.amount,0))],['PO PLANIE ZOSTAJE',PLN(d.free),d.free<0?'red':'green'],['POZYCJI',String(items.length)]])}<div class="card"><div class="title">Lista na ten miesiąc</div>${items.map(x=>`<div class="v25Action"><b>${String(x.day).padStart(2,'0')}</b><span>${esc(x.name)}<small>${x.type}</small></span><strong>${PLN(x.amount)}</strong></div>`).join('')||'<p class="muted">Wszystko wygląda na opłacone.</p>'}</div>`}
function renderBusiness(){let h=G('businessPlusBody');if(!h)return,y=S.selectedYear,rows=Array.from({length:12},(_,m)=>company(y,m)),tot=rows.reduce((a,r)=>({rev:a.rev+r.rev,cost:a.cost+r.cost,vat:a.vat+r.vat,zus:a.zus+r.zus+r.health,tax:a.tax+r.tax,profit:a.profit+r.profit}),{rev:0,cost:0,vat:0,zus:0,tax:0,profit:0});h.innerHTML=`${kpis([['PRZYCHÓD',PLN(tot.rev)],['KOSZTY',PLN(tot.cost)],['ZUS + ZDROWOTNA',PLN(tot.zus)],['PODATKI + VAT',PLN(tot.tax+tot.vat)],['REALNIE ZOSTAJE',PLN(tot.profit),tot.profit<0?'red':'green']])}<div class="card"><div class="title">Firma miesiąc po miesiącu <button class="btn" onclick="show('company')">Edytuj dane podstawowe ›</button></div><div class="v25Table"><div class="head"><b>Miesiąc</b><b>Przychód</b><b>Koszty</b><b>Daniny</b><b>Zostaje</b></div>${rows.map((r,i)=>`<div><span>${FULL[i]}</span><span>${PLN(r.rev)}</span><span>${PLN(r.cost)}</span><span>${PLN(r.zus+r.health+r.tax+r.vat)}</span><b class="${r.profit<0?'red':'green'}">${PLN(r.profit)}</b></div>`).join('')}</div></div>`}
function renderAll(){ensure();renderMonthly();renderBudget();renderWealth();renderGoals();renderCalendar();renderEmergency();renderScenario();renderDebt();renderActions();renderBusiness()}
window.v25ShiftMonth=function(d){S.finance.selectedMonth=addMonth(S.finance.selectedMonth||nowKey(),d);S.finance.analysisMonth=S.finance.selectedMonth;save();renderAll()};
window.v25ShiftAnalysis=function(d){S.finance.analysisMonth=addMonth(S.finance.analysisMonth||nowKey(),d);save();renderAll()};
window.v25SaveEmergency=function(){S.finance.emergencySavings=N(G('v25EmergencySavings')?.value);S.finance.emergencyTargetMonths=Math.max(1,N(G('v25EmergencyMonths')?.value)||6);save();renderAll()};
window.v25SaveScenario=function(){S.finance.scenario={salaryPct:N(G('v25ScSalary')?.value),companyPct:N(G('v25ScCompany')?.value),expensePct:N(G('v25ScExpense')?.value),extraDebt:N(G('v25ScDebt')?.value)};save();renderAll()};
function centsLoans(){document.querySelectorAll('#loanList input[type="number"]').forEach(x=>{if(['rate'].some(k=>(x.id||'').toLowerCase().includes(k)))return;x.step='0.01';if(x.value!==''&&!Number.isNaN(+x.value))x.value=(+x.value).toFixed(2)});}
function boot(){try{renderAll();centsLoans()}catch(e){console.error('v25',e)}}
document.addEventListener('click',()=>setTimeout(boot,0));
window.addEventListener('load',boot);
setTimeout(boot,300);
})();