/* Moje Finanse 2.6 — prognoza wizualnie oddzielona od danych rzeczywistych */
(function(){
const n=v=>+v||0;
const fmt=v=>new Intl.NumberFormat('pl-PL',{style:'currency',currency:'PLN',minimumFractionDigits:2,maximumFractionDigits:2}).format(n(v));
function actualLoanPaid(year){return (S.loans||[]).reduce((sum,l)=>sum+(l.history||[]).reduce((a,h)=>{if(!(h.month||'').startsWith(String(year)+'-'))return a;let reg=0;if(typeof h.paid==='boolean')reg=h.paid?n(h.regularPaid||l.payment):0;else reg=n(h.regularPaid!=null?h.regularPaid:h.paid);let ex=h.isOverpayment===false?0:n(h.extra);return a+reg+ex},0),0)}
function forecastLoanLeft(year){let total=0;(S.loans||[]).forEach(l=>{for(let m=0;m<12;m++){let k=year+'-'+String(m+1).padStart(2,'0'),base=(l.asOfDate||TODAY).slice(0,7);if(k<base)continue;let h=(l.history||[]).find(x=>x.month===k);if(h)continue;total+=n(l.payment)+n(l.extraMonthly)}});return total}
function snapshot(){let p=sal(),c=comp(),yr=Y(),sAct=0,sFc=0,gAct=0,gFc=0,crAct=0,crFc=0,ccAct=0,ccFc=0,cvAct=0,cvFc=0;for(let i=0;i<12;i++){let sr=yr.salary[i]||{},sa=n(sr.net)+n(sr.bonus)>0;if(sa){sAct+=n(p.rows[i].total);gAct+=n(p.rows[i].g)}else{sFc+=n(p.rows[i].total);gFc+=n(p.rows[i].g)}let rr=yr.company[i]||{},ca=!!(n(rr.revenue)||n(rr.costs)||n(rr.vat)||n(rr.vatOut)||n(rr.vatIn));if(ca){crAct+=n(c.rows[i].revenue);ccAct+=n(c.rows[i].costs);cvAct+=n(c.rows[i].vat)}else{crFc+=n(c.rows[i].revenue);ccFc+=n(c.rows[i].costs);cvFc+=n(c.rows[i].vat)}}let cpAct=crAct-ccAct,cpFc=crFc-ccFc,loanAct=actualLoanPaid(S.selectedYear),loanFc=forecastLoanLeft(S.selectedYear),freeAct=sAct+cpAct-cvAct-loanAct,freeFc=freeAct+sFc+cpFc-cvFc-loanFc;return{p,c,yr,sAct,sFc,gAct,gFc,crAct,crFc,ccAct,ccFc,cvAct,cvFc,cpAct,cpFc,loanAct,loanFc,freeAct,freeFc}}
function hint(el,text){if(!el)return;let old=el.parentElement.querySelector('.forecastHint26');if(old)old.remove();let s=document.createElement('span');s.className='forecastHint26';s.textContent=text;el.insertAdjacentElement('afterend',s)}
function apply(){if(!window.S||!document.getElementById('home'))return;let d=snapshot(),hero=document.querySelector('#home .hero');if(hero){let lab=hero.querySelector('small');if(lab)lab.textContent='WOLNA GOTÓWKA — TYLKO DANE WPISANE';let v=document.getElementById('freeYear');if(v)v.textContent=fmt(d.freeAct);let sub=document.getElementById('avgNet');if(sub){sub.className='forecastLine26';sub.textContent='prognoza końca roku ≈ '+fmt(d.freeFc)+' • nie jest doliczana do wyniku powyżej'}}
let net=document.getElementById('netTile'),gross=document.getElementById('grossTile'),company=document.getElementById('companyTile'),loan=document.getElementById('loanTile');if(net){net.textContent=fmt(d.sAct);net.previousElementSibling.textContent='ETAT NETTO — WPISANE';hint(net,'prognoza +' + fmt(d.sFc)+' → '+fmt(d.sAct+d.sFc))}if(gross){gross.textContent=fmt(d.gAct);gross.previousElementSibling.textContent='ETAT BRUTTO — WPISANE';hint(gross,'prognoza +' + fmt(d.gFc)+' → '+fmt(d.gAct+d.gFc))}if(company){company.textContent=fmt(d.cpAct);company.previousElementSibling.textContent='FIRMA — WPISANE';hint(company,'prognoza '+(d.cpFc>=0?'+':'')+fmt(d.cpFc)+' → '+fmt(d.cpAct+d.cpFc))}if(loan){loan.textContent=fmt(d.loanAct);loan.previousElementSibling.textContent='KREDYTY — FAKTYCZNIE WPŁACONE';hint(loan,'planowane do końca roku +'+fmt(d.loanFc))}
let rev=document.getElementById('companyRevenueHome'),cost=document.getElementById('companyCostsHome'),prof=document.getElementById('companyProfitHome'),vat=document.getElementById('companyVatHome');if(rev)rev.textContent=fmt(d.crAct);if(cost)cost.textContent=fmt(d.ccAct);if(prof)prof.textContent=fmt(d.cpAct);if(vat)vat.textContent=fmt(d.cvAct);
let total=document.getElementById('allIncomeTotal');if(total){total.textContent=fmt(d.sAct+d.cpAct);hint(total,'prognoza razem '+fmt(d.sAct+d.sFc+d.cpAct+d.cpFc))}
renderBars26(d);renderEarnings26(d)}
function renderBars26(d){let h=document.getElementById('homeBars');if(!h)return;let vals=[['BRUTTO',d.gAct,d.gFc,'barGross'],['NETTO',d.sAct,d.sFc,'barNet'],['FIRMA',Math.max(0,d.cpAct),Math.max(0,d.cpFc),'barCompany'],['KREDYTY',d.loanAct,d.loanFc,'barLoans']],mx=Math.max(1,...vals.map(x=>x[1]+x[2]));h.innerHTML=vals.map(x=>{let ah=Math.max(x[1]?4:0,x[1]/mx*140),fh=Math.max(x[2]?3:0,x[2]/mx*140);return `<div class="kpiCol kpi26"><div class="kpiBarStack26"><div class="kpiForecast26 ${x[3]}" style="height:${fh}px"></div><div class="kpiActual26 ${x[3]}" style="height:${ah}px"></div></div><b>${fmt(x[1])}</b><small>${x[0]}</small><span>prognoza +${fmt(x[2])}</span></div>`}).join('')}
function renderEarnings26(d){let h=document.getElementById('earningsChart');if(!h)return;let vals=d.p.rows.map((r,i)=>Math.max(0,n(r.total))+Math.max(0,n(d.c.rows[i].revenue)-n(d.c.rows[i].costs))),mx=Math.max(1,...vals);h.innerHTML=M.map((m,i)=>{let sa=!!(n(d.yr.salary[i]?.net)+n(d.yr.salary[i]?.bonus)),ca=!!(n(d.yr.company[i]?.revenue)||n(d.yr.company[i]?.costs)||n(d.yr.company[i]?.vat)||n(d.yr.company[i]?.vatOut)||n(d.yr.company[i]?.vatIn)),s=Math.max(0,n(d.p.rows[i].total)),c=Math.max(0,n(d.c.rows[i].revenue)-n(d.c.rows[i].costs)),k=165/mx,forecast=!(sa||ca);return `<div class="earnCol ${forecast?'forecastMonth26':'actualMonth26'}"><div class="earnStack"><div class="earnCompany" style="height:${c*k}px"></div><div class="earnSalary" style="height:${s*k}px"></div></div><span class="earnLabel">${m}</span>${forecast?'<em>prog.</em>':''}</div>`}).join('');let lg=h.parentElement.querySelector('.legend');if(lg)lg.innerHTML='<span><i class="dot greenDot"></i> rzeczywiste</span><span><i class="forecastLegend26"></i> prognoza — przerywana / jaśniejsza</span>'}
const oldRender=window.render;if(typeof oldRender==='function'){window.render=function(){oldRender();setTimeout(apply,0)}}
window.addEventListener('load',()=>setTimeout(apply,30));setTimeout(apply,400);
})();