/* Moje Finanse 3.1 — stabilizacja wersji, pulpitu i kalendarza */
(function(){
const VERSION='3.1.0';
const G=id=>document.getElementById(id),N=v=>+v||0;
const PLN=v=>new Intl.NumberFormat('pl-PL',{style:'currency',currency:'PLN',minimumFractionDigits:2,maximumFractionDigits:2}).format(N(v));
const FULL=['Styczeń','Luty','Marzec','Kwiecień','Maj','Czerwiec','Lipiec','Sierpień','Wrzesień','Październik','Listopad','Grudzień'];
const key=(y,m)=>`${y}-${String(m+1).padStart(2,'0')}`;
const parse=k=>{let [y,m]=String(k||'').split('-').map(Number);return{y:y||new Date().getFullYear(),m:(m||1)-1}};
const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
function setVersion(){document.title='Moje Finanse '+VERSION;let h=document.querySelector('.top small');if(h)h.innerHTML=`<span id="headerYear">${window.S?.selectedYear||''}</span> • wersja ${VERSION}`;document.documentElement.dataset.appVersion=VERSION}
function ensure(){if(!window.S)return false;S.finance||={};S.finance.expenses||=[];S.finance.calendarEvents||=[];if(!S.finance.selectedMonth)S.finance.selectedMonth=key(S.selectedYear||new Date().getFullYear(),new Date().getMonth());if(!S.finance.analysisMonth)S.finance.analysisMonth=S.finance.selectedMonth;return true}
function salary(y,m){try{let old=S.selectedYear;S.selectedYear=y;Y();let r=sal().rows[m]||{};S.selectedYear=old;Y();return{net:N(r.total),gross:N(r.g),pe:N(r.pe),er:N(r.er),actual:!!r.actual}}catch(e){let r=S.years?.[String(y)]?.salary?.[m]||{},net=N(r.net)+N(r.bonus);return{net,gross:N(r.gross),pe:0,er:0,actual:net>0}}}
function company(y,m){let r=S.years?.[String(y)]?.company?.[m]||{},rev=N(r.revenue),cost=N(r.costs),zus=N(r.zus),health=N(r.health),tax=N(r.tax),vat=(N(r.vatOut)||N(r.vatIn))?N(r.vatOut)-N(r.vatIn):N(r.vat);let actual=!!(rev||cost||zus||health||tax||vat);return{profit:rev-cost-zus-health-tax-vat,actual}}
function expenseRows(k){return (S.finance?.expenses||[]).filter(e=>e.active!==false&&(!e.from||k>=e.from)&&(!e.to||k<=e.to))}
function expenseTotal(k){return expenseRows(k).reduce((a,e)=>a+N(e.amount),0)}
function loanSpend(k){return (S.loans||[]).reduce((a,l)=>{let h=(l.history||[]).find(x=>x.month===k);if(h){let reg=typeof h.paid==='boolean'?(h.paid?N(h.regularPaid||l.payment):0):N(h.regularPaid!=null?h.regularPaid:h.paid),ex=h.isOverpayment===false?0:N(h.extra);return a+reg+ex}if(k<(l.asOfDate||'0000-00-00').slice(0,7))return a;return a+N(l.payment)+N(l.extraMonthly)},0)}
function renderMonthly(){if(!ensure())return;let host=G('monthlyBody');if(!host)return;let k=S.finance.selectedMonth,{y,m}=parse(k),s=salary(y,m),c=company(y,m),e=expenseTotal(k),lo=loanSpend(k),fact=(s.actual?s.net:0)+(c.actual?Math.max(0,c.profit):0),forecast=(s.actual?0:s.net)+(c.actual?0:Math.max(0,c.profit)),free=fact-e-lo,potential=fact+forecast-e-lo;
host.innerHTML=`<div class="card miniNav"><button class="btn" onclick="shiftMonth31(-1)">‹</button><b>${FULL[m]} ${y}</b><button class="btn" onclick="shiftMonth31(1)">›</button></div><div class="v25Kpis"><div><small>DOCHODY — FAKT</small><b class="green">${PLN(fact)}</b></div><div><small>WYDATKI</small><b>${PLN(e)}</b></div><div><small>RATY + NADPŁATY</small><b>${PLN(lo)}</b></div><div><small>WOLNA GOTÓWKA — FAKT</small><b class="${free<0?'red':'green'}">${PLN(free)}</b></div></div><div class="card"><div class="title">Przepływ miesiąca</div><div class="v25Flow"><div><span>Etat ${s.actual?'• fakt':'• prognoza'}</span><b>${PLN(s.net)}</b></div><div><span>Firma ${c.actual?'• fakt':'• prognoza'}</span><b>${PLN(c.profit)}</b></div><div class="minus"><span>Wydatki stałe</span><b>− ${PLN(e)}</b></div><div class="minus"><span>Kredyty</span><b>− ${PLN(lo)}</b></div><div class="result"><span>Zostaje z danych wpisanych</span><b>${PLN(free)}</b></div></div></div>${forecast?`<div class="card" style="border-style:dashed"><div class="title">Prognoza — osobno</div><div class="row"><span>Dodatkowy prognozowany dochód</span><b>+ ${PLN(forecast)}</b></div><div class="row"><span>Potencjalnie zostanie</span><b>${PLN(potential)}</b></div><p class="muted">Prognoza nie zwiększa głównego wyniku faktycznego.</p></div>`:''}<div class="card"><div class="title">PPK w miesiącu</div><div class="row"><span>PPK Ty</span><b>${PLN(s.pe)}</b></div><div class="row"><span>PPK firma</span><b>${PLN(s.er)}</b></div></div>`}
function renderCalendar(){if(!ensure())return;let host=G('calendarBody');if(!host)return;let k=S.finance.analysisMonth,{y,m}=parse(k),days=new Date(y,m+1,0).getDate(),off=(new Date(y,m,1).getDay()+6)%7,events={};let add=(d,label,kind,amount)=>{d=Math.max(1,Math.min(days,N(d)||1));(events[d]||=[]).push({label,kind,amount})};expenseRows(k).forEach(e=>add(e.day,e.name,'expense',e.amount));(S.loans||[]).forEach(l=>{if(k>=(l.asOfDate||'0000-00-00').slice(0,7))add(l.dueDay,l.name,'loan',l.payment)});(S.finance.calendarEvents||[]).filter(e=>e.month===k).forEach(e=>add(e.day,e.name,'custom',e.amount));let cells='';for(let i=0;i<off;i++)cells+='<div class="calDay empty"></div>';for(let d=1;d<=days;d++)cells+=`<div class="calDay"><b>${d}</b>${(events[d]||[]).map(e=>`<span class="calEvent ${e.kind}">${esc(e.label)}${N(e.amount)?' • '+PLN(e.amount):''}</span>`).join('')}</div>`;host.innerHTML=`<div class="card"><div class="calendarHead"><button class="btn" onclick="shiftCalendar31(-1)">‹</button><b>${FULL[m]} ${y}</b><button class="btn" onclick="shiftCalendar31(1)">›</button><button class="btn primary" onclick="window.calendarEventModal21?.()">＋ Wydarzenie</button></div><div class="calWeek"><span>Pn</span><span>Wt</span><span>Śr</span><span>Cz</span><span>Pt</span><span>So</span><span>Nd</span></div><div class="calendarGrid">${cells}</div></div>`}
window.shiftMonth31=function(d){ensure();let {y,m}=parse(S.finance.selectedMonth),x=new Date(y,m+d,1,12);S.finance.selectedMonth=key(x.getFullYear(),x.getMonth());save();renderMonthly()};
window.shiftCalendar31=function(d){ensure();let {y,m}=parse(S.finance.analysisMonth),x=new Date(y,m+d,1,12);S.finance.analysisMonth=key(x.getFullYear(),x.getMonth());save();renderCalendar()};
window.renderMonthly31=renderMonthly;window.renderCalendar31=renderCalendar;
const oldShow=window.show;if(typeof oldShow==='function')window.show=function(v){oldShow(v);setVersion();if(v==='monthly')setTimeout(renderMonthly,0);if(v==='calendar')setTimeout(renderCalendar,0)};
const oldRender=window.render;if(typeof oldRender==='function')window.render=function(){oldRender();setVersion();renderMonthly();renderCalendar()};
document.addEventListener('click',e=>{if(e.target.closest('.nav,.moduleLinks,.top'))setTimeout(setVersion,0)});
setTimeout(()=>{setVersion();renderMonthly();renderCalendar()},250);setTimeout(setVersion,900);
})();