/* Moje Finanse 3.3 — stabilne moduły: kredyty, wydatki, kalendarz, scenariusze, zadłużenie */
(function(){
const G=id=>document.getElementById(id),N=v=>+v||0;
const PLN=v=>new Intl.NumberFormat('pl-PL',{style:'currency',currency:'PLN',minimumFractionDigits:2,maximumFractionDigits:2}).format(N(v));
const FULL=['Styczeń','Luty','Marzec','Kwiecień','Maj','Czerwiec','Lipiec','Sierpień','Wrzesień','Październik','Listopad','Grudzień'];
const nowKey=()=>typeof TODAY==='string'?TODAY.slice(0,7):new Date().toISOString().slice(0,7);
const key=(y,m)=>`${y}-${String(m+1).padStart(2,'0')}`;
const parse=k=>{let [y,m]=String(k||nowKey()).split('-').map(Number);return{y,m:(m||1)-1}};
const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
function ensure(){if(typeof S==='undefined')return false;S.finance||={};S.finance.expenses||=[];S.finance.calendarEvents||=[];S.finance.scenario||={salaryPct:0,companyPct:0,expensePct:0,extraDebt:0};S.finance.informalDebts||=[];S.finance.analysisMonth||=S.finance.selectedMonth||nowKey();return true}
function expRows(k){return (S.finance.expenses||[]).filter(e=>e.active!==false&&(!e.from||k>=e.from)&&(!e.to||k<=e.to))}
function expTotal(k){return expRows(k).reduce((a,e)=>a+N(e.amount),0)}
function salary(y,m){try{let old=S.selectedYear;S.selectedYear=y;Y();let r=sal().rows[m]||{};S.selectedYear=old;Y();return{net:N(r.total),gross:N(r.g),actual:!!r.actual}}catch{let r=S.years?.[String(y)]?.salary?.[m]||{};let net=N(r.net)+N(r.bonus);return{net,gross:N(r.gross),actual:net>0}}}
function company(y,m){let r=S.years?.[String(y)]?.company?.[m]||{},rev=N(r.revenue),cost=N(r.costs),zus=N(r.zus),health=N(r.health),tax=N(r.tax),vat=(N(r.vatOut)||N(r.vatIn))?N(r.vatOut)-N(r.vatIn):N(r.vat);return{profit:rev-cost-zus-health-tax-vat,actual:!!(rev||cost||zus||health||tax||vat)}}
function loanSpend(k){return (S.loans||[]).reduce((a,l)=>{let h=(l.history||[]).find(x=>x.month===k);if(h){let reg=typeof h.paid==='boolean'?(h.paid?N(h.regularPaid||l.payment):0):N(h.regularPaid!=null?h.regularPaid:h.paid),ex=h.isOverpayment===false?0:N(h.extra);return a+reg+ex}if(k<(l.asOfDate||'0000-00-00').slice(0,7))return a;return a+N(l.payment)+N(l.extraMonthly)},0)}
function balance(l){try{return N(loanPoint(l).balance)}catch{return N(l.balance)}}
function informalRemaining(d){let paid=(d.payments||[]).reduce((a,p)=>a+N(p.amount),0);return Math.max(0,N(d.amount)-paid)}
function informalPaid(d){return Math.max(0,N(d.amount)-informalRemaining(d))}
function flow(k){let {y,m}=parse(k),s=salary(y,m),c=company(y,m),e=expTotal(k),lo=loanSpend(k),income=(s.actual?s.net:0)+(c.actual?Math.max(0,c.profit):0);return{k,y,m,s,c,e,lo,income,free:income-e-lo}}
function addMonth(k,d){let {y,m}=parse(k),x=new Date(y,m+d,1,12);return key(x.getFullYear(),x.getMonth())}
function nav(k,fn){let {y,m}=parse(k);return `<div class="card miniNav"><button class="btn" onclick="${fn}(-1)">‹</button><b>${FULL[m]} ${y}</b><button class="btn" onclick="${fn}(1)">›</button></div>`}
function renderBudget(){if(!ensure())return;let h=G('budgetBody');if(!h)return;let k=S.finance.analysisMonth||nowKey(),rows=expRows(k),total=expTotal(k);h.innerHTML=`${nav(k,'shiftFinanceAnalysis33')}<div class="grid"><div class="tile"><small>STAŁE / MIES.</small><b>${PLN(total)}</b></div><div class="tile"><small>STAŁE / ROK</small><b>${PLN(total*12)}</b></div><div class="tile"><small>POZYCJI</small><b>${rows.length}</b></div></div><div class="card"><div class="title">Wydatki stałe <button class="btn primary" onclick="window.expenseModal20?.()">＋ Dodaj</button></div>${rows.length?rows.map(e=>`<div class="budgetRow"><div><b>${esc(e.name)}</b><small>${esc(e.category||'Inne')} • dzień ${e.day||'—'}${e.from?' • od '+e.from:''}${e.to?' • do '+e.to:''}</small></div><b>${PLN(e.amount)}/m</b><button class="btn danger" onclick="window.removeExpense20?.(${(S.finance.expenses||[]).indexOf(e)})">Usuń</button></div>`).join(''):'<p class="muted">Brak wydatków stałych dla tego miesiąca. Dodaj pierwszą pozycję.</p>'}</div>`}
function renderCalendar(){if(!ensure())return;let h=G('calendarBody');if(!h)return;let k=S.finance.analysisMonth||nowKey(),{y,m}=parse(k),days=new Date(y,m+1,0).getDate(),off=(new Date(y,m,1).getDay()+6)%7,E={};let add=(d,t,a,c)=>{d=Math.max(1,Math.min(days,N(d)||1));(E[d]||=[]).push({t,a,c})};expRows(k).forEach(e=>add(e.day,e.name,e.amount,'expense'));(S.loans||[]).forEach(l=>{if(k>=(l.asOfDate||'0000-00-00').slice(0,7))add(l.dueDay,l.name,l.payment,'loan')});(S.finance.calendarEvents||[]).filter(e=>e.month===k).forEach(e=>add(e.day,e.name,e.amount,'custom'));let cells='';for(let i=0;i<off;i++)cells+='<div class="calDay empty"></div>';for(let d=1;d<=days;d++)cells+=`<div class="calDay"><b>${d}</b>${(E[d]||[]).map(e=>`<span class="calEvent ${e.c}">${esc(e.t)}${N(e.a)?' • '+PLN(e.a):''}</span>`).join('')}</div>`;h.innerHTML=`${nav(k,'shiftFinanceAnalysis33')}<div class="card"><div class="title">Terminy <button class="btn primary" onclick="window.calendarEventModal21?.()">＋ Wydarzenie</button></div><div class="calWeek"><span>Pn</span><span>Wt</span><span>Śr</span><span>Cz</span><span>Pt</span><span>So</span><span>Nd</span></div><div class="calendarGrid">${cells}</div></div>`}
function renderScenario(){if(!ensure())return;let h=G('scenarioBody');if(!h)return;let sc=S.finance.scenario,start=S.finance.analysisMonth||nowKey(),rows=[];for(let i=0;i<12;i++){let k=addMonth(start,i),d=flow(k),base=d.free,alt=(d.s.actual?d.s.net:0)*(1+N(sc.salaryPct)/100)+(d.c.actual?Math.max(0,d.c.profit):0)*(1+N(sc.companyPct)/100)-d.e*(1+N(sc.expensePct)/100)-d.lo-N(sc.extraDebt);rows.push({k,base,alt})}let b=rows.reduce((a,r)=>a+r.base,0),a=rows.reduce((s,r)=>s+r.alt,0);h.innerHTML=`<div class="grid"><div class="tile"><small>BAZA 12 MIES.</small><b>${PLN(b)}</b></div><div class="tile"><small>SCENARIUSZ</small><b class="${a>=b?'green':'red'}">${PLN(a)}</b></div><div class="tile"><small>RÓŻNICA</small><b class="${a>=b?'green':'red'}">${PLN(a-b)}</b></div></div><div class="card"><div class="form"><label>Zmiana etatu %<input id="scSalary33" type="number" step="0.1" value="${N(sc.salaryPct)}"></label><label>Zmiana firmy %<input id="scCompany33" type="number" step="0.1" value="${N(sc.companyPct)}"></label><label>Zmiana kosztów %<input id="scExpense33" type="number" step="0.1" value="${N(sc.expensePct)}"></label><label>Dodatkowa nadpłata / mies.<input id="scDebt33" type="number" step="0.01" value="${N(sc.extraDebt)}"></label></div><button class="btn primary" onclick="saveScenario33()">Przelicz</button></div><div class="card"><div class="title">12 miesięcy</div>${rows.map(r=>`<div class="v25Row"><span>${r.k}</span><span>bazowo <b>${PLN(r.base)}</b> → scenariusz <b class="${r.alt>=r.base?'green':'red'}">${PLN(r.alt)}</b></span></div>`).join('')}</div>`}
function informalHtml(){let ds=S.finance.informalDebts||[],total=ds.reduce((a,d)=>a+informalRemaining(d),0);return `<div class="card"><div class="title">Do oddania — bez odsetek i bez terminu <button class="btn primary" onclick="informalDebtModal33()">＋ Dodaj</button></div><p class="muted">Dla pieniędzy, które trzeba oddać kiedy będziesz mógł. Nie tworzy rat ani terminu spłaty i nie trafia do kalendarza.</p><div class="row"><span>Łącznie pozostało</span><b>${PLN(total)}</b></div>${ds.length?ds.map((d,i)=>{let rem=informalRemaining(d),paid=informalPaid(d),p=N(d.amount)?Math.min(100,paid/N(d.amount)*100):0;return `<div class="card" style="margin-top:10px"><div class="title"><span>${esc(d.name||'Zobowiązanie')}</span><span>${PLN(rem)} pozostało</span></div>${d.note?`<p class="muted">${esc(d.note)}</p>`:''}<div class="progress"><i style="width:${p}%"></i></div><div class="row"><span>Oddano ${PLN(paid)} z ${PLN(d.amount)}</span><b>${p.toFixed(1)}%</b></div><div class="actions"><button class="btn primary" onclick="informalPaymentModal33(${i})">＋ Zapisz oddanie</button><button class="btn danger" onclick="removeInformalDebt33(${i})">Usuń</button></div>${(d.payments||[]).length?`<div class="ledger">${[...(d.payments||[])].reverse().map(p=>`<div class="ledgerRow"><div><b>${esc(p.date||'')}</b><small>${PLN(p.amount)}${p.note?' • '+esc(p.note):''}</small></div></div>`).join('')}</div>`:''}</div>`}).join(''):'<p class="muted">Nie masz jeszcze takich zobowiązań.</p>'}</div>`}
function renderDebt(){if(!ensure())return;let h=G('debtBody');if(!h)return;let loans=S.loans||[],k=S.finance.analysisMonth||nowKey(),d=flow(k),bankDebt=loans.reduce((a,l)=>a+balance(l),0),informal=(S.finance.informalDebts||[]).reduce((a,x)=>a+informalRemaining(x),0),debt=bankDebt+informal,payment=loans.reduce((a,l)=>a+N(l.payment)+N(l.extraMonthly),0),ratio=d.income>0?payment/d.income*100:0,weighted=bankDebt?loans.reduce((a,l)=>a+balance(l)*N(l.rate),0)/bankDebt:0;let avalanche=[...loans].sort((a,b)=>N(b.rate)-N(a.rate)),snowball=[...loans].sort((a,b)=>balance(a)-balance(b));h.innerHTML=`<div class="grid"><div class="tile"><small>ŁĄCZNE ZADŁUŻENIE</small><b>${PLN(debt)}</b><span>kredyty ${PLN(bankDebt)} + bezterminowe ${PLN(informal)}</span></div><div class="tile"><small>RATY / MIES.</small><b>${PLN(payment)}</b></div><div class="tile"><small>RATY / DOCHÓD</small><b>${ratio.toFixed(1)}%</b></div><div class="tile"><small>ŚR. OPROCENTOWANIE KREDYTÓW</small><b>${weighted.toFixed(2)}%</b></div></div>${informalHtml()}<div class="two"><div class="card"><div class="title">Avalanche — najpierw najwyższe oprocentowanie</div>${avalanche.length?avalanche.map((l,i)=>`<div class="v25Row"><span>${i+1}. ${esc(l.name)}<small>${N(l.rate).toFixed(2)}%</small></span><b>${PLN(balance(l))}</b></div>`).join(''):'<p class="muted">Brak kredytów.</p>'}</div><div class="card"><div class="title">Snowball — najpierw najmniejsze saldo</div>${snowball.length?snowball.map((l,i)=>`<div class="v25Row"><span>${i+1}. ${esc(l.name)}<small>rata ${PLN(l.payment)}</small></span><b>${PLN(balance(l))}</b></div>`).join(''):'<p class="muted">Brak kredytów.</p>'}</div></div>`}
window.informalDebtModal33=function(){if(!ensure())return;open(`<h2>Dodaj kwotę do oddania</h2><p class="muted">Bez odsetek, bez rat i bez terminu.</p><div class="form"><label>Komu / nazwa<input id="idName33" placeholder="np. Tata, znajomy"></label><label>Kwota<input id="idAmount33" type="number" step="0.01"></label><label>Notatka<input id="idNote33" placeholder="opcjonalnie"></label></div><div class="actions"><button class="btn" onclick="closeModal()">Anuluj</button><button class="btn primary" onclick="saveInformalDebt33()">Zapisz</button></div>`)};
window.saveInformalDebt33=function(){ensure();let amount=N(G('idAmount33')?.value);if(amount<=0)return alert('Podaj kwotę większą od zera.');S.finance.informalDebts.push({name:G('idName33')?.value||'Do oddania',amount,note:G('idNote33')?.value||'',payments:[]});save();closeModal();renderDebt()};
window.informalPaymentModal33=function(i){let d=S.finance.informalDebts?.[i];if(!d)return;open(`<h2>Oddanie — ${esc(d.name)}</h2><p class="muted">Pozostało ${PLN(informalRemaining(d))}</p><div class="form"><label>Data<input id="idPayDate33" type="date" value="${typeof TODAY==='string'?TODAY:new Date().toISOString().slice(0,10)}"></label><label>Kwota<input id="idPayAmount33" type="number" step="0.01"></label><label>Notatka<input id="idPayNote33" placeholder="opcjonalnie"></label></div><div class="actions"><button class="btn" onclick="closeModal()">Anuluj</button><button class="btn primary" onclick="saveInformalPayment33(${i})">Zapisz</button></div>`)};
window.saveInformalPayment33=function(i){let d=S.finance.informalDebts?.[i];if(!d)return;let amount=N(G('idPayAmount33')?.value),rem=informalRemaining(d);if(amount<=0)return alert('Podaj kwotę większą od zera.');if(amount>rem)amount=rem;d.payments||=[];d.payments.push({date:G('idPayDate33')?.value||'',amount,note:G('idPayNote33')?.value||''});save();closeModal();renderDebt()};
window.removeInformalDebt33=function(i){if(confirm('Usunąć to zobowiązanie?')){S.finance.informalDebts.splice(i,1);save();renderDebt()}};
window.shiftFinanceAnalysis33=function(d){ensure();S.finance.analysisMonth=addMonth(S.finance.analysisMonth||nowKey(),d);save();renderBudget();renderCalendar();renderScenario();renderDebt()};
window.saveScenario33=function(){ensure();S.finance.scenario={salaryPct:N(G('scSalary33')?.value),companyPct:N(G('scCompany33')?.value),expensePct:N(G('scExpense33')?.value),extraDebt:N(G('scDebt33')?.value)};save();renderScenario()};
window.openLoanFromHome33=function(i){if(!S.loans?.[i])return;S.loans[i].uiCollapsed=false;save();show('loans');setTimeout(()=>{let cards=[...document.querySelectorAll('#loanList .loan')],card=cards[i];if(card){card.scrollIntoView({behavior:'smooth',block:'start'});card.classList.add('loanFocus33');setTimeout(()=>card.classList.remove('loanFocus33'),1400)}},80)};
function wireLoanHome(){let home=G('loanHome');if(!home||home.dataset.loanLinks33)return;home.dataset.loanLinks33='1';home.addEventListener('click',e=>{let row=e.target.closest('.row');if(!row)return;let rows=[...home.querySelectorAll(':scope > .row')],i=rows.indexOf(row);if(i>=0)openLoanFromHome33(i)});home.style.cursor='pointer'}
function renderAll(){renderBudget();renderCalendar();renderScenario();renderDebt();wireLoanHome()}
window.renderBudget33=renderBudget;window.renderCalendar33=renderCalendar;window.renderScenario33=renderScenario;window.renderDebt33=renderDebt;
const oldShow=window.show;if(typeof oldShow==='function')window.show=function(v){oldShow(v);if(v==='budget')setTimeout(renderBudget,0);if(v==='calendar')setTimeout(renderCalendar,0);if(v==='scenario')setTimeout(renderScenario,0);if(v==='debt')setTimeout(renderDebt,0);if(v==='home')setTimeout(wireLoanHome,0)};
const oldRender=window.render;if(typeof oldRender==='function')window.render=function(){oldRender();setTimeout(renderAll,0)};
setTimeout(renderAll,350);setTimeout(wireLoanHome,900);
})();