/* Moje Finanse 3.4.1 — stabilny moduł Firma+ */
(function(){
const G=id=>document.getElementById(id),N=v=>+v||0;
const PLN=v=>new Intl.NumberFormat('pl-PL',{style:'currency',currency:'PLN',minimumFractionDigits:2,maximumFractionDigits:2}).format(N(v));
const FULL=['Styczeń','Luty','Marzec','Kwiecień','Maj','Czerwiec','Lipiec','Sierpień','Wrzesień','Październik','Listopad','Grudzień'];
function ensure(){if(typeof S==='undefined')return false;S.years||={};if(!S.years[String(S.selectedYear)]&&typeof Y==='function')Y();return true}
function rowFor(y,i){let yr=S.years?.[String(y)];if(!yr&&typeof Y==='function'){let old=S.selectedYear;S.selectedYear=y;yr=Y();S.selectedYear=old}return yr?.company?.[i]||{}}
function calc(r){let revenue=N(r.revenue),costs=N(r.costs),vatOut=N(r.vatOut),vatIn=N(r.vatIn),vatLegacy=N(r.vat),zus=N(r.zus),health=N(r.health),tax=N(r.tax),vat=(vatOut||vatIn)?vatOut-vatIn:vatLegacy,profit=revenue-costs-zus-health-tax-vat;return{revenue,costs,vatOut,vatIn,zus,health,tax,vat,profit}}
function renderBusinessPlus35(){if(!ensure())return;let host=G('businessPlusBody');if(!host)return;let y=S.selectedYear,rows=Array.from({length:12},(_,i)=>rowFor(y,i)),sum=rows.map(calc).reduce((a,r)=>{a.revenue+=r.revenue;a.costs+=r.costs;a.vat+=r.vat;a.zus+=r.zus;a.health+=r.health;a.tax+=r.tax;a.profit+=r.profit;return a},{revenue:0,costs:0,vat:0,zus:0,health:0,tax:0,profit:0});host.innerHTML=`<div class="sectionHead"><div class="yearNav"><button class="btn" onclick="changeBusinessYear35(-1)">‹</button><b>${y}</b><button class="btn" onclick="changeBusinessYear35(1)">›</button></div></div><div class="grid"><div class="tile"><small>PRZYCHÓD</small><b>${PLN(sum.revenue)}</b></div><div class="tile"><small>KOSZTY</small><b>${PLN(sum.costs)}</b></div><div class="tile"><small>VAT SALDO</small><b>${PLN(sum.vat)}</b></div><div class="tile"><small>REALNIE ZOSTAJE</small><b class="${sum.profit<0?'red':'green'}">${PLN(sum.profit)}</b></div></div><div class="card"><div class="title">Firma+ — miesiąc po miesiącu</div><p class="muted">Przychód i koszty netto, VAT, ZUS, zdrowotna i podatek. Wynik „realnie zostaje” jest liczony po wszystkich wpisanych obciążeniach.</p><div class="businessGrid">${rows.map((r,i)=>{let c=calc(r);return `<div class="bizMonth"><div class="mh"><b>${FULL[i]}</b><span class="status ${c.revenue||c.costs||c.vat||c.zus||c.health||c.tax?'actual':''}">${c.revenue||c.costs||c.vat||c.zus||c.health||c.tax?'wpisane':'puste'}</span></div><label>Przychód netto<input type="number" step="0.01" id="bpRev${i}" value="${r.revenue??''}"></label><label>Koszty netto<input type="number" step="0.01" id="bpCost${i}" value="${r.costs??''}"></label><label>VAT należny<input type="number" step="0.01" id="bpVatOut${i}" value="${r.vatOut??''}"></label><label>VAT naliczony<input type="number" step="0.01" id="bpVatIn${i}" value="${r.vatIn??''}"></label><label>ZUS społeczne<input type="number" step="0.01" id="bpZus${i}" value="${r.zus??''}"></label><label>Składka zdrowotna<input type="number" step="0.01" id="bpHealth${i}" value="${r.health??''}"></label><label>Podatek dochodowy<input type="number" step="0.01" id="bpTax${i}" value="${r.tax??''}"></label><div class="bizResult"><small>REALNIE ZOSTAJE</small><b class="${c.profit<0?'red':'green'}">${PLN(c.profit)}</b></div><button class="btn primary" onclick="saveBusinessMonth35(${i})">Zapisz ${FULL[i]}</button></div>`}).join('')}</div></div>`}
window.saveBusinessMonth35=function(i){if(!ensure())return;let yr=S.years[String(S.selectedYear)]||(typeof Y==='function'?Y():null);if(!yr)return;yr.company||=Array.from({length:12},()=>({}));let r=yr.company[i]||{};r.revenue=G('bpRev'+i)?.value===''?null:N(G('bpRev'+i)?.value);r.costs=G('bpCost'+i)?.value===''?null:N(G('bpCost'+i)?.value);r.vatOut=G('bpVatOut'+i)?.value===''?0:N(G('bpVatOut'+i)?.value);r.vatIn=G('bpVatIn'+i)?.value===''?0:N(G('bpVatIn'+i)?.value);r.zus=G('bpZus'+i)?.value===''?0:N(G('bpZus'+i)?.value);r.health=G('bpHealth'+i)?.value===''?0:N(G('bpHealth'+i)?.value);r.tax=G('bpTax'+i)?.value===''?0:N(G('bpTax'+i)?.value);r.vat=r.vatOut-r.vatIn;yr.company[i]=r;save();renderBusinessPlus35();if(typeof render==='function')render()};
window.changeBusinessYear35=function(d){S.selectedYear+=d;if(typeof Y==='function')Y();save();if(typeof render==='function')render();setTimeout(renderBusinessPlus35,0)};
window.renderBusinessPlus35=renderBusinessPlus35;
const oldShow=window.show;if(typeof oldShow==='function')window.show=function(v){oldShow(v);if(v==='businessplus')setTimeout(renderBusinessPlus35,0)};
const oldRender=window.render;if(typeof oldRender==='function')window.render=function(){oldRender();let v=G('businessplus');if(v?.classList.contains('active'))setTimeout(renderBusinessPlus35,0)};
setTimeout(()=>{let v=G('businessplus');if(v?.classList.contains('active'))renderBusinessPlus35()},300);
})();