/* Moje Finanse 3.8 — pełne sterowanie absencjami i integracja z prognozą */
(function(){
const G=id=>document.getElementById(id),N=v=>+v||0,R2=v=>Math.round((N(v)+Number.EPSILON)*100)/100;
const PLN=v=>new Intl.NumberFormat('pl-PL',{style:'currency',currency:'PLN',minimumFractionDigits:2,maximumFractionDigits:2}).format(N(v));
function daysInMonth(y,m){return new Date(y,m+1,0).getDate()}
function workdays(y,m){let n=0;for(let d=1;d<=daysInMonth(y,m);d++){let w=new Date(y,m,d,12).getDay();if(w!==0&&w!==6)n++}return n}
function ensure(){S.finance||={};S.finance.payrollControls||={};if(S.finance.payrollControls.healthBonusGross==null)S.finance.payrollControls.healthBonusGross=639.74;return S.finance.payrollControls}
const baseSal=typeof window.sal==='function'?window.sal:null;
const baseFg=typeof window.fg==='function'?window.fg:null;
function prevRows(y,m,count){let out=[];for(let k=1;k<=count;k++){let d=new Date(y,m-k,1,12),yy=String(d.getFullYear()),mm=d.getMonth(),r=S.years?.[yy]?.salary?.[mm];if(r&&(N(r.net)+N(r.bonus)>0))out.push({y:d.getFullYear(),m:mm,r})}return out}
function grossSnapshot(y,m){let old=S.selectedYear;try{S.selectedYear=y;if(typeof Y==='function')Y();let p=baseSal?baseSal().rows[m]:null;return N(p?.g)}catch(e){return 0}finally{S.selectedYear=old}}
function avgGrossPerDay(y,m,count){let rows=prevRows(y,m,count),sum=0,wd=0;rows.forEach(x=>{let g=grossSnapshot(x.y,x.m);if(g>0){sum+=g;wd+=N(x.r.nominalWorkDays)||workdays(x.y,x.m)}});return wd>0?sum/wd:0}
function l4Daily(y,m,pct){let rows=prevRows(y,m,12),sum=0,c=0;rows.forEach(x=>{let g=grossSnapshot(x.y,x.m);if(g>0){sum+=g;c++}});let avg=c?sum/c:0,base=avg*(1-.1371);return R2(base/30*(N(pct)||80)/100)}
function controls(y,i,row,baselineGross){let cfg=ensure(),wd=Math.max(1,N(row.nominalWorkDays)||workdays(y,i)),vac=Math.max(0,N(row.vacationDays)),sick=Math.max(0,N(row.sickDays)),sickPct=row.sickPct==null?80:N(row.sickPct),bonusGross=row.healthBonusGross==null?N(cfg.healthBonusGross)||639.74:N(row.healthBonusGross),bonusOn=row.healthBonusEligible!==false,vacDaily=avgGrossPerDay(y,i,3),sickDaily=l4Daily(y,i,sickPct),vacPay=R2(vacDaily*vac),sickPay=R2(sickDaily*sick),regularBase=Math.max(0,N(baselineGross)-(bonusOn?bonusGross:0)),regularDaily=wd?regularBase/wd:0,healthLoss=bonusOn?0:bonusGross,sickRegularLoss=R2(regularDaily*sick),modelGross=R2(Math.max(0,N(baselineGross)-healthLoss-sickRegularLoss+sickPay));return{wd,vac,sick,sickPct,bonusGross,bonusOn,vacDaily,vacPay,sickDaily,sickPay,regularDaily,healthLoss,sickRegularLoss,modelGross,delta:R2(modelGross-N(baselineGross))}}
function sal38(){if(!baseSal)return{rows:[],avg:0,count:0,last:-1};let base=baseSal(),cum=0,lastEmp=N(S.settings?.ppkEmp)||2,lastEr=N(S.settings?.ppkEr)||1.5,yr=S.years?.[String(S.selectedYear)]?.salary||[];let rows=base.rows.map((r,i)=>{let raw=yr[i]||{},actual=!!r.actual,emp=raw.ppkEmployeePct!=null?N(raw.ppkEmployeePct):lastEmp,er=raw.ppkEmployerPct!=null?N(raw.ppkEmployerPct):lastEr;if(actual){lastEmp=emp;lastEr=er;cum+=N(r.base);return{...r,payroll38:controls(S.selectedYear,i,raw,r.g)}}let ctl=controls(S.selectedYear,i,raw,r.g),p=baseFg?baseFg(ctl.modelGross,cum,emp,er,i):r,c={...r,...p,total:N(p.net),n:N(p.net),b:0,actual:false,y:cum+N(p.base),i,payroll38:ctl};cum+=N(p.base);return c});let actualRows=rows.filter(x=>x.actual);return{rows,avg:actualRows.length?actualRows.reduce((a,r)=>a+N(r.total),0)/actualRows.length:0,count:actualRows.length,last:Math.max(-1,...rows.map((r,i)=>r.actual?i:-1))}}
function render(){if(typeof S==='undefined')return;ensure();let yr=S.years?.[String(S.selectedYear)];if(!yr?.salary)return;let p=sal38(),cards=[...document.querySelectorAll('#months .month')];cards.forEach((card,i)=>{let r=yr.salary[i]||{},row=p.rows[i]||{},ctl=row.payroll38||controls(S.selectedYear,i,r,row.g||0),box=card.querySelector('.payrollCtl37');if(!box){box=document.createElement('div');box.className='payrollCtl37';card.appendChild(box)}let fact=!!row.actual;box.innerHTML=`<div class="payCtlHead37"><b>Kadry / absencje</b><span>${fact?'dane pomocnicze — faktyczne netto ma pierwszeństwo':'STERUJE PROGNOZĄ'}</span></div><div class="payCtlGrid37"><label class="check37"><input type="checkbox" id="hb37_${i}" ${ctl.bonusOn?'checked':''}> Premia zdrowotna należna</label><label>Pełna premia zdrowotna brutto<input id="hbg37_${i}" type="number" step="0.01" value="${ctl.bonusGross.toFixed(2)}"></label><label>Dni urlopu<input id="vac37_${i}" type="number" step="0.5" min="0" value="${ctl.vac}"></label><label>Dni L4<input id="sick37_${i}" type="number" step="0.5" min="0" value="${ctl.sick}"></label><label>L4 % podstawy<input id="sp37_${i}" type="number" step="1" min="0" max="100" value="${ctl.sickPct}"></label><label>Dni robocze w miesiącu<input id="wd37_${i}" type="number" step="1" min="1" value="${ctl.wd}"></label></div><div class="payCtlStats37"><span>Urlop — stawka z 3 mies.: <b>${PLN(ctl.vacDaily)}/dzień</b></span><span>Wartość urlopu ${ctl.vac} dni: <b>${PLN(ctl.vacPay)}</b></span><span>L4 — stawka ${ctl.sickPct}%: <b>${PLN(ctl.sickDaily)}/dzień</b></span><span>Wynagrodzenie L4 ${ctl.sick} dni: <b>${PLN(ctl.sickPay)}</b></span><span>Utrata zwykłego brutto przez L4: <b class="red">−${PLN(ctl.sickRegularLoss)}</b></span><span>Premia zdrowotna: <b>${ctl.bonusOn?PLN(ctl.bonusGross):'<span class="red">utracona −'+PLN(ctl.bonusGross)+'</span>'}</b></span><span>Brutto bazowe prognozy: <b>${PLN(row.g-ctl.delta)}</b></span><span>Brutto po korektach: <b>${PLN(ctl.modelGross)}</b></span><span>Wpływ absencji/premii: <b class="${ctl.delta<0?'red':'green'}">${ctl.delta>=0?'+':''}${PLN(ctl.delta)}</b></span><span>Prognozowane netto po korektach: <b class="green">${PLN(row.net)}</b></span></div><button class="btn primary" onclick="savePayroll37(${i})">Zapisz i przelicz prognozę</button><small class="muted">Urlop nie obniża stałego wynagrodzenia — stawka z 3 miesięcy jest pokazana kontrolnie. L4 zastępuje część zwykłego wynagrodzenia świadczeniem chorobowym. Premię zdrowotną 639,74 zł możesz w każdym miesiącu włączyć lub wyłączyć. Dla miesiąca z wpisanym faktycznym netto model nie nadpisuje wypłaty.</small>`;});}
window.sal=sal38;
window.savePayroll37=function(i){let r=Y().salary[i],c=ensure();r.healthBonusEligible=!!G('hb37_'+i)?.checked;r.healthBonusGross=N(G('hbg37_'+i)?.value)||639.74;r.vacationDays=Math.max(0,N(G('vac37_'+i)?.value));r.sickDays=Math.max(0,N(G('sick37_'+i)?.value));r.sickPct=Math.max(0,Math.min(100,N(G('sp37_'+i)?.value)||80));r.nominalWorkDays=Math.max(1,N(G('wd37_'+i)?.value)||workdays(S.selectedYear,i));c.healthBonusGross=r.healthBonusGross;save();if(typeof window.render==='function')window.render();setTimeout(render,0)};
const oldRender=window.render;if(typeof oldRender==='function')window.render=function(){oldRender();setTimeout(render,0)};
const oldShow=window.show;if(typeof oldShow==='function')window.show=function(v){oldShow(v);if(v==='salary')setTimeout(render,0)};
let style=document.createElement('style');style.textContent=`.payrollCtl37{margin-top:12px;padding-top:12px;border-top:1px solid #e4e9f0}.payCtlHead37{display:flex;justify-content:space-between;gap:8px;align-items:center;margin-bottom:8px}.payCtlHead37 span{font-size:11px;color:#73819a;font-weight:700}.payCtlGrid37{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px}.payCtlGrid37 label{font-size:11px;color:#68778f}.payCtlGrid37 input{width:100%;margin-top:4px}.payCtlGrid37 .check37{display:flex;align-items:center;gap:7px;background:#f6f8fb;border-radius:10px;padding:10px;color:#24324a}.payCtlGrid37 .check37 input{width:auto;margin:0}.payCtlStats37{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:6px;margin:10px 0;font-size:11px;color:#65728a}.payCtlStats37 span{background:#f7f9fc;padding:8px 10px;border-radius:9px}@media(max-width:700px){.payCtlGrid37{grid-template-columns:repeat(2,minmax(0,1fr))}.payCtlStats37{grid-template-columns:1fr}}`;document.head.appendChild(style);
setTimeout(()=>{if(typeof window.render==='function')window.render();render()},300);
})();