/* Moje Finanse 3.7 — sterowanie urlopem, L4 i premią zdrowotną */
(function(){
const G=id=>document.getElementById(id),N=v=>+v||0;
const PLN=v=>new Intl.NumberFormat('pl-PL',{style:'currency',currency:'PLN',minimumFractionDigits:2,maximumFractionDigits:2}).format(N(v));
const M3=['Sty','Lut','Mar','Kwi','Maj','Cze','Lip','Sie','Wrz','Paź','Lis','Gru'];
function daysInMonth(y,m){return new Date(y,m+1,0).getDate()}
function workdays(y,m){let n=0;for(let d=1;d<=daysInMonth(y,m);d++){let w=new Date(y,m,d,12).getDay();if(w!==0&&w!==6)n++}return n}
function ensure(){S.finance||={};S.finance.payrollControls||={healthBonusGross:639.74};return S.finance.payrollControls}
function prevRows(y,m,count){let out=[];for(let k=1;k<=count;k++){let d=new Date(y,m-k,1,12),yy=String(d.getFullYear()),mm=d.getMonth(),r=S.years?.[yy]?.salary?.[mm];if(r&&(N(r.net)+N(r.bonus)>0))out.push({y:d.getFullYear(),m:mm,r})}return out}
function grossFor(y,m,r){let old=S.selectedYear;try{S.selectedYear=y;if(typeof Y==='function')Y();let p=typeof sal==='function'?sal().rows[m]:null;return N(p?.g)}catch(e){return 0}finally{S.selectedYear=old}}
function avgGrossPerDay(y,m,count){let rows=prevRows(y,m,count),sum=0,wd=0;rows.forEach(x=>{let g=grossFor(x.y,x.m,x.r);if(g>0){sum+=g;wd+=N(x.r.nominalWorkDays)||workdays(x.y,x.m)}});return wd>0?sum/wd:0}
function l4Daily(y,m,pct){let rows=prevRows(y,m,12),sum=0,c=0;rows.forEach(x=>{let g=grossFor(x.y,x.m,x.r);if(g>0){sum+=g;c++}});let avg=c?sum/c:0,base=avg*(1-.1371);return base/30*(N(pct)||80)/100}
function render(){if(typeof S==='undefined')return;ensure();let yr=S.years?.[String(S.selectedYear)];if(!yr?.salary)return;let cards=[...document.querySelectorAll('#months .month')];cards.forEach((card,i)=>{let r=yr.salary[i]||{},box=card.querySelector('.payrollCtl37');if(!box){box=document.createElement('div');box.className='payrollCtl37';card.appendChild(box)}let y=S.selectedYear,wd=N(r.nominalWorkDays)||workdays(y,i),vac=N(r.vacationDays),sick=N(r.sickDays),sickPct=r.sickPct==null?80:N(r.sickPct),bonusGross=r.healthBonusGross==null?N(S.finance.payrollControls.healthBonusGross)||639.74:N(r.healthBonusGross),bonusOn=r.healthBonusEligible!==false,vacDaily=avgGrossPerDay(y,i,3),sickDaily=l4Daily(y,i,sickPct),vacPay=vacDaily*vac,sickPay=sickDaily*sick,fullGross=typeof sal==='function'?N(sal().rows[i]?.g):0,regularDaily=wd?Math.max(0,fullGross-(bonusOn?bonusGross:0))/wd:0,modelGross=Math.max(0,fullGross-(bonusOn?0:bonusGross)-regularDaily*(vac+sick)+vacPay+sickPay),delta=modelGross-fullGross;
box.innerHTML=`<div class="payCtlHead37"><b>Kadry / absencje</b><span>${r.actual?'':'sterowanie prognozą'}</span></div><div class="payCtlGrid37"><label class="check37"><input type="checkbox" id="hb37_${i}" ${bonusOn?'checked':''}> Premia zdrowotna należna</label><label>Pełna premia brutto<input id="hbg37_${i}" type="number" step="0.01" value="${bonusGross.toFixed(2)}"></label><label>Dni urlopu<input id="vac37_${i}" type="number" step="0.5" min="0" value="${vac}"></label><label>Dni L4<input id="sick37_${i}" type="number" step="0.5" min="0" value="${sick}"></label><label>L4 % podstawy<input id="sp37_${i}" type="number" step="1" min="0" max="100" value="${sickPct}"></label><label>Dni robocze w miesiącu<input id="wd37_${i}" type="number" step="1" min="1" value="${wd}"></label></div><div class="payCtlStats37"><span>Urlop — stawka est. z 3 mies.: <b>${PLN(vacDaily)}/dzień</b></span><span>Urlop ${vac} dni: <b>${PLN(vacPay)}</b></span><span>L4 — podstawa 12 mies., ${sickPct}%: <b>${PLN(sickDaily)}/dzień</b></span><span>L4 ${sick} dni: <b>${PLN(sickPay)}</b></span><span>Premia zdrowotna: <b>${bonusOn?PLN(bonusGross):'utracona '+PLN(bonusGross)}</b></span><span>Wpływ modelu na brutto: <b class="${delta<0?'red':'green'}">${delta>=0?'+':''}${PLN(delta)}</b></span></div><button class="btn" onclick="savePayroll37(${i})">Zapisz kadry / absencje</button><small class="muted">Urlop: estymacja na podstawie 3 poprzednich miesięcy. L4: estymacja podstawy z maks. 12 poprzednich miesięcy i domyślnie 80%. Dni robocze możesz nadpisać ręcznie.</small>`;
});}
window.savePayroll37=function(i){let r=Y().salary[i],c=ensure();r.healthBonusEligible=!!G('hb37_'+i)?.checked;r.healthBonusGross=N(G('hbg37_'+i)?.value)||639.74;r.vacationDays=Math.max(0,N(G('vac37_'+i)?.value));r.sickDays=Math.max(0,N(G('sick37_'+i)?.value));r.sickPct=Math.max(0,Math.min(100,N(G('sp37_'+i)?.value)||80));r.nominalWorkDays=Math.max(1,N(G('wd37_'+i)?.value)||workdays(S.selectedYear,i));c.healthBonusGross=r.healthBonusGross;save();render();};
const oldRender=window.render;if(typeof oldRender==='function')window.render=function(){oldRender();setTimeout(render,0)};
const oldShow=window.show;if(typeof oldShow==='function')window.show=function(v){oldShow(v);if(v==='salary')setTimeout(render,0)};
let style=document.createElement('style');style.textContent=`.payrollCtl37{margin-top:12px;padding-top:12px;border-top:1px solid #e4e9f0}.payCtlHead37{display:flex;justify-content:space-between;gap:8px;align-items:center;margin-bottom:8px}.payCtlHead37 span{font-size:11px;color:#73819a}.payCtlGrid37{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px}.payCtlGrid37 label{font-size:11px;color:#68778f}.payCtlGrid37 input{width:100%;margin-top:4px}.payCtlGrid37 .check37{display:flex;align-items:center;gap:7px;background:#f6f8fb;border-radius:10px;padding:10px;color:#24324a}.payCtlGrid37 .check37 input{width:auto;margin:0}.payCtlStats37{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:6px;margin:10px 0;font-size:11px;color:#65728a}.payCtlStats37 span{background:#f7f9fc;padding:8px 10px;border-radius:9px}@media(max-width:700px){.payCtlGrid37{grid-template-columns:repeat(2,minmax(0,1fr))}.payCtlStats37{grid-template-columns:1fr}}`;document.head.appendChild(style);
setTimeout(render,400);
})();