/* Moje Finanse 4.0 — planowanie i analityka */
(function(){
'use strict';
const G=id=>document.getElementById(id),N=v=>+v||0,PLN=v=>new Intl.NumberFormat('pl-PL',{style:'currency',currency:'PLN',minimumFractionDigits:2,maximumFractionDigits:2}).format(N(v)),esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
function ensure(){if(typeof S==='undefined')return false;S.finance||={};S.finance.products||=[];S.finance.ppk||={opening:0,returnPct:5,stateSubsidies:0};return true}
function ppkAnnualContribution(){try{let p=sal(),a=p.rows.filter(r=>r.actual),months=Math.max(1,a.length),paid=a.reduce((x,r)=>x+N(r.pe)+N(r.er),0);return paid/months*12}catch{return 0}}
function futureValue(open,annual,rate,years){let m=years*12,r=N(rate)/100/12,v=N(open);for(let i=0;i<m;i++)v=v*(1+r)+annual/12;return v}
function injectPpk(){if(!ensure())return;let host=G('wealthBody');if(!host)return;let id='mf40ppkProjection',box=G(id);if(!box){box=document.createElement('div');box.id=id;box.className='mf40-card mf40-section';host.appendChild(box)}let p=S.finance.ppk,annual=ppkAnnualContribution(),open=N(p.opening)+N(p.stateSubsidies),rate=N(p.returnPct)||5;box.innerHTML=`<div class="mf40-head"><div><h3>PPK — projekcja długoterminowa</h3><span class="mf40-sub">na podstawie aktualnego salda, średnich wpłat i założonej stopy zwrotu</span></div></div><div class="mf40-grid"><div class="mf40-kpi"><small>ROCZNE WPŁATY EST.</small><b>${PLN(annual)}</b></div><div class="mf40-kpi"><small>ZA 5 LAT</small><b>${PLN(futureValue(open,annual,rate,5))}</b></div><div class="mf40-kpi"><small>ZA 10 LAT</small><b>${PLN(futureValue(open,annual,rate,10))}</b></div><div class="mf40-kpi"><small>ZA 20 LAT</small><b>${PLN(futureValue(open,annual,rate,20))}</b></div><div class="mf40-kpi"><small>ZA 30 LAT</small><b>${PLN(futureValue(open,annual,rate,30))}</b></div></div><p class="mf40-note">To symulacja, nie gwarantowany wynik inwestycyjny. Zmiana stopy zwrotu w module Majątek aktualizuje projekcję.</p>`}
function productProfit(p){let sell=N(p.price),mat=N(p.material),parts=N(p.parts),energy=N(p.energy),pack=N(p.packaging),ship=N(p.shipping),fees=N(p.fees),ads=N(p.ads),other=N(p.other),cost=mat+parts+energy+pack+ship+fees+ads+other,profit=sell-cost,margin=sell?profit/sell*100:0;return{cost,profit,margin}}
function injectProducts(){if(!ensure())return;let host=G('businessPlusBody');if(!host)return;let id='mf40products',box=G(id);if(!box){box=document.createElement('div');box.id=id;box.className='mf40-card mf40-section';host.appendChild(box)}let ps=S.finance.products;box.innerHTML=`<div class="mf40-head"><div><h3>Rentowność produktów</h3><span class="mf40-sub">cena − materiał − części − prąd − opakowanie − wysyłka − prowizje − reklama</span></div><button class="btn primary" onclick="mf40ProductModal()">＋ Produkt</button></div>${ps.length?ps.map((p,i)=>{let z=productProfit(p);return`<div class="mf40-row"><div style="flex:1"><b>${esc(p.name)}</b><small>cena ${PLN(p.price)} • koszt ${PLN(z.cost)}</small><div class="mf40-progress"><i style="width:${Math.max(0,Math.min(100,z.margin))}%"></i></div></div><div><b class="${z.profit>=0?'green':'red'}">${PLN(z.profit)}</b><small>${z.margin.toFixed(1)}% marży</small></div><button class="btn" onclick="mf40EditProduct(${i})">Edytuj</button><button class="btn danger" onclick="mf40RemoveProduct(${i})">Usuń</button></div>`}).join(''):'<p class="muted">Dodaj np. lampę i wpisz wszystkie koszty jednej sztuki, aby widzieć realny zysk.</p>'}`}
function productModal(i=null){let p=i==null?{}:S.finance.products[i]||{},v=(k)=>p[k]??'';open(`<h2>${i==null?'Dodaj':'Edytuj'} produkt</h2><div class="form"><label>Nazwa<input id="pr40name" value="${esc(v('name'))}"></label><label>Cena sprzedaży brutto<input id="pr40price" type="number" step="0.01" value="${v('price')}"></label><label>Materiał<input id="pr40material" type="number" step="0.01" value="${v('material')}"></label><label>Części / komponenty<input id="pr40parts" type="number" step="0.01" value="${v('parts')}"></label><label>Prąd<input id="pr40energy" type="number" step="0.01" value="${v('energy')}"></label><label>Opakowanie<input id="pr40pack" type="number" step="0.01" value="${v('packaging')}"></label><label>Wysyłka<input id="pr40ship" type="number" step="0.01" value="${v('shipping')}"></label><label>Prowizje / płatności<input id="pr40fees" type="number" step="0.01" value="${v('fees')}"></label><label>Reklama / szt.<input id="pr40ads" type="number" step="0.01" value="${v('ads')}"></label><label>Inne<input id="pr40other" type="number" step="0.01" value="${v('other')}"></label></div><button class="btn primary" onclick="mf40SaveProduct(${i==null?'null':i})">Zapisz</button>`)}
window.mf40ProductModal=()=>productModal(null);window.mf40EditProduct=i=>productModal(i);window.mf40SaveProduct=function(i){let p={name:G('pr40name').value.trim()||'Produkt',price:N(G('pr40price').value),material:N(G('pr40material').value),parts:N(G('pr40parts').value),energy:N(G('pr40energy').value),packaging:N(G('pr40pack').value),shipping:N(G('pr40ship').value),fees:N(G('pr40fees').value),ads:N(G('pr40ads').value),other:N(G('pr40other').value)};i==null?S.finance.products.push(p):S.finance.products[i]=p;save();closeModal();injectProducts()};window.mf40RemoveProduct=i=>{if(confirm('Usunąć produkt?')){S.finance.products.splice(i,1);save();injectProducts()}};
function balance(l){try{return N(loanPoint(l).balance)}catch{return N(l.balance)}}
function payoff(l,extra=0){let b=balance(l),r=(l.loanType==='zero'?0:N(l.rate))/1200,p=N(l.payment)+N(extra),m=0,interest=0;if(p<=0)return{m:600,interest:0};while(b>.01&&m<600){let it=b*r;if(p<=it+.001)break;interest+=it;b=Math.max(0,b-(p-it));m++}return{m,interest}}
function injectDebtStrategies(){if(!ensure())return;let host=G('debtBody');if(!host)return,id='mf40debtStrategies',box=G(id);if(!box){box=document.createElement('div');box.id=id;box.className='mf40-card mf40-section';host.appendChild(box)}let loans=[...(S.loans||[])],snow=[...loans].sort((a,b)=>balance(a)-balance(b)),aval=[...loans].sort((a,b)=>N(b.rate)-N(a.rate));box.innerHTML=`<div class="mf40-head"><div><h3>Strategie spłaty</h3><span class="mf40-sub">porównanie kolejności, bez automatycznej decyzji za Ciebie</span></div></div><div class="mf40-grid two"><div class="mf40-mutedBox"><b>Snowball — od najmniejszego salda</b>${snow.map((l,i)=>`<div class="mf40-row"><span>${i+1}. ${esc(l.name)}</span><b>${PLN(balance(l))}</b></div>`).join('')}</div><div class="mf40-mutedBox"><b>Avalanche — od najwyższego oprocentowania</b>${aval.map((l,i)=>`<div class="mf40-row"><span>${i+1}. ${esc(l.name)}</span><b>${N(l.rate).toFixed(2)}%</b></div>`).join('')}</div></div><div class="mf40-dash"></div><div class="mf40-head"><h3>Szybki symulator dodatkowej nadpłaty</h3></div>${loans.map((l,i)=>{let base=payoff(l,0),e100=payoff(l,100),e500=payoff(l,500),e1000=payoff(l,1000);return`<div class="mf40-row"><div><b>${esc(l.name)}</b><small>bez dodatkowej: ${base.m} mies. / odsetki ${PLN(base.interest)}</small></div><div><small>+100 zł: ${e100.m} mies. / oszcz. ${PLN(Math.max(0,base.interest-e100.interest))}</small><small>+500 zł: ${e500.m} mies. / oszcz. ${PLN(Math.max(0,base.interest-e500.interest))}</small><small>+1000 zł: ${e1000.m} mies. / oszcz. ${PLN(Math.max(0,base.interest-e1000.interest))}</small></div></div>`}).join('')||'<p class="muted">Brak kredytów.</p>'}`}
function backups(){try{return JSON.parse(localStorage.getItem('moje-finanse-backups-v1')||'[]')}catch{return[]}}
function injectBackups(){if(!ensure())return;let sec=G('settings');if(!sec)return,id='mf40restore',box=G(id);if(!box){box=document.createElement('div');box.id=id;box.className='mf40-card mf40-section';sec.appendChild(box)}let bs=backups();box.innerHTML=`<div class="mf40-head"><div><h3>Przywracanie kopii</h3><span class="mf40-sub">ostatnie automatyczne kopie lokalne</span></div></div>${bs.length?bs.slice(0,10).map((b,i)=>`<div class="mf40-row"><span>${new Date(b.stamp).toLocaleString('pl-PL')}</span><button class="btn" onclick="mf40RestoreBackup(${i})">Przywróć</button></div>`).join(''):'<p class="muted">Brak kopii.</p>'}`}
window.mf40RestoreBackup=function(i){let b=backups()[i];if(!b)return;if(!confirm('Przywrócić tę kopię? Aktualny stan zostanie zastąpiony.'))return;localStorage.setItem('moje-finanse-v14',JSON.stringify(b.data));location.reload()};
function payrollDiagnostics(){let out=[];try{let g=8452.56,pension=Math.round(g*.0976*100)/100,dis=Math.round(g*.015*100)/100,sick=Math.round(g*.0245*100)/100,social=Math.round((pension+dis+sick)*100)/100,health=Math.round((g-social)*.09*100)/100,pe=Math.round(g*.04*100)/100,er=Math.round(g*.015*100)/100;out.push(['ZUS przykład',Math.abs(social-1158.85)<.02,`${PLN(social)} / 1 158,85 zł`]);out.push(['Zdrowotna przykład',Math.abs(health-656.43)<.02,`${PLN(health)} / 656,43 zł`]);out.push(['PPK Ty 4%',Math.abs(pe-338.10)<.02,`${PLN(pe)} / 338,10 zł`]);out.push(['PPK firma 1,5%',Math.abs(er-126.79)<.02,`${PLN(er)} / 126,79 zł`])}catch(e){out.push(['Silnik płac',false,String(e)])}return out}
function injectDiagnostics(){let sec=G('settings');if(!sec)return,id='mf40diag',box=G(id);if(!box){box=document.createElement('div');box.id=id;box.className='mf40-card mf40-section';sec.appendChild(box)}let tests=payrollDiagnostics(),ok=tests.filter(x=>x[1]).length;box.innerHTML=`<div class="mf40-head"><div><h3>Diagnostyka 4.0</h3><span class="mf40-sub">kontrola silnika na danych z paska wynagrodzenia</span></div><span class="mf40-badge ${ok===tests.length?'fact':'warn'}">${ok}/${tests.length}</span></div>${tests.map(t=>`<div class="mf40-row"><span>${t[1]?'✓':'⚠'} ${t[0]}</span><b class="${t[1]?'green':'red'}">${t[2]}</b></div>`).join('')}`}
function inject(){injectPpk();injectProducts();injectDebtStrategies();injectBackups();injectDiagnostics()}
function hook(){let oldShow=window.show;if(typeof oldShow==='function'&&!oldShow.__mf40planning){let fn=function(v){oldShow(v);setTimeout(inject,0)};fn.__mf40planning=true;window.show=fn}let oldRender=window.render;if(typeof oldRender==='function'&&!oldRender.__mf40planning){let fn=function(){oldRender();setTimeout(inject,0)};fn.__mf40planning=true;window.render=fn}inject()}
window.addEventListener('load',()=>setTimeout(hook,180),{once:true});setTimeout(hook,500);
})();