/* Moje Finanse 4.0 — końcowe poprawki UI */
(function(){
'use strict';
const G=id=>document.getElementById(id),N=v=>+v||0,PLN=v=>new Intl.NumberFormat('pl-PL',{style:'currency',currency:'PLN',minimumFractionDigits:2,maximumFractionDigits:2}).format(N(v));
function homeBars(){if(typeof S==='undefined'||typeof sal!=='function'||typeof comp!=='function')return;let p=sal(),c=comp(),n=p.rows.filter(r=>r.actual).reduce((a,r)=>a+N(r.total),0),g=p.rows.filter(r=>r.actual).reduce((a,r)=>a+N(r.g),0),f=c.rows.filter(r=>r.actual).reduce((a,r)=>a+Math.max(0,N(r.profit!=null?r.profit:r.revenue-r.costs)),0),l=0;for(let m=0;m<12;m++){if(!(p.rows[m]?.actual||c.rows[m]?.actual))continue;let k=`${S.selectedYear}-${String(m+1).padStart(2,'0')}`;(S.loans||[]).forEach(x=>{let h=(x.history||[]).find(z=>z.month===k);if(h)l+=(typeof h.paid==='boolean'?(h.paid?N(h.regularPaid||x.payment):0):N(h.regularPaid!=null?h.regularPaid:h.paid))+(h.isOverpayment===false?0:N(h.extra));else if(k>=(x.asOfDate||'0000-00').slice(0,7))l+=N(x.payment)+N(x.extraMonthly)})}let host=G('homeBars');if(!host)return,mx=Math.max(1,n,g,f,l);host.innerHTML=[[g,'barGross','BRUTTO FAKT'],[n,'barNet','NETTO FAKT'],[f,'barCompany','FIRMA FAKT'],[l,'barLoans','KREDYTY']].map(x=>`<div class="kpiCol"><div class="kpiBar ${x[1]}" style="height:${Math.max(5,x[0]/mx*140)}px"></div><b>${PLN(x[0])}</b><small>${x[2]}</small></div>`).join('')}
function hints(){let map={t40thr:'Roczna granica pierwszego progu podatkowego dla wybranego roku.',t40red:'Roczna kwota zmniejszająca podatek; silnik rozkłada ją miesięcznie.',t40kup:'Koszty uzyskania przychodu stosowane w kalkulacji listy płac.',ppk40ret:'Założenie do symulacji PPK — nie jest gwarantowaną stopą zwrotu.'};Object.entries(map).forEach(([id,t])=>{let e=G(id);if(e)e.title=t});document.querySelectorAll('#months input[id^="sp"]').forEach(e=>e.title='Procent wynagrodzenia/zasiłku chorobowego używany w estymacji L4.');document.querySelectorAll('#months input[id^="vg"]').forEach(e=>e.title='Wpisz zmienne składniki brutto istotne dla podstawy wynagrodzenia urlopowego.')}
let autoTimer=null;function autosave(e){let input=e.target;if(!input.closest('#months .mf40-month'))return;let m=input.id.match(/(\d+)$/);if(!m)return;let i=+m[1];clearTimeout(autoTimer);autoTimer=setTimeout(()=>{if(typeof window.mf40SaveSalary==='function')window.mf40SaveSalary(i)},350)}
function bind(){let months=G('months');if(months&&!months.dataset.mf40Auto){months.dataset.mf40Auto='1';months.addEventListener('change',autosave)}homeBars();hints()}
function hook(){let oldShow=window.show;if(typeof oldShow==='function'&&!oldShow.__mf40ui){let fn=function(v){oldShow(v);setTimeout(bind,0)};fn.__mf40ui=true;window.show=fn}let oldRender=window.render;if(typeof oldRender==='function'&&!oldRender.__mf40ui){let fn=function(){oldRender();setTimeout(bind,0)};fn.__mf40ui=true;window.render=fn}bind()}
window.addEventListener('load',()=>setTimeout(hook,260),{once:true});setTimeout(hook,650);
})();