/* Moje Finanse 4.1 — bezpieczne rozszerzenia stabilnej wersji */
(function(){
'use strict';
const VERSION='4.1.0',G=id=>document.getElementById(id),N=v=>+v||0,PLN=v=>new Intl.NumberFormat('pl-PL',{style:'currency',currency:'PLN',minimumFractionDigits:2,maximumFractionDigits:2}).format(N(v)),esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
function ensure(){if(typeof S==='undefined')return false;S.finance||={};let f=S.finance;f.products||=[];f.categoryLimits||={};f.assets||=[];f.goals||=[];f.informalDebts||=[];f.ppkOpening=N(f.ppkOpening);f.ppkReturnPct=N(f.ppkReturnPct)||5;return true}
function setVersion(){document.title='Moje Finanse '+VERSION;let h=document.querySelector('.top small');if(h)h.innerHTML=`<span id="headerYear">${typeof S!=='undefined'?S.selectedYear:''}</span> • wersja ${VERSION}`;document.documentElement.dataset.appVersion=VERSION}
function currentBalance(l){try{return N(loanPoint(l).balance)}catch{return N(l.balance)}}
function informalRemaining(d){return Math.max(0,N(d.amount)-(d.payments||[]).reduce((a,p)=>a+N(p.amount),0))}
function backup(force=false){if(!ensure())return;try{let k='moje-finanse-backups-v1',a=JSON.parse(localStorage.getItem(k)||'[]'),now=Date.now(),last=a[0]?.stamp?new Date(a[0].stamp).getTime():0;if(!force&&now-last<6*3600000)return;a.unshift({stamp:new Date().toISOString(),data:JSON.parse(JSON.stringify(S))});localStorage.setItem(k,JSON.stringify(a.slice(0,10)));S.finance.lastBackup=new Date().toISOString()}catch(e){console.warn('backup41',e)}}
function wrapSave(){let old=window.save;if(typeof old!=='function'||old.__mf41)return;let fn=function(){old();backup(false)};fn.__mf41=true;window.save=fn}
function ppkAnnual(){try{let p=sal(),act=p.rows.filter(r=>r.actual),m=Math.max(1,act.length),sum=act.reduce((a,r)=>a+N(r.pe)+N(r.er),0);return sum/m*12}catch{return 0}}
function fv(open,annual,rate,years){let v=N(open),r=N(rate)/100/12;for(let i=0;i<years*12;i++)v=v*(1+r)+annual/12;return v}
function injectPpk(){let host=G('wealthBody');if(!host||G('ppkProjection41'))return;let a=ppkAnnual(),open=N(S.finance.ppkOpening),rate=N(S.finance.ppkReturnPct)||5,box=document.createElement('div');box.id='ppkProjection41';box.className='card';box.innerHTML=`<div class="title">PPK — prognoza długoterminowa <span class="pill">symulacja</span></div><div class="grid"><div class="tile"><small>ROCZNE WPŁATY EST.</small><b>${PLN(a)}</b></div><div class="tile"><small>5 LAT</small><b>${PLN(fv(open,a,rate,5))}</b></div><div class="tile"><small>10 LAT</small><b>${PLN(fv(open,a,rate,10))}</b></div><div class="tile"><small>20 LAT</small><b>${PLN(fv(open,a,rate,20))}</b></div><div class="tile"><small>30 LAT</small><b>${PLN(fv(open,a,rate,30))}</b></div></div><p class="muted">Symulacja przy stopie zwrotu ${rate.toFixed(1)}% rocznie. To nie jest gwarantowany wynik inwestycyjny.</p>`;host.appendChild(box)}
function productProfit(p){let cost=['material','parts','energy','packaging','shipping','fees','ads','other'].reduce((a,k)=>a+N(p[k]),0),profit=N(p.price)-cost;return{cost,profit,margin:N(p.price)?profit/N(p.price)*100:0}}
function injectProducts(){let host=G('businessPlusBody');if(!host||G('products41'))return;let ps=S.finance.products,box=document.createElement('div');box.id='products41';box.className='card';box.innerHTML=`<div class="title">Rentowność produktów <button class="btn primary" onclick="productModal41()">＋ Produkt</button></div><p class="muted">Cena sprzedaży minus materiał, komponenty, prąd, opakowanie, wysyłka, prowizje, reklama i pozostałe koszty.</p>${ps.length?ps.map((p,i)=>{let z=productProfit(p);return`<div class="row"><div style="flex:1"><b>${esc(p.name)}</b><small>cena ${PLN(p.price)} • koszt ${PLN(z.cost)} • marża ${z.margin.toFixed(1)}%</small></div><b class="${z.profit>=0?'green':'red'}">${PLN(z.profit)}</b><button class="btn" onclick="productModal41(${i})">Edytuj</button><button class="btn danger" onclick="removeProduct41(${i})">Usuń</button></div>`}).join(''):'<p class="muted">Dodaj pierwszy produkt.</p>'}`;host.appendChild(box)}
window.productModal41=function(i=null){let p=i==null?{}:S.finance.products[i]||{},v=k=>p[k]??'';open(`<h2>${i==null?'Dodaj':'Edytuj'} produkt</h2><div class="form"><label>Nazwa<input id="p41n" value="${esc(v('name'))}"></label><label>Cena sprzedaży brutto<input id="p41price" type="number" step="0.01" value="${v('price')}"></label><label>Materiał<input id="p41mat" type="number" step="0.01" value="${v('material')}"></label><label>Komponenty<input id="p41parts" type="number" step="0.01" value="${v('parts')}"></label><label>Prąd<input id="p41energy" type="number" step="0.01" value="${v('energy')}"></label><label>Opakowanie<input id="p41pack" type="number" step="0.01" value="${v('packaging')}"></label><label>Wysyłka<input id="p41ship" type="number" step="0.01" value="${v('shipping')}"></label><label>Prowizje/płatności<input id="p41fees" type="number" step="0.01" value="${v('fees')}"></label><label>Reklama / szt.<input id="p41ads" type="number" step="0.01" value="${v('ads')}"></label><label>Inne<input id="p41other" type="number" step="0.01" value="${v('other')}"></label></div><div class="actions"><button class="btn" onclick="closeModal()">Anuluj</button><button class="btn primary" onclick="saveProduct41(${i==null?'null':i})">Zapisz</button></div>`)};
window.saveProduct41=function(i){let p={name:G('p41n').value.trim()||'Produkt',price:N(G('p41price').value),material:N(G('p41mat').value),parts:N(G('p41parts').value),energy:N(G('p41energy').value),packaging:N(G('p41pack').value),shipping:N(G('p41ship').value),fees:N(G('p41fees').value),ads:N(G('p41ads').value),other:N(G('p41other').value)};i==null?S.finance.products.push(p):S.finance.products[i]=p;save();closeModal();G('products41')?.remove();injectProducts()};window.removeProduct41=i=>{if(confirm('Usunąć produkt?')){S.finance.products.splice(i,1);save();G('products41')?.remove();injectProducts()}};
function injectLimits(){let host=G('budgetBody');if(!host||G('limits41'))return;let cats={};(S.finance.expenses||[]).filter(e=>e.active!==false).forEach(e=>{let c=e.category||'Inne';cats[c]=(cats[c]||0)+N(e.amount)});let box=document.createElement('div');box.id='limits41';box.className='card';box.innerHTML=`<div class="title">Limity kategorii <button class="btn" onclick="limitModal41()">Ustaw limit</button></div>${Object.keys(cats).length?Object.entries(cats).map(([c,v])=>{let l=N(S.finance.categoryLimits[c]),p=l?Math.min(100,v/l*100):0;return`<div class="row"><div style="flex:1"><b>${esc(c)}</b><small>${PLN(v)}${l?' / '+PLN(l):' • brak limitu'}</small><div class="progress"><i style="width:${p}%"></i></div></div><b class="${l&&v>l?'red':''}">${l&&v>l?'+'+PLN(v-l):l?Math.round(p)+'%':'—'}</b></div>`}).join(''):'<p class="muted">Dodaj wydatki z kategoriami.</p>'}`;host.appendChild(box)}
window.limitModal41=function(){open(`<h2>Limit kategorii</h2><div class="form"><label>Kategoria<input id="l41c"></label><label>Limit miesięczny<input id="l41v" type="number" step="0.01"></label></div><button class="btn primary" onclick="saveLimit41()">Zapisz</button>`)};window.saveLimit41=function(){let c=G('l41c').value.trim(),v=N(G('l41v').value);if(c)S.finance.categoryLimits[c]=v;save();closeModal();G('limits41')?.remove();injectLimits()};
function payoff(l,extra=0){let b=currentBalance(l),r=(l.loanType==='zero'?0:N(l.rate))/1200,p=N(l.payment)+N(extra),m=0,interest=0;if(p<=0)return{m:600,interest};while(b>.01&&m<600){let it=b*r;if(p<=it+.001)return{m:600,interest};interest+=it;b=Math.max(0,b-(p-it));m++}return{m,interest}}
function injectDebt(){let host=G('debtBody');if(!host||G('debtSim41'))return;let informal=(S.finance.informalDebts||[]).reduce((a,d)=>a+informalRemaining(d),0),bank=(S.loans||[]).reduce((a,l)=>a+currentBalance(l),0),box=document.createElement('div');box.id='debtSim41';box.className='card';box.innerHTML=`<div class="title">Pełny obraz zadłużenia</div><div class="grid"><div class="tile"><small>KREDYTY BANKOWE</small><b>${PLN(bank)}</b></div><div class="tile"><small>0% / BEZ TERMINU</small><b>${PLN(informal)}</b></div><div class="tile"><small>RAZEM</small><b>${PLN(bank+informal)}</b></div></div><div class="title" style="margin-top:14px">Symulator dodatkowej nadpłaty</div>${(S.loans||[]).map(l=>{let b=payoff(l),x100=payoff(l,100),x500=payoff(l,500),x1000=payoff(l,1000);return`<div class="row"><div><b>${esc(l.name)}</b><small>bazowo ${b.m} mies. • odsetki ${PLN(b.interest)}</small></div><div><small>+100: ${x100.m} mies. / oszcz. ${PLN(Math.max(0,b.interest-x100.interest))}</small><small>+500: ${x500.m} mies. / oszcz. ${PLN(Math.max(0,b.interest-x500.interest))}</small><small>+1000: ${x1000.m} mies. / oszcz. ${PLN(Math.max(0,b.interest-x1000.interest))}</small></div></div>`}).join('')||'<p class="muted">Brak kredytów.</p>'}`;host.appendChild(box)}
function injectWealthDebt(){let host=G('wealthBody');if(!host||G('wealthDebt41'))return;let inf=(S.finance.informalDebts||[]).reduce((a,d)=>a+informalRemaining(d),0);if(!inf)return;let box=document.createElement('div');box.id='wealthDebt41';box.className='card';box.innerHTML=`<div class="title">Dodatkowe zobowiązania 0%</div><div class="row"><span>Do oddania bez terminu</span><b>${PLN(inf)}</b></div><p class="muted">Ta kwota powinna być uwzględniana przy ocenie rzeczywistej wartości netto.</p>`;host.appendChild(box)}
function injectBackup(){let sec=G('settings');if(!sec||G('backup41'))return;let box=document.createElement('div');box.id='backup41';box.className='card';let arr=[];try{arr=JSON.parse(localStorage.getItem('moje-finanse-backups-v1')||'[]')}catch{}box.innerHTML=`<div class="title">Kopie bezpieczeństwa <span class="pill">max 10</span></div><div class="row"><span>Ostatnia kopia</span><b>${arr[0]?.stamp?new Date(arr[0].stamp).toLocaleString('pl-PL'):'—'}</b></div><button class="btn" onclick="backupNow41()">Utwórz kopię teraz</button>${arr.slice(0,5).map((b,i)=>`<div class="row"><small>${new Date(b.stamp).toLocaleString('pl-PL')}</small><button class="btn" onclick="restoreBackup41(${i})">Przywróć</button></div>`).join('')}`;sec.appendChild(box)}
window.backupNow41=function(){backup(true);save();G('backup41')?.remove();injectBackup()};window.restoreBackup41=function(i){let a=[];try{a=JSON.parse(localStorage.getItem('moje-finanse-backups-v1')||'[]')}catch{}let b=a[i];if(!b||!confirm('Przywrócić tę kopię?'))return;localStorage.setItem('moje-finanse-v14',JSON.stringify(b.data));location.reload()};
function injectVersionNote(){let sec=G('settings');if(!sec||G('v41note'))return;let b=document.createElement('div');b.id='v41note';b.className='card';b.innerHTML=`<div class="title">Moje Finanse ${VERSION}</div><p class="muted">Stabilna baza + kadry, podatki per rok, wydatki stałe/jednorazowe, limity kategorii, PPK długoterminowe, rentowność produktów, zobowiązania 0%, symulatory nadpłat i automatyczne kopie danych.</p>`;sec.appendChild(b)}
function inject(){if(!ensure())return;setVersion();injectPpk();injectProducts();injectLimits();injectDebt();injectWealthDebt();injectBackup();injectVersionNote()}
function hook(){if(!ensure())return;wrapSave();let r=window.render;if(typeof r==='function'&&!r.__mf41){let fn=function(){let out=r();setTimeout(inject,0);return out};fn.__mf41=true;window.render=fn}let s=window.show;if(typeof s==='function'&&!s.__mf41){let fn=function(v){let out=s(v);setTimeout(inject,0);return out};fn.__mf41=true;window.show=fn}inject()}
window.addEventListener('finance-modules-ready',()=>setTimeout(hook,60),{once:true});window.addEventListener('load',()=>setTimeout(hook,650),{once:true});setTimeout(hook,1200);
})();